### ISSUE TITLE
Using @angular/language-service with language server report errors with HTML files

### ISSUE THREAD

**Issue by yanxi0830** [typescript-language-server/typescript-language-server#104]
Hi, I am trying to integrate `@angular/language-service` plugin with the language server via the global plugins initializationOptions. This works with template inside Typescript files, but not with templates as html files. If I execute the language server with HTML content types, it reports a bunch of typescript errors. 

![typescript-ls](https://user-images.githubusercontent.com/19946372/54455855-228bc400-4733-11e9-80f2-593e1684667a.png)

Is there any options to disable the errors while enabling the @angular/language-service for HTML files? 

Possibly related? https://github.com/Microsoft/TypeScript/issues/17151

**Comment by mickaelistria** [comment]
I've reported it upstream as I think it's an issue that tsserver even tries to parse the `.html` file if there is no plugin instructing it to do it: https://github.com/microsoft/TypeScript/issues/31423

**Comment by apexskier** [comment]
> If I execute the language server with HTML content types, it reports a bunch of typescript errors.

I think this is the core issue. If you don't execute the language server with html files, it won't report issues for them. To my knowledge, most client language server implementations require you to specify which languages/syntaxes to apply the language server to - [Sublime text](https://github.com/sublimelsp/LSP-typescript/blob/0f51d6f3ec4951ee9193e7a6aaa90ab9b91f107b/LSP-typescript.sublime-settings#L3-L33), [Nova](https://github.com/apexskier/nova-typescript/blob/a8aaa3b83e366593a80517c3cbe646da31f08821/src/main.ts#L184) as two examples - so something in your setup is instructing `language-service-plugin` to process HTML files without any real support for it.

In this case though, I'd need much more detail to know how Eclipse/`@angular/language-service`/`language-service-plugin` are working together to try to understand this issue.

**Comment by rchl** [comment]
I've investigated this a bit.

The typescript plugin doesn't support HTML files, only inline templates in ts files.

https://github.com/angular/vscode-ng-language-service also includes a dedicated language server that support html templates also. I believe they only provide VSCode extension but if you search a bit you might be able to find server adapted for your editor. For example there is https://github.com/sublimelsp/LSP-angular for Sublime Text.
