### ISSUE TITLE
Allow empty or null workspaceSymbols query

### ISSUE THREAD

**Issue by mickaelistria** [typescript-language-server/typescript-language-server#108]
While the spec says the query for workspaceSymbols mustn't be null or empty, it seems more pragmatic and useful to allow it to be null or empty to return everything (that would be helpful for Eclipse LSP4E integration of workspace symbols relying on Quick Access for instance).
Currently, a null or empty query would return nothing, can it be changed so it returns everything?

**Comment by weilbith** [comment]
Did anyone has ever put some work in here?

**Comment by DonnieWest** [comment]
Nope, but PRs welcome

Poking around though, it appears the spec was updated a year ago to accommodate this use case.

See the spec here
 https://microsoft.github.io/language-server-protocol/specification.html#workspace_symbol

 And the change here

https://github.com/microsoft/language-server-protocol/pull/770

**Comment by weilbith** [comment]
I thought [this inline-doc](https://github.com/microsoft/TypeScript/blob/6643d973856d89ef9f2e85e46fe5e460503ff256/lib/protocol.d.ts#L2128) was a hint that `'.*'` would do the work. But apparently it does not. In this code-base I could not find any evaluation of the query parameter isn't there?

**Comment by DonnieWest** [comment]
https://github.com/theia-ide/typescript-language-server/blob/master/server/src/lsp-server.ts#L837-L858

Here's the function that accepts the incoming request

**Comment by weilbith** [comment]
Yes. I followed the flow from there to the tsp client etc, but I could not find where the query is filtered for an empty string. It must be way more deep and is not a simple parameter guard.

**Comment by rchl** [comment]
This is not a limiting in this server as mentioned above.

As far as I can see this code in `typescript` ends up ignoring empty query: https://github.com/microsoft/TypeScript/blob/1ade73df2bf3e83085ca4647d0a3339abe3f869b/src/services/patternMatcher.ts#L107-L109

So this can be requested in `typescript` repo instead.
