### ISSUE TITLE
CLI --socket appears to do nothing

### ISSUE THREAD

**Issue by xevrem** [typescript-language-server/typescript-language-server#111]
I'm trying to use this tool to do some javascript/typescript analysis/processing and I cannot get a socketed server to run.

if I enter `typescript-language-server --socket 3000` or `node server/lib/cli.js --socket 3000` it just does nothing. No errors, no warnings, no silent process forks... nothing. Note: `--stdio` does seem to create a server, but that is also not particularly useful for my usecase (at present)

what am I doing wrong?

NOTE: i do have globally available tsservers and i've also tried building directly with this repo

**Comment by DonnieWest** [comment]
It doesn't appear that you're doing anything wrong. We're just currently not starting a server. I'm thinking we remove those CLI options unless someone wants to implement a proper socketed connection
