### ISSUE TITLE
experimentalDecorators: true ignored in Angular 5xxx projects in Emacs

### ISSUE THREAD

**Issue by adriandeveloper** [typescript-language-server/typescript-language-server#113]
Bug: When loading an Angular 5 project (legacy work project), LSP is reporting that the decorators like @Output(), @Input() are experimental and are subject to change.  

![Imgur](https://i.imgur.com/e0Fk83B.png)

These errors are littered thorough the project and is causing ~~LSP to crash~~ lsp-ui to become disabled due to the amounts of `errors` it reports. 

The error suggests setting `experimentalDecorators` to true to get rid of that warning and it is setup in the `tsconfig.json` file but it seems that LSP is `ignoring` this setting.

![Imgur](https://i.imgur.com/YIx7b8j.png)

Note that this only seems to happen with Angular 5 projects and below.  I've started an Angular 8x project and there are no `experimentalDecorators` errors present.

**To Reproduce**
Load an Angular 5 project and view a .ts file. Errors should pop up if the LSP server starts. 
Other older projects the server crashes (may submit a separate bug for that later).

Since I'm working on an Angular 5 project, I can't share that code, but here is a fork of an [Angular 5 project](https://github.com/adriandeveloper/Angular5-Seed.git) where the same error is present.  

Just clone and run npm install (or yarn).

**Expected behavior**
When LSP starts and `experimentalDecorators `are true, there should be no errors.  

**OS**
Mac OS Mojave

**Error callstack**
No error other than what's displayed.

**Note**
I also use VSCode for this project (moving over to Emacs + Evil Mode) and there are no LSP errors of this nature in VSCode.

**Comment by jguenther** [comment]
I'm having this problem after upgrading a project to Angular 10.

I've tried adding this to the top of `compilerOptions` in my tsconfig for this project, but I'm still seeing these errors everywhere that uses decorators. it doesn't cause build failures, just errors showing up in lsp

```
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowJs": true,
```

**Comment by rchl** [comment]
The `typescript` dependency in your project might have been to old and did not support the `experimentalDecorators` setting.

Could try upgrading it but then that might cause other compatibility issue with your project.

**Comment by adriandeveloper** [comment]
True. 

Well that was for my old job and I've moved on.  New company has a far better stack.  

Thanks for the help. Closing this.

**Comment by eduardoheleno** [comment]
im having the same problem in a nestjs project
![image](https://github.com/typescript-language-server/typescript-language-server/assets/61231740/714cd214-b944-4608-be8a-c17b1cf8365a)

**Comment by predragnikolic** [comment]
@eduardoheleno please provide an example to reproduce the issue.

And information like what text editor are you using, what is your version of TypeScript and what is your version of the TypeScript language server?
