### ISSUE TITLE
tsserver options

### ISSUE THREAD

**Issue by lgranie** [typescript-language-server/typescript-language-server#122]
Hi,

I've installed npm locally in my home directory.
There is no option for typescript-language-server to specify the npm binary path.
tsserver has the option -npmLocation.

Should be a good, IMHO, to replace all --tsserver-* options with a --ttsserver-options option.

Regards,
Laurent

**Comment by uqix** [comment]
With brew node, I got this ` [tsserver] /bin/sh: /usr/local/Cellar/node/12.5.0/bin/npm: No such file or directory`

**Comment by PetarMetodiev** [comment]
I also got this error.

**Comment by jeffvandyke** [comment]
Do you think it would be better to specify these tsserver options (as this project's stated goal is to wrap tsserver) to interpret any options following a "`--`" be passed to `tsserver`?

**Comment by lgranie** [comment]
Yes. As long as we can access to all the tsserver options, it's a good idea.

**Comment by dylanirlbeck** [comment]
@uqix @PetarMetodiev Did either of you fix this error? I'm getting the same thing.

**Comment by uqix** [comment]
Noop

**Comment by PetarMetodiev** [comment]
No 😕

**Comment by harto** [comment]
There are a couple of possible workarounds until this is fixed:
 - symlink `npm` into the same directory as `node` (per https://github.com/microsoft/TypeScript/issues/23924#issuecomment-770216873)
 - provide a wrapper around `tsserver` that invokes it with the desired arguments, then pass that to `typescript-language-server`. E.g.:

```console
typescript-language-server --tsserver-path my-tsserver-wrapper
```
where `my-tsserver-wrapper` is a shell script like:
```bash
exec tsserver --npmLocation "$(which npm)" "$@"
```

I think the fix suggested by @lgranie sounds ideal, though.
