### ISSUE TITLE
New file does not get import candidates from node_modules

### ISSUE THREAD

**Issue by uqix** [typescript-language-server/typescript-language-server#124]
It seems that the newly created js file does not be treated as a member file of the react-app project, cause the completion candidates do not take node_modules into account.

__Steps to reproduce:__

1. npx create-react-app my-app
2. add jsconfig.json
3. npm -S install redux
4. npm -S install redux-saga
5. Open src/App.js, in function, type take, import works (import { take } from '@redux-saga/core/effects';)
6. New src/Hello.js, in function, type take, no import candidates
7. Restart lsp (just close all project buffers)
8. Open src/Hello.js, in function, type take, import works (import { take } from '@redux-saga/core/effects';)

```json
{
    "compilerOptions": {
        "target": "ES6",
        "moduleResolution": "Node",
        "jsx": "react",
        "jsxFactory": "jsx"
    },
    "include": ["src/**/*"]
}
```
-----------------------

Answer from @yyoncho

> Based on my experiments it looks like it is a language server issue caused by the fact that when you open a new file there is no file on the disk but only a in memory buffer. For example, if you do touch foo.js before opening foo.js it will work just fine although lsp-mode will send the same set of notifications to the server.
> As per lsp spec the server is supposed to use the content that is sent from the client, and it should not read the disk content.

**Comment by rchl** [comment]
I can't reproduce it using those steps. I feel like `create-react-app` creates different project these days. If you have updated steps then feel free to post and I'll check it out.
