### ISSUE TITLE
How to disable 'Could not find a declaration file for module'

### ISSUE THREAD

**Issue by raxod502** [typescript-language-server/typescript-language-server#142]
I have a JavaScript file which includes

```javascript
import "regenerator-runtime/runtime";
```

and this gets a warning from the language server

```
typescript: Could not find a declaration file for module 'regenerator-runtime/runtime'.
'<filename>' implicitly has an 'any' type
Try `npm install @types/regenerator-runtime` if it exists or add a new declaration (.d.ts) file
containing `declare module 'regenerator-runtime/runtime';` [7016]
```

This is not a useful warning because my code is not TypeScript and I do not care about types. How can I disable the warning? Here's what I already tried:

* Create a file `types.d.ts` next to my `index.js` containing `declare module '*';` (I use Parcel to compile my webapp)
* Create a `tsconfig.json` in my project root with `{ "compilerOptions": { "noImplicitAny": false } }`
* Install type definitions just to make the server happy -- unfortunately none exist
* Add to line before the import `// @ts-ignore`

None of these do anything, even after I restart the language server. How do I disable the warning?

**Comment by keyboard-clacker** [comment]
I'm also having trouble with this. @raxod502 did you ever find a solution?

**Comment by raxod502** [comment]
I am looking at that line of code in my project right now, and currently no warning is being displayed. However, I cannot for the life of me figure out why that might be. [Here is the code](https://github.com/MuddCreates/life-after-mudd/blob/f1e0cad7f32c1eefbd126832a2d125a181edf6c6/static/js/admin.js#L3), though, in case it is helpful.

**Comment by jangid** [comment]
I am also have the same problem. Is there a fix for this?

**Comment by alixander** [comment]
bump

**Comment by HannaNguyen-new** [comment]
I have the same problem. I don't use typescript but when i require skipper the warning appears.
`const skipper = require('skipper-better-s3')`

Would appreciate any solution to this.

**Comment by rchl** [comment]
It will be possible to ignore specific diagnostics with the new `diagnostics.ignoredCodes` option in next release.
