### ISSUE TITLE
Typescript can't find absolute imports even when tsconfig has baseUrl attribute

### ISSUE THREAD

**Issue by LukeWood** [typescript-language-server/typescript-language-server#145]
e.x.

<img width="303" alt="Screen Shot 2020-03-30 at 4 38 28 PM" src="https://user-images.githubusercontent.com/12191303/77971935-e4613400-72a4-11ea-9398-62b24a7f4fe7.png">

**Comment by javoire** [comment]
Actually this server _does_ support this, as opposed to https://github.com/sourcegraph/javascript-typescript-langserver ([#680](https://github.com/sourcegraph/javascript-typescript-langserver/issues/680))

What does your `tsconfig.json` look like? 

Here's an example app with working absolute imports: https://github.com/javoire/sourcegraph-javascript-typescript-langserver-testcase

This is the specific config enabling it
https://github.com/javoire/sourcegraph-javascript-typescript-langserver-testcase/blob/master/tsconfig.json#L25-L29

**Comment by mngyuan** [comment]
have the same issue, using this server in my vim but getting the following
`import { UserEvents } from '~/utils/Constants'; typescript: Cannot find module '~/utils/Constants'.`

`tsconfig.json`:
```json
  "paths": {
    "~/*": ["src/*"],
    "assets/*": ["assets/*"]
  }
```

`src/utils/Constants.ts` exists

**Comment by rchl** [comment]
You need to specify `baseUrl` for those to work. For example `"baseUrl": "."` should do.

**Comment by rchl** [comment]
Those initial issue was about absolute paths, not path maps.

**Comment by rchl** [comment]
Closing since the initial issue seems invalid. The path shown in the screenshot would be resolved against node_modules, not the `baseUrl`.
