### ISSUE TITLE
Create documentSymbol for constants blocks

### ISSUE THREAD

**Issue by mickaelistria** [typescript-language-server/typescript-language-server#147]
When there are many constant declarations grouped in the same file, it would be convenient to create a "group" documentSymbol for the block of definitions.
That would allow outlines to allow collapsing this block.
This suggestion comes @AlexLuya usage of Wild Web Developer: https://github.com/eclipse/wildwebdeveloper/issues/404

**Comment by rchl** [comment]
Sorry but I don't think it makes sense to create a group for constants. If we are grouping constants then why not normal variables or classes or functions? This shouldn't be arbitrary IMO.

Also, what would be the `kind` (https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#symbolKind) of that additional "group"?
