### ISSUE TITLE
Get TypeScript version which consumes tsserver

### ISSUE THREAD

**Issue by angelozerr** [typescript-language-server/typescript-language-server#16]
As is exists 3 strategies to retrieve tsserver (workspace, global, used by typescript-language-server) It should be very nice if client (ex: Eclipse IDE)  could display in a status bar (or other thing) the TypeScript version used to execute tsserver.

Perhaps a notification message like this:

```
NotificationMessage
{
  "jsonrpc": "2.0",
  "method": "window/showMessage",
  "params": {
    "type": 4,
    "message": "TypeScript 2.5"
  }
}
```

or with other kind of message?

**Comment by svenefftinge** [comment]
Yes, simply logging on info level would turn this into such a message.

**Comment by prabirshrestha** [comment]
Would also be good to actually have a command that returns tsserver info so clients can ask for it manually. typescript version as well as the absolute path.

**Comment by rchl** [comment]
Log message was added in #292 though it will be a full sentence so not sure how easily consumable for the UI.
