### ISSUE TITLE
how to disable this may be converted to async function error

### ISSUE THREAD

**Issue by NikosEfthias** [typescript-language-server/typescript-language-server#166]
I am happy using promises instead of async functions at certain places but typescript language server constantly reports errors saying those functions can be converted to async functions which should be a code action i believe not an error message 
Is there any way to disable certain messages?
Something similar to the `#[allow]` annotation in rust which disables certain warnings

**Comment by DonnieWest** [comment]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#ts-ignore-or-ts-expect-error

Is this what you're looking for?

**Comment by NikosEfthias** [comment]
@DonnieWest this is not a typescript error the tsc doesnt report any errors this is just a diagnostic reported by typescript-language-server and since it is not a real error ts-ignore doesnt really help with that

**Comment by pyrho** [comment]
Coc handles this via a coc-specific configuration setting, when `"typescript.suggestionActions.enabled": false`, [coc will filter out](https://github.com/neoclide/coc-tsserver/blob/ed538dc3b55bb94efe2bc511327d81a90c00e674/src/server/features/diagnostics.ts#L140) all suggestions (except unused variable, but that's pretty opinionated).

I can take a look at tackling this (it's been bothering me too :P); this could be done via a command line switch like `--ignore-diagnostic-code 42` (which could occur multiple times), which would then be used to filter out the diagnostics sent back to neovim.

What do you think @DonnieWest  ?

**Comment by DonnieWest** [comment]
@pyrho sounds like a plan :)

**Comment by NikosEfthias** [comment]
How about block specific ignores? similar to `allow` macro of rust or `ts-ignore` annotation of typescript ?
