### ISSUE TITLE
Support for `didChangeWatchedFiles` workspace method

### ISSUE THREAD

**Issue by corneliusweig** [typescript-language-server/typescript-language-server#171]
The language server protocol defines the `didChangeWatchedFiles` workspace [method](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeWatchedFiles) to notify the language server about changes in files that are part of the workspace, but not currently opened. It is encouraged to support this method, to reduce the number of processes that watch for files and thus unnecessarily use more system resources.

My understanding is that `typescript-language-server` currently uses the node file watching APIs of the underlying `tsserver` to watch for such file changes, which ignores this protocol method. Are there plans to support the `didChangeWatchedFiles` method in the future? Or are there fundamental obstacles that make this impossible?

**Comment by rchl** [comment]
As you said, currently `tsserver` does the file watching.

Typescript's code is massive and what it watches exactly and when is not documented anywhere so:
 - moving that logic to the `typescript-language-server`'s side would be major undertaking
 - I don't believe there is an API to notify tsserver about unopened file being changed (though I haven't researched much)
 - I haven't even seen an option to disable `tsserver`'s own file watching.

So I would say that the way it works now is "as designed" and it's not really visible to change that.

**Comment by corneliusweig** [comment]
Ok, thanks for the clarification.
