### ISSUE TITLE
add support for linkedEditingRange for react tsx tags

### ISSUE THREAD

**Issue by prabirshrestha** [typescript-language-server/typescript-language-server#179]
Spec: https://microsoft.github.io/language-server-protocol/specification#textDocument_linkedEditingRange
Client Implementation: https://github.com/prabirshrestha/vim-lsp/pull/1022

Demo with a different language server.

https://user-images.githubusercontent.com/629908/103635937-993f2480-4f8c-11eb-873a-63b7f31986d5.mp4

**Comment by predragnikolic** [comment]
I didn't new about linked ranges, pretty cool. 

But the precondition for that is to bump the "vscode-languageserver" up to support the 3.16 spec.
