### ISSUE TITLE
Typescript-language-server, used with lsp-mode in emacs, locks files preventing build

### ISSUE THREAD

**Issue by RKBK** [typescript-language-server/typescript-language-server#186]
Hi,

I'm using emacs-lsp for vue and typescript, through vetur, eslint and ts-ls. I regularly need to rebuild my project code using a command like `yarn build` (from a terminal outside emacs). However, the typescript-language-server (ts-ls) invoked in emacs locks my files, so that the yarn build command fails. The build command first runs a clean.js file which just goes through the directories and tries to delete all the files. I need to kill the typescript-language-server, before I can run yarn build.

I get errors like 
```
  errno: -4051,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
```

when it tries to run stuff like
```
 at Array.forEach (<anonymous>)
    at deleteDirRecursive
```
to remove the built files before building. 

Is there an option I should set to prevent typescript-language-server from locking my files?

**Comment by rchl** [comment]
Is this on Windows?

**Comment by RKBK** [comment]
Sorry for my delay in answering. This is running emacs under Windows subsystem for linux (WSL), and with the `build` process running under windows terminal (i.e. not under WSL).

**Comment by RKBK** [comment]
Running everything inside WSL (i.e. emacs, the language server, and yarn) seems to let me avoid this problem.

**Comment by rchl** [comment]
Sorry but I don't think this server can do anything about this issue. The locking is likely due to what the `tsserver` itself does and we have no control over that.
