### ISSUE TITLE
jsdoc generation for js/jsx/ts/tsx

### ISSUE THREAD

**Issue by nimo23** [typescript-language-server/typescript-language-server#194]
When creating the jsdoc comment above a method, constructor, etc. then it does not include the return type or the properties in this jsdoc. 

```
// When including jsdoc, props and return type should be included.
/** 
*/
constructor(item: Item){
}
```

Should be:

```
/** 
 * @param item
*/
constructor(item: Item){
}

/**
* @return item
*/
get getItem(): Item{
    return this.item;
}
```

Would be nice to include this information automatically in jsdoc.

Would be also nice to support auto-completion for including outside properties and methods within jsdoc. For example, when mentioning another method within jsdoc..

**Comment by rchl** [comment]
Are you creating JSDoc through server's code action or manually? If manually then there is no way to do it like that.

In some cases server provides code actions to create the jsdoc block but I'm not sure now if it fills out the params.

**Comment by rchl** [comment]
In any case, that would be something that would be provided through code actions so the implementation would live in typescript. Feel free to report a feature request in the typescript repo if it's still an issue.
