### ISSUE TITLE
Support function arguments in completion snippets

### ISSUE THREAD

**Issue by andersevenrud** [typescript-language-server/typescript-language-server#198]
I came across https://github.com/theia-ide/typescript-language-server/issues/15 while doing some research , and this was closed with a recommendation to OP to make a new issue when it came to snippet support (i.e function parentheses and function arguments / signature) on completion, but never did.

So I thought I'd open one as I would love to see support for this feature.

**Comment by hungrybirder** [comment]
I really want this feature.

**Comment by rchl** [comment]
I've investigated how https://github.com/neoclide/coc-tsserver (which is a fork of vscode's TS language features) handles that and it appears that there is quite a bit of custom code to support that (through optional setting).

**Comment by rchl** [comment]
For the record, vscode implements this through an optional `javascript.suggest.completeFunctionCalls` / `typescript.suggest.completeFunctionCalls` setting. This likely has an issue with signature help not being triggered when using it so that's probably why it is disabled by default.

**Comment by sf8193** [comment]
is there anything i need to do to enable this? doesn't seem to be working for me @rchl

**Comment by rchl** [comment]
There is a setting for it that is by default disabled: https://github.com/typescript-language-server/typescript-language-server/blob/c07426adc8b079273c267e18d11993d53d482886/README.md?plain=1#L303-L312
