### ISSUE TITLE
Neovim errors potientally due to pnpm monorepo?

### ISSUE THREAD

**Issue by creepinson** [typescript-language-server/typescript-language-server#205]
I just installed this with nvim-lspconfig, however it gives relative import and cannnot find name errors. In vscode it works fine. I have a multi project workspace using pnpm which I believe symlinks dependencies. 

**Neovim:**
![image](https://user-images.githubusercontent.com/11761863/116334979-f7398700-a78a-11eb-96a4-453fceeed339.png)

**VSCode:**
![image](https://user-images.githubusercontent.com/11761863/116335042-0b7d8400-a78b-11eb-9d59-a48646981701.png)

~~I am editing within the subfolder packages/client in the monorepo - maybe if I run `nvim packages/client/src/api.ts` instead of cding into packages/client it'll work.~~ nope.

It also builds fine, so it definitely shouldn't be giving these errors.

Thanks,
Theo.

**Comment by DonnieWest** [comment]
Looks like #195 might fix this

**Comment by creepinson** [comment]
Sorry for the bump, but is the PR going to be merged soon? I can't seem to get *any* of my ts projects working in nvim, and there doesn't seem to be a good alternative that I can find.

**Comment by creepinson** [comment]
Any updates on this? Is this repository even active?

**Comment by DonnieWest** [comment]
I don't personally use pnpm, but looks like someone is contributing #195 that should fix this

Please don't spam the repository asking for updates. All the work is done in the open and is available for you to see. The best way to ensure things work is to contribute an appropriate fix

**Comment by rchl** [comment]
I will assume that it works now since the referenced PR is merged and released.
