### ISSUE TITLE
Method ‘textDocument/references’ does not respect includeDeclarations option

### ISSUE THREAD

**Issue by WilcoKruijer** [typescript-language-server/typescript-language-server#206]
‘textDocument/references’ does not check for the `includeDeclaration` boolean on the `ReferenceParams` object and thus incorrectly returns the declaration of the current symbol when this property is set to false.

[Protocol definition](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_references)

**Comment by rchl** [comment]
The fact that the spec has property for it doesn't mean that the server needs to support it.

I'm not sure if Typescript actually supports it. Do you know any more than me or just basing your issue on the LSP spec?

**Comment by WilcoKruijer** [comment]
Not sure if I agree with your assessment. The `includeDeclaration` argument has always been a part of `ReferenceParams` in the protocol, therefore it is (kind of) expected for servers to implement this argument when the references request is implemented. I was mislead by the fact that this parameter was present but not adhered to when implementing a language client. That's the reason I decided to file an issue. Feel free to close this issue if you do not agree. Thanks for responding!

Not sure if `tsserver` supports this.

**Comment by rmagatti** [comment]
I believe this to be the culprit of https://github.com/rmagatti/goto-preview/issues/50

Or at least related. 
This is the code I'm using to get the references in Neovim if that's of any help.
```
M.lsp_request_references = function(opts)
  local params = vim.lsp.util.make_position_params()
  local lsp_call = "textDocument/references"
  local success, _ = pcall(vim.lsp.buf_request, 0, lsp_call, params, lib.get_handler(lsp_call, opts))
  if not success then
    print_lsp_error(lsp_call)
  end
end
```

I am then getting this error.
```
"Request textDocument/references failed with message: Cannot read property 'includeDeclaration' of undefined"
```

Which I imagine might be coming from this line.
https://github.com/typescript-language-server/typescript-language-server/commit/5b1d9fb596071eda11410e718df680742b408dc8#diff-2a5096ffdb93efd5ef847c28e268f1e1e824fa2894ecd611c1a1f1164c4f4c63R598

Not sure exactly what to make of this yet, any help would be appreciated :)

**Comment by rmagatti** [comment]
Yeah, so changing the code to this, as expected, makes things work again.
```
return result.body.refs
  .filter(
      (fileSpan) =>
      params.context?.includeDeclaration || !fileSpan.isDefinition
      )
  .map((fileSpan) => toLocation(fileSpan, this.documents));
```

**Comment by rchl** [comment]
According to TypeScript's type definitions the `context` should be always defined but we can add such fix anyway.

What version of TypeScript have you been testing this with?

**Comment by rchl** [comment]
Actually that one comes from the client so it's a bug in your editor. The context object should be always provided.

**Comment by rmagatti** [comment]
Ah I see what you mean by it being the client. Neovim's builtin client actually adds the `context.includeDeclaration = true` in its call, I'm doing the raw call myself, bypassing what the builtin client does by default, hence the issue.

Ref:
https://github.com/neovim/neovim/blob/1f3c0593eb1d4e54ce1edf35da67d184807a9280/runtime/lua/vim/lsp/buf.lua#L314

Fixed in https://github.com/rmagatti/goto-preview/pull/51

That said, other language servers like the lua one wasn't breaking on this call.
Maybe it's worth adding an optional check either way? But I'll leave that decision to you ofc.

Thanks for the help.

**Comment by rchl** [comment]
I'll go with not changing anything since the server is following the spec now. If the server would have to handle all possible permutations of inputs, even invalid ones, the code would probably be 50% bigger. :)

**Comment by rmagatti** [comment]
Of course. Fair enough. 👍
