### ISSUE TITLE
Incorrect attribute completion suggestion with discriminating union type

### ISSUE THREAD

**Issue by jgburet** [typescript-language-server/typescript-language-server#208]
I'm using SublimeText4.
This does not happen on ST3 with the "typescript" package (meaning, non-LSP).

Two problems here
- `"o:{organizationId}"` is already present on lign 114;
- the `$customizer` attribute is suggested but it doesn't match the type used with the previous attribute.

The suggestion:
<img width="738" alt="Screenshot 2021-04-29 at 14 08 36" src="https://user-images.githubusercontent.com/1304987/116551193-f40fd980-a8f7-11eb-8a3f-9d120ef3769b.png">

The corresponding type:
<img width="1122" alt="Screenshot 2021-04-29 at 14 09 21" src="https://user-images.githubusercontent.com/1304987/116551194-f4a87000-a8f7-11eb-9e8c-25b3105ea36c.png">

Example of where `$customizer` should be accepted
<img width="1122" alt="Screenshot 2021-04-29 at 14 12 35" src="https://user-images.githubusercontent.com/1304987/116551196-f4a87000-a8f7-11eb-87b4-f1c6467fcdf2.png">

https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions

**Comment by rchl** [comment]
It's hard to figure out the issue just from the screenshot. It would help if you would provide some sample code.

**Comment by rchl** [comment]
Closing due to no response/reproduction.

If it works the same in VSCode then I would assume it's typescript behavior and you could try submitting an issue in the Typescript repo instead.
