### ISSUE TITLE
Multiple import options on auto-import

### ISSUE THREAD

**Issue by Pablo1107** [typescript-language-server/typescript-language-server#210]
When doing auto-import on some symbol, it only presents one import options when there are several available.

Is there a way that this can be enhanced here?

FYI, I've been using this with nvim native lsp.

**Comment by rchl** [comment]
I'm not sure what this is about exactly? Do you have any specific examples?

There were some improvements in this area lately. For example we are now providing info from which module the auto-import will be performed so it's possible to distinguish between multiple identical symbols. Was that the issue?

**Comment by rchl** [comment]
Will mark this as a duplicated of #235.

#318 implements something that should help but not sure if the flow will match what you are describing.

**Comment by Pablo1107** [comment]
The workflow that I described originally was what I previously had using coc-tsserver in which when you type a missing symbol it allowed you to import from several sources (same as with code action) if the symbol is exported with the same name of several files.

For example:


```typescript
// file1.ts
export const symbol = () => {}
```

```typescript
// file2.ts
export const symbol = () => {}
```

```typescript
symb| // auto-complete showed just symbol from file1.ts to complete and import but no file2.ts
```

Idk if this was added in the meantime.

**Comment by rchl** [comment]
That seems to work in the current version already:

<img width="795" alt="Screenshot 2021-12-04 at 10 57 02" src="https://user-images.githubusercontent.com/153197/144705339-2783a7b6-e9e2-4a1d-b8c3-0c0a61320d46.png">
