### ISSUE TITLE
Support for auto-import all

### ISSUE THREAD

**Issue by yassinebridi** [typescript-language-server/typescript-language-server#235]
I just moved away from coc-tsserver, and I really miss the auto-import all functionality.
I was wondering if this is something that can be included in this server.

**Comment by rchl** [comment]
Maybe. How does it work in `coc-tsserver` exactly?

**Comment by yassinebridi** [comment]
I'm not sure if you asking me how it works internally, but here is a gif of it working.

![Peek 2021-07-13 23-33](https://user-images.githubusercontent.com/18403595/125533783-e6f5965c-a397-49f4-9440-d5bd8dc5145b.gif)

**Comment by rchl** [comment]
According to https://github.com/neoclide/coc-tsserver/issues/201 this feature comes from ts-server so we shouldn't need to implement anything. Though it also says that this only works in TS projects, not JS.

Though I'm not really getting that code action locally in one project I've tried so not sure what's up.

**Comment by rchl** [comment]
I've traced ts-server a bit and there actually is something that the server needs to handle to enable this.

**Comment by williamboman** [comment]
I'm struggling a bit with the inverse of this - deleting all unused imports. It seems like the code action request only ever receives the code action to remove a single import. I can't seem to get it to provide the "Delete all unused import" code action. I've stepped through the code in a debugger but can't make much sense of what's going on tbh.. Any pointers?

**Comment by yassinebridi** [comment]
@williamboman This is something the coc does too. The organise import  command organises the imports and remove any unused commands.

**Comment by rchl** [comment]
Implementing the support for that in #318.

Based on the earlier gif here, I don't think it will work exactly how it works in COC.

Those extra actions will be exposed as "Source actions" (typically exposed by the editor through a dedicated sub-menu) and also will be usable with Code-Actions-On-Save functionality, if editor supports that.

**Comment by kamalkech** [comment]
@yassinebridi  the shortcut ?

**Comment by yassinebridi** [comment]
You should add this in your config
```
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')
```
you will have the `:OR` command, that you can map.

**Comment by kamalkech** [comment]
@yassinebridi i am not using coc, ofc i already install typescript-language-server but when i try to import cannot see import all !!
