### ISSUE TITLE
Imported modules autocomplete not working

### ISSUE THREAD

**Issue by flosker** [typescript-language-server/typescript-language-server#250]
I am using Neovim with [nvim-compe](https://github.com/hrsh7th/nvim-compe) & typescript-language-server. Auto completion for imported module's properties works in JS files, but not in TS.

### To reproduce
Install `union` from npm. Create test.js & test2.ts files with following content.

```
import uni from 'union'
```

And try to autocomplete, `uni`. You should get results like this - [Screenshot](https://imgur.com/a/ezjpz0P). But I a not getting them. in `.ts`.

**Comment by rchl** [comment]
In Typescript the types need to be explicitly defined and this package doesn't ship with types nor the types are available at `@types/union`.

In Javascript the types are automatically inferred from exports so it works better in this case.

The closest thing talking about the JS and TS differences I could find is at https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html
