### ISSUE TITLE
Completion not working properly with pnpm

### ISSUE THREAD

**Issue by itmecho** [typescript-language-server/typescript-language-server#254]
I'm using `pnpm` along with `next` and `mantine`. For some reason, the autocompletion in both `neovim` and `code` doesn't work for the `mantine` types. 

You can replicate this by cloning https://github.com/mantinedev/mantine-next-template and running `pnpm install`. Then open the project in `code` and try adding a const somewhere valid like `const x = <Center`. This should trigger the autocompletion for the Center component from mantine but I get nothing.

If I do `rm -Rf node_modules && npm install`, then do the same as above, it works. I'm guessing it's something to do with the symlinking that `pnpm` does?

Discussion on the `mantine` repo: https://github.com/mantinedev/mantine/discussions/224

**Comment by rchl** [comment]
VSCode doesn't use this server so if you also have issues with it, it's possibly a deeper issue in tserver (typescript) itself.

**Comment by itmecho** [comment]
Thanks @rchl! I've opened a discussion on the `pnpm` repo to see if anyone there can help.

Everything compiles fine and once I've manually imported a component, I don't get any errors.

**Comment by rchl** [comment]
Any updates on the investigation?

**Comment by Luiz-Monad** [comment]
I stumbled upon this problem, which I misidentified as being a problem with Zip archives. I mentioned it here. 
https://github.com/microsoft/vscode/issues/75559

Please notice this problem looked like it was coming from the Yarn2 or the Zip feature, but I actually found the source to be the TServer.
