### ISSUE TITLE
Question: how the LS knows about the global dependencies installed on the machine?

### ISSUE THREAD

**Issue by bushev** [typescript-language-server/typescript-language-server#260]
Hey,

I have a quick question. I'm trying to use the LS but how I can configure it to resolve global dependencies?

**Comment by rchl** [comment]
That sounds like a bad idea but also maybe not related to this LS but to Node.js rather.

Are you able to import global dependencies from a *.js file? I believe you can't so you shouldn't expect LS server to be able either.

Or maybe you have a use case that works and makes sense then please explain more.

**Comment by bushev** [comment]
Hey @rchl,

I'm building a mobile IDE, pretty custom and I use about 10 different LS for the different languages.

At this moment, I'm trying to understand for to use this LS in a real life. When there are global dependencies on the machine or local dependencies in the node_modules folder.

When I use `didOpen` and `didChange` events to get LS to know about a single project file `index.ts` for example, how it can be synced with the `node_modules` folder?

**Comment by rchl** [comment]
TS is resolving the imports more or less the same way as Node does so this explanation is probably relevant: https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders.

There is also some info about how it resolves dependencies from global locations: https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders

**Comment by bushev** [comment]
Do you mean that LS will look for files that I use in a `require` statement by reading `node_modules` directories?

**Comment by rchl** [comment]
`require` or `import`, doesn't matter.

It will try to resolve that import by running its algorithm for resolving modules. That includes looking within the `node_modules` directory. It's described in the links above.

**Comment by bushev** [comment]
Okay, that makes sense. Thank you for explaining this!
