### ISSUE TITLE
Error handling, when tsserver cannot be found

### ISSUE THREAD

**Issue by svenefftinge** [typescript-language-server/typescript-language-server#28]
Since we no longer ship typescript with this npm package, there are scenarios in which no `tsserver`can be found. We need to send a message to the user, telling her what to do.

The corresponding exception https://github.com/theia-ide/typescript-language-server/blob/master/src/lsp-server.ts#L85

**Comment by rchl** [comment]
With #292 we'll fail the `initialize` request with an `Could not find a valid tsserver version. Exiting.` error if we can't resolve `typescript`.
