### ISSUE TITLE
possible to honor `importModuleSpecifierEnding` in responses to `textDocument/completion`?

### ISSUE THREAD

**Issue by orzechowskid** [typescript-language-server/typescript-language-server#282]
I'm working with a Javascript project where all files are ES modules and need to be imported using the full filename with extension.  I've configured my LSP client to send an `initialize` message to typescript-language-server containing the `initializationOptions.preferences.importModuleSpecifierEnding` property with a value of `"js"`.

file extensions are present in imports automatically added for me.  I can type `foo` into my IDE, select the completion item labeled "foobar", and see `import { foobar } from './blah/foobar.js';` added to the top of my source file.  so far so good.

file extensions are not present in responses to `textDocument/completion` requests when I attempt to manually add an import.  I can type `import { } from './blah/` into my IDE, select the completion item labeled "foobar", and see `foobar` appended to my source file at the cursor's current location.  I would have expected to see "foobar.js" here as well, but nothing in the responses to `textDocument/completion` or `completionItem/resolve` contains that string so I think the server isn't even sending it:

```
[Trace - 01:48:45 PM] Sending request 'textDocument/completion - (35)'.
Params: {
  "textDocument": {
    "uri": "file:///home/dan/test/src/index.js"
  },
  "position": {
    "line": 6,
    "character": 18
  },
  "context": {
    "triggerKind": 1
  }
}


[Trace - 01:48:45 PM] Received response 'textDocument/completion - (35)' in 34ms.
Result: {
  "isIncomplete": null,
  "items": [
    {
      "data": {
        "entryNames": [
          "foobar"
        ],
        "offset": 19,
        "line": 7,
        "file": "/home/dan/test/src/index.js"
      },
      "sortText": "11",
      "kind": 17,
      "label": "foobar"
    }
  ]
}

[Trace - 01:48:47 PM] Sending request 'completionItem/resolve - (36)'.
Params: {
  "_emacsStartPoint": 109,
  "data": {
    "entryNames": [
      "foobar"
    ],
    "offset": 19,
    "line": 7,
    "file": "/home/dan/test/src/index.js"
  },
  "sortText": "11",
  "kind": 17,
  "label": "foobar"
}

[Trace - 01:48:47 PM] Received response 'completionItem/resolve - (36)' in 69ms.
Result: {
  "detail": "foobar",
  "_emacsStartPoint": 109,
  "data": {
    "entryNames": [
      "foobar"
    ],
    "offset": 19,
    "line": 7,
    "file": "/home/dan/test/src/index.js"
  },
  "sortText": "11",
  "kind": 17,
  "label": "foobar"
}
```

it looks like the completion item is of type 17, which according to the spec is a file.  given the configuration present in the initialization message, I would have expected a file extension to be present here.

is there a way to tell the LSP server to append file extensions in the latter case?

thank you!

**Comment by rchl** [comment]
I must say that I can't quite see this issue when I try on the `test_data` directory in this repo:

<img width="714" alt="Screenshot 2021-11-07 at 20 37 30" src="https://user-images.githubusercontent.com/153197/140659344-408b2781-d79b-40c1-89e3-c42a0033ace0.png">

It completes to:

<img width="255" alt="Screenshot 2021-11-07 at 20 37 42" src="https://user-images.githubusercontent.com/153197/140659354-0521ff1a-ea26-4bc1-880a-c93a14e47ea0.png">

This is with `importModuleSpecifierEnding` set to `js` of course.

Can you check which version of `typescript` is used in that project. Here it's 4.4.

I will also point out that https://github.com/typescript-language-server/typescript-language-server/pull/281 has some improvements around that area but for me it works without that change even.

**Comment by orzechowskid** [comment]
hm, you're right.  I see the same behavior as you do when I clone this repository and point my IDE at it.  I then compared this project with my original project, and realized that I had a `paths` entry in my own tsconfig.json:

```
"paths": {
  "~/*" : [ "./public/*" ]
}
```

manually writing an import statement with the path prefix does not result in the file extension being provided:
`import * from '~/utils/foo` -> `import * from '~/utils/foobar'`

manually writing an import statement without the path prefix does result in the file extension being provided:
`import * from '../../utils/foo` -> `import * from '../../utils/foobar.js`

I'm using Typescript 4.4.4 and typescript-language-server 0.6.5 .

**Comment by rchl** [comment]
I'd suggest reporting it in https://github.com/microsoft/TypeScript repo since it also reproduces with VSCode (with `"javascript.preferences.importModuleSpecifierEnding": "js"` set).

Best to talk in context of VSCode there since it's their product and it's what they care the most about.

**Comment by rchl** [comment]
Will mark this as upstream issue and resolve. Feel free to post a link to the issue if you get to reporting it.

**Comment by orzechowskid** [comment]
got it, thanks for your help!
