### ISSUE TITLE
tsserver process dying is not handled

### ISSUE THREAD

**Issue by masad-frost** [typescript-language-server/typescript-language-server#302]
Sometimes the `tsserver` process dies (OOM or other reasons), when that happens the parent process is essentially useless. 

Happy to contribute here, but would love some advice on how you think we should proceed when the process dies. Some options:
1. Kill the `typescript-language-server` process, probably the easiest option, let the user handle restarting
2. Respawn `tsserver` process internally inside `TspClient`, reconfigure `tsserver` (need to cache initial configuration and compiler options), and then resend pending requests.
3. Create a new instance of `TspClient` inside `LspClient`, ditto above

**Comment by masad-frost** [comment]
I'm not sure how stateful is `tsserver` and if it's even makes sense to respawn

**Comment by rchl** [comment]
I don't think it makes sense to restart, there is too much state. We could trigger a "message box" (`window/showMessage`) on the client when that happens. The question is how do you detect it crashing?

**Comment by masad-frost** [comment]
We can listen on the process's [`exit` event](https://nodejs.org/api/child_process.html#event-exit), no?

**Comment by masad-frost** [comment]
I'm not sure if a `showMessage` is enough, that would mean clients (or possibly worse the user of the client) would have to handle that message. Most client implementations I've seen (namely vscode and neovim) restart the language server if it crashes (they also handle crash loops).

**Comment by rchl** [comment]
But you are talking about the server itself crashing and restarting, not the subprocesses of the server.

As I said, restarting the `tsserver` subprocess doesn't seem viable as there is too much state. Restarting the server itself would work because then the client will ensure that all files are re-opened (didOpen fired) and state is correct.

**Comment by rchl** [comment]
So the solution could be to just crash the main server process on purpose when that happens. The client would take care of restarting and handling crash loop.

**Comment by masad-frost** [comment]
Yes crashing the main process is what I was referring to in the first option. I can send a PR over the weekend.

**Comment by rchl** [comment]
Created a fix in #305
