### ISSUE TITLE
`typescript` version is no longer resolved above the `rootUri`

### ISSUE THREAD

**Issue by tapayne88** [typescript-language-server/typescript-language-server#313]
Thanks for the work maintain this project!

Prior to #292 it looks like ts-ls would resolve the version of `typescript` following node module resolution (up the folder structure). This is useful if you're in workspaces that has `root_dir` like folders but the `typescript` module is installed higher in the tree, something like this

```console
├── index.ts
├── node_modules
│   └── typescript
├── package.json
├── packages
│   └── some_app
│       ├── package.json
│       ├── tsconfig.json
│       └── index.ts        <--- open this file
└── tsconfig.json
```

This setup can be common in yarn / npm workspace setups.

We could reimplement something like the `findPathToYarnSdk` at the point we look for the various typescript module options (`getWorkspaceVersion`).
https://github.com/typescript-language-server/typescript-language-server/blob/42bf57a5af9672275437fa77ef0d4fcd94084d16/src/modules-resolver.ts#L18-L30
https://github.com/typescript-language-server/typescript-language-server/blob/51f64ed1a74bb90fd24837a383826601ff8c1ddb/src/utils/versionProvider.ts#L136-L149

What do you think? I'd be happy to look at picking this up

**Comment by rchl** [comment]
Are you talking about the case when single file is opened (without the workspace folder)?

When workspace folder is opened then we are looking for the typescript package in the root workspace folder which I think makes sense.

**Comment by tapayne88** [comment]
I suppose in the default neovim setup `some_app` would be considered a workspace as it has a `tsconfig.json` (and/or `package.json`), it just doesn't have the `typescript` module available within it due to it being a member of a yarn workspace.

https://github.com/neovim/nvim-lspconfig/blob/8b0176da95494f245f7cd7d630bc63303031ce8a/lua/lspconfig/tsserver.lua#L22-L25

**Comment by rchl** [comment]
I see.

Looking up typescript any number of levels up the workspace folder sounds kinda wrong to me but that is indeed how it worked before.

I guess we should restore that functionality.

**Comment by tapayne88** [comment]
Yeah, javascript projects have very loose definitions of where things should live, runtime resolution is a nightmare! It makes the lives of tools like these (and the people who look after them) very tricky!
