### ISSUE TITLE
[Bug][Case Study] Completion not working properly on Virtual File systems.

### ISSUE THREAD

**Issue by Luiz-Monad** [typescript-language-server/typescript-language-server#319]
Case study: https://github.com/yarnpkg/berry/issues/962
Being able to use "go to definition" on files on projects that uses "Yarn2" or any other virtualized file system. (like https://github.com/typescript-language-server/typescript-language-server/issues/254)

Possible duplicate https://github.com/typescript-language-server/typescript-language-server/issues/254

Steps to test
```
git clone https://github.com/Luiz-Monad/react-native-tizen-dotnet
cd Devtools/react-native-tizen-dotnet
rm -recurse -force (join-path (gci env:APPDATA).value '../local/microsoft/typescript/')
rm ./.pnp.cjs
rm ./.yarnclean
rm ./.yarnrc.yml
rm ./.yarn/ -Recurse -Force
yarn set version berry
yarn add typescript
yarn dlx @yarnpkg/sdks vscode
```
If you do this, then "go to definition will work", but it seems to be using the Internal Typescript language services from Vscode.
https://github.com/microsoft/vscode/tree/4fcbe9449c57ff1e65f134dde6df58cb28bcea5f/extensions/typescript-language-features

Now lets try using the actual Typescript Language Server.
```

@'
{
  "include": [
    "*.config.js",
    "./src/**/*.js"
  ],
  "compilerOptions": {
    "target": "es2016",  
    "module": "commonjs",
    "allowJs": true,    
    "outDir": "./dist", 
    "esModuleInterop": true
  }
}
'@ | out-file tsconfig.json

```

What was supposed to happen "go to definition works"
What happens instead:
![image](https://user-images.githubusercontent.com/4574729/144712052-66143d64-05b5-418b-909c-4be8c44a1035.png)

Logs I collected while trying to reproduce the problem.
 (which I mistakenly thought was caused by the ZipFile provider, it appeared as the cache wasn't being populated )

[20211203T232329 - works.zip](https://github.com/microsoft/vscode/files/7653384/20211203T232329.-.works.zip)
[20211203T232402 - dont work.zip](https://github.com/microsoft/vscode/files/7653385/20211203T232402.-.dont.work.zip)

Related issues:
https://github.com/microsoft/vscode/issues/98830
https://github.com/microsoft/vscode/issues/59650
https://github.com/microsoft/vscode/issues/75559

**Comment by rchl** [comment]
Which client/editor are you testing this with? This not only needs to be supported by the server but also by the client/editor.

With yarn you need some special steps. It was discussed in https://github.com/typescript-language-server/typescript-language-server/pull/220

But the editor also needs to support non-file paths. As for VSCode, I'm not sure if it has support for that out-of-the-box for any language server and whether you need to declare something in the servers' package.json. The internal typescript-language-services are not using LSP so have support baked-in internally and not sure how relevant that is to actual language servers.

**Comment by rchl** [comment]
In any case, sorry for all over the place response but I believe the situation is like so:
 - yarn does some tsserver wrapping and translates `file:` paths to virtualized ones but the behavior depends on editor name passed through the `hostInfo` object.
 - as long as editor supports those non-file paths, it should work but I'm not sure how well as I haven't tried it
 - I believe server doesn't need to support anything

**Comment by Luiz-Monad** [comment]
```
[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.62.3 (system setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z (2 wks ago)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

[OK] [Copy]

λ yarn --version
1.22.5
```

No problem, I'm tracking this specific bug all over the place.

**Comment by Luiz-Monad** [comment]
"The internal typescript-language-services are not using LSP  so have support baked-in internally and not sure how relevant that is for the actual language servers."
Yes, it works, but as soon as I add a "tsconfig.json" file, it switches to using the this language server, if I understood the logs correctly.
I also noticed that the `yarn2` adds some small piece of code before loading the `tsserver`

<details>
<summary>sdks/typescript/lib/tsserver.js</summary>
<p>

```javascript
#!/usr/bin/env node

const {existsSync} = require(`fs`);
const {createRequire, createRequireFromPath} = require(`module`);
const {resolve} = require(`path`);

const relPnpApiPath = "../../../../.pnp.cjs";

const absPnpApiPath = resolve(__dirname, relPnpApiPath);
const absRequire = (createRequire || createRequireFromPath)(absPnpApiPath);

const moduleWrapper = tsserver => {
  if (!process.versions.pnp) {
    return tsserver;
  }

  const {isAbsolute} = require(`path`);
  const pnpApi = require(`pnpapi`);

  const isVirtual = str => str.match(/\/(\$\$virtual|__virtual__)\//);
  const normalize = str => str.replace(/\\/g, `/`).replace(/^\/?/, `/`);

  const dependencyTreeRoots = new Set(pnpApi.getDependencyTreeRoots().map(locator => {
    return `${locator.name}@${locator.reference}`;
  }));

  // VSCode sends the zip paths to TS using the "zip://" prefix, that TS
  // doesn't understand. This layer makes sure to remove the protocol
  // before forwarding it to TS, and to add it back on all returned paths.

  function toEditorPath(str) {
    // We add the `zip:` prefix to both `.zip/` paths and virtual paths
    if (isAbsolute(str) && !str.match(/^\^?(zip:|\/zip\/)/) && (str.match(/\.zip\//) || isVirtual(str))) {
      // We also take the opportunity to turn virtual paths into physical ones;
      // this makes it much easier to work with workspaces that list peer
      // dependencies, since otherwise Ctrl+Click would bring us to the virtual
      // file instances instead of the real ones.
      //
      // We only do this to modules owned by the the dependency tree roots.
      // This avoids breaking the resolution when jumping inside a vendor
      // with peer dep (otherwise jumping into react-dom would show resolution
      // errors on react).
      //
      const resolved = isVirtual(str) ? pnpApi.resolveVirtual(str) : str;
      if (resolved) {
        const locator = pnpApi.findPackageLocator(resolved);
        if (locator && dependencyTreeRoots.has(`${locator.name}@${locator.reference}`)) {
          str = resolved;
        }
      }

      str = normalize(str);

      if (str.match(/\.zip\//)) {
        switch (hostInfo) {
          // Absolute VSCode `Uri.fsPath`s need to start with a slash.
          // VSCode only adds it automatically for supported schemes,
          // so we have to do it manually for the `zip` scheme.
          // The path needs to start with a caret otherwise VSCode doesn't handle the protocol
          //
          // Ref: https://github.com/microsoft/vscode/issues/105014#issuecomment-686760910
          //
          // Update Oct 8 2021: VSCode changed their format in 1.61.
          // Before | ^zip:/c:/foo/bar.zip/package.json
          // After  | ^/zip//c:/foo/bar.zip/package.json
          //
          case `vscode <1.61`: {
            str = `^zip:${str}`;
          } break;

          case `vscode`: {
            str = `^/zip/${str}`;
          } break;

          // To make "go to definition" work,
          // We have to resolve the actual file system path from virtual path
          // and convert scheme to supported by [vim-rzip](https://github.com/lbrayner/vim-rzip)
          case `coc-nvim`: {
            str = normalize(resolved).replace(/\.zip\//, `.zip::`);
            str = resolve(`zipfile:${str}`);
          } break;

          // Support neovim native LSP and [typescript-language-server](https://github.com/theia-ide/typescript-language-server)
          // We have to resolve the actual file system path from virtual path,
          // everything else is up to neovim
          case `neovim`: {
            str = normalize(resolved).replace(/\.zip\//, `.zip::`);
            str = `zipfile:${str}`;
          } break;

          default: {
            str = `zip:${str}`;
          } break;
        }
      }
    }

    return str;
  }

  function fromEditorPath(str) {
    switch (hostInfo) {
      case `coc-nvim`:
      case `neovim`: {
        str = str.replace(/\.zip::/, `.zip/`);
        // The path for coc-nvim is in format of /<pwd>/zipfile:/<pwd>/.yarn/...
        // So in order to convert it back, we use .* to match all the thing
        // before `zipfile:`
        return process.platform === `win32`
          ? str.replace(/^.*zipfile:\//, ``)
          : str.replace(/^.*zipfile:/, ``);
      } break;

      case `vscode`:
      default: {
        return process.platform === `win32`
          ? str.replace(/^\^?(zip:|\/zip)\/+/, ``)
          : str.replace(/^\^?(zip:|\/zip)\/+/, `/`);
      } break;
    }
  }

  // Force enable 'allowLocalPluginLoads'
  // TypeScript tries to resolve plugins using a path relative to itself
  // which doesn't work when using the global cache
  // https://github.com/microsoft/TypeScript/blob/1b57a0395e0bff191581c9606aab92832001de62/src/server/project.ts#L2238
  // VSCode doesn't want to enable 'allowLocalPluginLoads' due to security concerns but
  // TypeScript already does local loads and if this code is running the user trusts the workspace
  // https://github.com/microsoft/vscode/issues/45856
  const ConfiguredProject = tsserver.server.ConfiguredProject;
  const {enablePluginsWithOptions: originalEnablePluginsWithOptions} = ConfiguredProject.prototype;
  ConfiguredProject.prototype.enablePluginsWithOptions = function() {
    this.projectService.allowLocalPluginLoads = true;
    return originalEnablePluginsWithOptions.apply(this, arguments);
  };

  // And here is the point where we hijack the VSCode <-> TS communications
  // by adding ourselves in the middle. We locate everything that looks
  // like an absolute path of ours and normalize it.

  const Session = tsserver.server.Session;
  const {onMessage: originalOnMessage, send: originalSend} = Session.prototype;
  let hostInfo = `unknown`;

  Object.assign(Session.prototype, {
    onMessage(/** @type {string} */ message) {
      const parsedMessage = JSON.parse(message)

      if (
        parsedMessage != null &&
        typeof parsedMessage === `object` &&
        parsedMessage.arguments &&
        typeof parsedMessage.arguments.hostInfo === `string`
      ) {
        hostInfo = parsedMessage.arguments.hostInfo;
        if (hostInfo === `vscode` && process.env.VSCODE_IPC_HOOK && process.env.VSCODE_IPC_HOOK.match(/Code\/1\.([1-5][0-9]|60)\./)) {
          hostInfo += ` <1.61`;
        }
      }

      return originalOnMessage.call(this, JSON.stringify(parsedMessage, (key, value) => {
        return typeof value === `string` ? fromEditorPath(value) : value;
      }));
    },

    send(/** @type {any} */ msg) {
      return originalSend.call(this, JSON.parse(JSON.stringify(msg, (key, value) => {
        return typeof value === `string` ? toEditorPath(value) : value;
      })));
    }
  });

  return tsserver;
};

if (existsSync(absPnpApiPath)) {
  if (!process.versions.pnp) {
    // Setup the environment to be able to require typescript/lib/tsserver.js
    require(absPnpApiPath).setup();
  }
}

// Defer to the real typescript/lib/tsserver.js your application uses
module.exports = moduleWrapper(absRequire(`typescript/lib/tsserver.js`));

```
</p>
</details>

I have no idea what's wrong.

**Comment by rchl** [comment]
> Yes, it works, but as soon as I add a "tsconfig.json" file, it switches to using the this language server, if I understood the logs correctly.

VSCode doesn't include any of this server's code. So unless you somehow added it manually (I'm not aware of any existing VSCode extensions for it), this code should never be used in VSCode.

**Comment by Luiz-Monad** [comment]
No, that code is included by `Yarn berry` and is on my project, 
here https://github.com/Luiz-Monad/react-native-tizen-dotnet/tree/master/Devtools/react-native-tizen-dotnet/.yarn/sdks/typescript/lib

Perhaps that integration is doing something wrong, and I should file the bug there.

**Comment by rchl** [comment]
What you've pointed to is just a thin layer that acts as a proxy to the actual `typescript` package. So still not really related to this server. This servers is using `typescript` also and it would also go through that `yarn` SDK proxy if using this server but I'm pretty sure that this server is not used when using VSCode.

**Comment by Luiz-Monad** [comment]
Oh, you're right, my bad, both files were called `tsserver.js` in my logs, I got confused.

And that Yarn code is very sneaky, I didn't knew. https://github.com/elmpp/berry/blob/7b414b3afd1f6274b5e0294277d2dcf80a17b251/packages/yarnpkg-pnpify/sources/generateSdk.ts#L194

**Comment by Luiz-Monad** [comment]
I think I should open an issue here, I didn't knew it hads an internal extension. 
https://github.com/microsoft/vscode/tree/main/extensions/typescript-language-features/src/tsServer

Arcanis could have helped me, instead of saying "Please don't make Yarn support requests on the VSCode tracker".
He knows its a problem with that hack, I didn't knew about it, I don't know how this works.
https://github.com/microsoft/vscode/issues/75559#issuecomment-986005785

Sorry about the inconvenience.
