### ISSUE TITLE
npm install in the windows title

### ISSUE THREAD

**Issue by bryant-the-coder** [typescript-language-server/typescript-language-server#325]
![image](https://user-images.githubusercontent.com/92417638/145041986-f8322157-3099-4fbe-a688-44da684bd707.png)
is this even normal? i am using lsp neovim and when i type no snippets is provided... Pls help

**Comment by rchl** [comment]
Sorry but this doesn't seem to be related to this server. Maybe try searching for help within the community using the same text editor.

**Comment by RitschAlex** [comment]
I get the exact same message when tsserver gets triggered. However, it seems like that this problem does not affect the functionality of tsserver.

@bryant-the-coder were you able to find a solution for this?

**Comment by bryant-the-coder** [comment]
No
