### ISSUE TITLE
Unclear how to resolve "Could not find a valid tsserver version. Exiting." error

### ISSUE THREAD

**Issue by axelson** [typescript-language-server/typescript-language-server#336]
When the user receives this error on initialize `Could not find a valid tsserver version. Exiting.` it is not clear what needs to be done to resolve the issue. They may not have any idea what "tsserver" is (and may be confused into thinking that tsserver is typescript language server). Judging from https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29 this can usually be resolved by `npm install -g typescript`.

**Comment by xav-ie** [comment]
I had this issue and thankfully landed here! :). Thanks for the tip.

**Comment by texaco** [comment]
oh lord... sooo many hours!

Thanks!!
