### ISSUE TITLE
Support willSaveWaitUntil to allow format on save

### ISSUE THREAD

**Issue by simark** [typescript-language-server/typescript-language-server#34]
I started to add some glue code here:

https://github.com/simark/typescript-language-server/tree/will-save-wait-until-attempt

But I'm currently blocked on https://github.com/theia-ide/theia/issues/1710.

**Comment by simark** [comment]
LSP reference: https://microsoft.github.io/language-server-protocol/specification#textDocument_willSaveWaitUntil

**Comment by rchl** [comment]
You are mentioning format on save but this server doesn't really support formatting.

Unless you mean organizing imports, which is something it supports, but I'm not sure it belongs in within that functionality.

Many editors support Code Actions On Save which would make more sense for running "Organize Imports" on save.
