### ISSUE TITLE
Feature Request: Jsx attribute completion snippet

### ISSUE THREAD

**Issue by TrietMinh799** [typescript-language-server/typescript-language-server#359]
In vscode, if you use typescript 4.5 in your project, you will have the ability to do in react like this
![jsx-attributes-snippets-4-5](https://user-images.githubusercontent.com/57322084/148174156-18561ab7-d8ae-4b83-9581-1ea80bb971de.gif)
you can enable it with
```json
"typescript.preferences.jsxAttributeCompletionStyle": "auto",
```
If we can do this in vscode, can we do the same thing in neovim with this language server?

**Comment by rchl** [comment]
The master branch has that option already. In the meantime you could just add `jsxAttributeCompletionStyle: "auto"` to `initializationOptions.preferences` yourself and it would work too as long as you are using 4.5 typescript.

**Comment by predragnikolic** [comment]
I think that this issue can be closed,
but I noticed one problem with `jsxAttributeCompletionStyle` and created a separate ticket for it https://github.com/typescript-language-server/typescript-language-server/issues/360
