### ISSUE TITLE
When using `jsxAttributeCompletionStyle` the completion items have the wrong insertTextFormat

### ISSUE THREAD

**Issue by predragnikolic** [typescript-language-server/typescript-language-server#360]
Given a JSX component:
```tsx
type Prop = {
  name: string
}
export function App({name}: Prop) {
  return <div className="App">
      {name}
  </div>
}
```

When requesting completion items with `jsxAttributeCompletionStyle`,
the typescript language server will return this response:

```
:: <<< LSP-typescript 601: {'items': [{'kind': 10, 'insertText': 'key={$1}', 'filterText': 'key', 'sortText': '12', 'label': 'key?', 'data': {'file': '/home/predragnikolic/Documents/sandbox/my-react-ts-app/src/index.tsx', 'entryNames': ['key'], 'line': 7, 'offset': 19}}, {'kind': 10, 'insertText': "name='$1'", 'sortText': '11', 'data': {'file': '/home/predragnikolic/Documents/sandbox/my-react-ts-app/src/index.tsx', 'entryNames': ['name'], 'line': 7, 'offset': 19}, 'label': 'name'}], 'isIncomplete': False}
```

so when we select the completion item for the `name` prop,
this will get inserted:
```
<App name='$1'| />
```
but I expect:
```
<App name='|' />
```

Note that insert is  `'insertText': "name='$1'"`,
which is a snippet, but the completion item is missing `insertTextFormat: 2` to give a note to the client that it should inset a snippet.

**Comment by TrietMinh799** [comment]
I also have this problem in neovim

**Comment by rchl** [comment]
Are you able to provide a minimal project that reproduces?

I've tried with something like this but that doesn't result in typescript sending snippet completions (only plain `name` completion).

![Screenshot 2022-01-05 at 22 18 53](https://user-images.githubusercontent.com/153197/148290911-0b29861f-68b7-4828-99bb-476e4aa11de0.png)

I'm guessing I either need to change some jsx-related option in tsconfig or create npm project and add some dependency?

**Comment by TrietMinh799** [comment]
In my case with neovim, this is the minimal project that I can reproduce
[this project](https://github.com/TrietMinh799/sample-project)

you can just enable jsxAttributeCompletionStyle to auto in your editor 

this is where I enable it in neovim

```lua
nvim_lsp.tsserver.setup {
  on_attach = on_attach,
  capabilities = capabilities,
  init_options = {
    preferences = {
      jsxAttributeCompletionStyle = "auto"
    }
  }
}
```

**Comment by rchl** [comment]
Thanks, that was helpful. Created a fix at https://github.com/typescript-language-server/typescript-language-server/pull/362
