### ISSUE TITLE
Emacs lsp-mode: The connected server(s) does not support method textDocument/definition.

### ISSUE THREAD

**Issue by ndrewtl** [typescript-language-server/typescript-language-server#369]
I believe that based on the README of this project, `textDocument/definition` is supported. I installed this program using the instructions on the [Emacs `lsp-mode` documentation](https://emacs-lsp.github.io/lsp-mode/page/lsp-typescript/), using:

```
M-x lsp-install-server RET ts-ls RET
```

The server installed successfully, and completions appear to work fine. However, the jump-to-definition feature seems broken.

Running

```
M-x lsp-find-definition
```

on a token gives this:

```
The connected server(s) does not support method textDocument/definition.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
```

Am I using the wrong command? Or could there be an issue in the interface between the Emacs client interacts with this language server?

**Comment by predragnikolic** [comment]
This server does support go to definition.

I do not use Emacs, so I cannot help you with configuring it.

It would be best to ask that question on the Emacs LSP repo, or on their discord.

**Comment by rchl** [comment]
The server also announces support for `textDocument/definition`: https://github.com/typescript-language-server/typescript-language-server/blob/c8ca9c94e684981ad21943a4fbde6befd9c7aa44/src/lsp-server.ts#L244-L244

You could try `M-x lsp-describe-session` as the message said and post that.

**Comment by ndrewtl** [comment]
Hi @rchl , I tried that command, and got a pane with a single toggle corresponding to a different project. It didn't give much information, unfortunately. I guess I'll look into the emacs lsp-mode documentation
