### ISSUE TITLE
Stdio mode: server ignores messages

### ISSUE THREAD

**Issue by prokartem** [typescript-language-server/typescript-language-server#383]
I am trying to use typescript-language-server with monaco-editor, but in stdio mode nothing happens, although seems like all works fine. Is there some problem with my understanding of LSP or something else?

I am expecting that it should behaves in a similar manner as tsserver:
![image](https://user-images.githubusercontent.com/73672965/151295632-8271f04e-c7e0-4a54-b5d4-591e63554529.png)

But in reality:
![image](https://user-images.githubusercontent.com/73672965/151295818-1aa825c9-e5fe-4e27-84b2-144389c2fa0b.png)

**Comment by rchl** [comment]
The specification how the messages should be formatted is at https://microsoft.github.io/language-server-protocol/specification#baseProtocol

The request is supposed have a `Content-Length` header and use \r\n line endings so using terminal might not be the best way to try out things.

Possibly `tsserver` is less strict with handling and responds with an error when the message is not properly formatted.
