### ISSUE TITLE
How to connect a client to a running instance of the server

### ISSUE THREAD

**Issue by kushal-ti** [typescript-language-server/typescript-language-server#410]
I'm really sorry, i know this is a very basic question but i honestly haven't been able to find what I needed and i'm very new to LSP. How can i connect a client, like a vscode-extension, to a server that was started with the `typescript-language-server --stdio` command?

**Comment by rchl** [comment]
You can't with `stdio` mode. The server would have to provide a different mode of communication to make that possible but it doesn't and there is really no plans to add other communication modes.

**Comment by kushal-ti** [comment]
Okay. So then I would have to start the server using the client? In that case it should be able to work using IPC right?

**Comment by rchl** [comment]
Yes, the client has to start the server and set up stdout/stderr channels to the server and communicate through that. So no IPC.

(This server uses https://github.com/Microsoft/vscode-languageserver-node#readme libraries and those might provide IPC support almost out of the box but I haven't investigated how hard it would be to support that)
