### ISSUE TITLE
Could not find a valid tsserver version

### ISSUE THREAD

**Issue by ghostbuster91** [typescript-language-server/typescript-language-server#411]
Hi, 

I am trying to setup neovim with typescript language support through lsp. I use nix. 
I already saw https://github.com/typescript-language-server/typescript-language-server/issues/336 and https://github.com/typescript-language-server/typescript-language-server/issues/28

I tried multiple things but whatever I do I always get the same error message:
```
RPC[Error] code_name = InternalError, message = "Request initialize failed with message: Could not find a valid tsserver version. Exiting."
```
I even provided explicitly path to the `tsserver`:
```
    require("lspconfig")["tsserver"].setup({
                on_attach = on_attach,
                capabilities = capabilities,
                cmd = { 
          "/nix/store/mis3pr62zjli08kdxg6lqhvkjbiih7kq-typescript-language-server-0.9.6/bin/typescript-language-server",
          "--stdio",
          "--tsserver-path",
          "/nix/store/cq9s34idhmcwqiy4jb89ghlpr6x6wiz1-typescript-4.5.5/lib/" }
    })
```

Calling `typescript-language-server` explicitly with above parameters doesn't yield any errors.
```
/nix/store/mis3pr62zjli08kdxg6lqhvkjbiih7kq-typescript-language-server-0.9.6/bin/typescript-language-server \
--stdio \
--tsserver-path /nix/store/cq9s34idhmcwqiy4jb89ghlpr6x6wiz1-typescript-4.5.5/lib/ \
--log-level 4 \
--tsserver-log-file=ts-logs.txt --tsserver-log-verbosity=verbose
```

I wish the error message was a little bit more descriptive.

Did it find tsserver at all? If so, why was it considered as invalid? 

Could someone point me to a direction how can I debug that further? 

Thanks in advance!

**Comment by rchl** [comment]
Running from the terminal doesn't reproduce because the discovery of typescript is only triggered after the LSP `initialize` message was received which doesn't happen when running manually like that.

I guess there could be some extra verbose log messages added to debug cases like that.

**Comment by rchl** [comment]
I've added additional logs that will be visible with `--log-level 3` or higher that should make it is easy to debug this issue.

https://github.com/typescript-language-server/typescript-language-server/releases/tag/v0.9.7

**Comment by ghostbuster91** [comment]
Thanks that was really fast, I will try with the newest version and let you know what I find.

**Comment by carbonizer** [comment]
@ghostbuster91 I ran into the same problem. You should have been targeting `lib` a few more levels down:

`/nix/store/cq9s34idhmcwqiy4jb89ghlpr6x6wiz1-typescript-4.5.5/lib/node_modules/typescript/lib/`

**Comment by ghostbuster91** [comment]
@carbonizer Thanks a lot! It worked like a charm :)

**Comment by jrgiacone** [comment]
> @carbonizer Thanks a lot! It worked like a charm :)

I get permission denied on this? any idea: Spawning language server with cmd: `/nix/store/v4lcvq8ymzgyzc5iinpp
3lc5lvvgrl36-typescript-language-server-2.1.0/lib/node_modules/type
script-language-server/lib/` failed with error message: EACCES: per
mission denied

**Comment by rchl** [comment]
Check the path. It looks kinda broken to me (there is a space in one place and also not sure about the directory structure):
```
/nix/store/v4lcvq8ymzgyzc5iinpp 3lc5lvvgrl36-typescript-language-server-2.1.0/lib/node_modules/type script-language-server/lib/
```
