### ISSUE TITLE
Go to definition function broken in monorepo project

### ISSUE THREAD

**Issue by RyanzpLee** [typescript-language-server/typescript-language-server#431]
Following on from this issue report here neovim/nvim-lspconfig#1830 I'm reporting it here in hopes that something could be done about this.

### Neovim version

NVIM v0.7.0-dev+1387-gd73bf3138
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

fd7843ad04cbc8ee2181bed9c3e83839b0d0b285

### Operating system and version

macOS 12.3

### Affected language servers

tsserver 0.9.7

### Description

In the particular project repository that I'm working on, there is a global `node_modules` folder at the root level which contains the typescript module. Within an app, when I want to go the definition of a JSX component with neovim's lsp client it puts me on the import line instead of taking me to the file where it is defined.

However, if I remove the typescript module from the root level `node_modules`, then suddenly the 'go to definition' functionality works as expected. [Here is an asciinema recording showing this behaviour](https://asciinema.org/a/vAn6bmxHSaE2j8asE5F5hC41D)

This behaviour works when I use vscode and coc.nvim, but neovims built in lsp client works different as it does not use tsserver directly. [Here is a screen recording showing the different behaviour to vscode and neovim](https://streamable.com/5mp81j)

Follow the steps below to reproduce the problem. 

1. [Setup a minimal config](https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua)
2. Have tsserver installed npm install -g typescript typescript-language-server
3. [Clone this repo](https://github.com/RyanzpLee/test-monorepo-lsp) and rename test_node_modules to `node_modules` to simulate a global node modules that gets shared across all apps in `apps/`
4. Go to apps/app1/src/page1.jsx and put your cursor on `<NiceComponentOverlay />`
5. Use <cmd>lua vim.lsp.buf.definition()<CR> which should be mapped to gd
6. it will only jump to line 2 where it is imported.
7. Expected behaviour is to jump to apps/app1/src/pages/page1/components/NiceComponentOverlay/NiceComponentOverlay.jsx
8. Remove test-monorepo-lsp/node_modules/typescript
9. Repeat steps 4 - 5 for desired behaviour

Is there something that I can change on my end, or is this something that has to be fixed as part of the language server?

**Comment by rchl** [comment]
You've lost some content in this description. For example point 4 doesn't say what to put the cursor on.

**Comment by rchl** [comment]
I've replied in https://github.com/neovim/nvim-lspconfig/issues/1830

**Comment by RyanzpLee** [comment]
> You've lost some content in this description. For example point 4 doesn't say what to put the cursor on.

Ah I didn't realise putting things in  `<>` would hide them on markdown, thats why it was hidden!

**Comment by rchl** [comment]
Resolving per comment linked earlier.
