### ISSUE TITLE
Renaming JSX attributes not working correctly

### ISSUE THREAD

**Issue by xnorly** [typescript-language-server/typescript-language-server#434]
## My setup
- iTerm2 3.4.15
- NeoVim 0.6.1
- typescript-language-server@0.9.7 (installed globally with npm)
- typescript@4.6.3 (installed globally with npm)
- a react typescript project created with `yarn create react-app my-test-app --template typescript`

## Reproducing steps
- download the [minimal_init.lua](https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua) file (with `local name` set to `"tsserver"`) and put it in the react project folder
- `cd` into the react project folder and open up `src/App.tsx` with neovim (using the minimal_init.lua file): 
```bash
nvim -u minimal_init.lua src/App.tsx
```
- hit `:q` and `enter` to close the window showing `packer.nvim`
- move the cursor to the first instance of the word `className` (use `h`, `j`, `k`, `l` to move around)
- (still in neovim) run the following command `:lsp vim.lsp.buf.rename("newName")` which should change all occurrences of `className` to `newName`
- hit `u` to undo the renaming (this only reverts the changes in App.tsx file, but not the changes made in other files)
- try using the renaming command from above once again

## What I expected
that all occurrences of `className` would be renamed again

## What happened
only the instance under the cursor changed, all other instances remained unchanged

## Observations
If the undo operation is done in all affected files (not just in `App.tsx`), the renaming will work again correctly

## tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}
```

**Comment by xnorly** [comment]
And suddenly it started working. Don't know why.

**Comment by xnorly** [comment]
Sometimes it works, sometimes it doesn't.

Here are the logs from the times when it doesn't work:
[mylog.log](https://github.com/typescript-language-server/typescript-language-server/files/8476915/mylog.log)

**Comment by mjlbach** [comment]
It's probably most meaningful if you extract/show only the RPC logs to make this question neovim agnostic, as typescript-language-server is not neovim specific.

**Comment by mjlbach** [comment]
```
[DEBUG][2022-04-13 00:31:07] .../lua/vim/lsp.lua:962	"LSP[tsserver]"	"client.request"	1	"textDocument/rename"	{
  newName = "classNewName",
  position = {
    character = 9,
    line = 8
  },
  textDocument = {
    uri = "file:///Users/userName/my-eslint/src/App.tsx"
  }
}	<function 1>	1
[DEBUG][2022-04-13 00:31:07] .../vim/lsp/rpc.lua:347	"rpc.send"	{
  id = 3,
  jsonrpc = "2.0",
  method = "textDocument/rename",
  params = {
    newName = "classNewName",
    position = {
      character = 9,
      line = 8
    },
    textDocument = {
      uri = "file:///Users/userName/my-eslint/src/App.tsx"
    }
  }
}
[DEBUG][2022-04-13 00:31:07] .../vim/lsp/rpc.lua:454	"rpc.receive"	{
  id = 3,
  jsonrpc = "2.0",
  result = {
    changes = {
      ["file:///Users/userName/my-eslint/src/App.tsx"] = { {
          newText = "classNewName",
          range = {
            end = {
              character = 18,
              line = 8
            },
            start = {
              character = 9,
              line = 8
            }
          }
        } }
    }
  }
}
```

**Comment by rchl** [comment]
Please share a complete project that I could test with using another editor as I'm not familiar enough with neovim to be able to test it there.

And BTW, if it also reproduces in VSCode then it's most likely an issue in typescript or with the configuration (`tsconfig.json`).

**Comment by xnorly** [comment]
@rchl thank you for your response and sorry for the delay

I am not able to provide another project to demonstrate the behaviour.

But I tried with VSCode and it doesn't reproduce there.
(renaming, then undo the renaming and then renaming again works fine in VS Code).

If anyone has an idea what to do next, I'll be happy to try it out.

best regards

**Comment by rchl** [comment]
1. I had to use `yarn create react-app test-react --template typescript` as your command didn't produce a typescript project
2. I've tested this project in VSCode and it reproduced this issue also
3. `className` is a property defined in `node_modules/@types/react/index.d.ts` and it seems like typescript is also modifying this file, even though it's a dependency. So I think that's the reason why it causes problems. If the change is not reverted from the dependency then it wouldn't know anymore what `className` really is as there is no type for it.

So it seems to work as expected to me.

**Comment by rchl** [comment]
4. BTW. Your log doesn't show changes to `node_modules/@types/react/index.d.ts`. That's likely because it was already modified in your previous attempts. And in that situations there is no `className` defined in the react types so typescript is not able to infer that it's the same attribute being used on all the elements so just renames the word under the cursor. You can delete `node_modules` and re-install dependencies to get a fresh state again and then renaming should also produce a change to `node_modules/@types/react/index.d.ts` in the log. An in VSCode at least, renaming doesn't automatically open the `node_modules/@types/react/index.d.ts` file but it does change its content so it's not possible to revert it from the UI.

**Comment by xnorly** [comment]
1. I am sorry, I left out `--template typescript` unintentionally.
2. I'm probably not familiar enough with VSCode, so I need to try it again
3. Oh, that makes a lot of sense. Thank you! So I should just be more careful when renaming JSX attributes that are already defined somewhere in the dependencies.

**Comment by xnorly** [comment]
4.
- "That's likely because it was already modified in your previous attempts"
this is very likely! :)
- "so it's not possible to revert it from the UI"
That's probably why I wasn't able to reproduce it.

Thank you so much @rchl.

**Comment by xnorly** [comment]
Is there a way to tell typescript not to rename stuff within dependency files? That would probably solve my "issue".

**Comment by rchl** [comment]
No, I don't think so.

But the main issue here is that you are attempting to use semantic rename for renaming the built-in attribute. LSP will attempt to rename also the definition which is generally an expected thing to do to keep the project valid and working.

While this case is very likely not the expected outcome for most users, what could the alternative be? Rename uses of `className` but not the definition? That would not really produce a working code in most cases. Or should it disallow rename? That would also be bad as it would prevent some legitimate cases from working.

I feel like protection against modifying files in `node_modules` would more fit within the client implementation side. It could warn the user or something. But that would be a heuristic specific to node and not really suitable to be in typescript or this server itself.

**Comment by xnorly** [comment]
The reason I wanted to rename all instances of `className` was that I wanted to try out [emotion](https://emotion.sh/docs/introduction) library.
Using emotion, you don't use the `className` attribute, instead you use the `css` attribute like so:
```javascript
<div
  css={css`
    padding: 32px;
  `}
>
```
So for this (maybe rare) case, renaming all instances of className, but not the definition, would make sense and still produce a working code (if you correctly add all the css stylings you wish to use).

I also think that disallowing the rename would not be optimal.

Maybe a tsconfig option to protect against modification in `some_folder` would work? Since it could be set to any folder, it would not be a setting specific to node.

**Comment by rchl** [comment]
That would be up to [Typescript](https://github.com/microsoft/TypeScript) to implement though so you can discuss this use case there if you want. Though I would say that limiting what the `rename` response returns is not the right approach and, if anything, the better approach would be to just ignore specific file paths on the client/editor side.

**Comment by xnorly** [comment]
Ok. Thank you for all your explanations. Appreciated very much!
I will close the issue now.
