### ISSUE TITLE
Allow auto-import as type

### ISSUE THREAD

**Issue by zanona** [typescript-language-server/typescript-language-server#446]
Hello, apologies if this currently possible through some existing option, but it would be great to be able to auto import interfaces as type rather than in the same line as normal dependencies like:

```ts
import {method} from 'foo';
import type {AType} from 'foo';
``` 

So whenever request `AType` it would add the second line above. Currently, it just adds to the same import of the first line as

```ts
import {AType, method} from 'foo';
```

This is ideal for anyone approaching the code and immediately being able to tell which dependencies are type only.

**Comment by rchl** [comment]
The logic for that is in https://github.com/microsoft/TypeScript so I would suggest discussing it there.

**Comment by zanona** [comment]
Thanks for the heads up. Will do 👍
