### ISSUE TITLE
SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by GabrielDuarteM** [typescript-language-server/typescript-language-server#466]
Hey! 👋

I'm trying to run the language server on vim, but its failing unexpectedly. If I run `typescript-language-server` directly on the console, I get the following error:

```sh
$ typescript-language-server

/home/gabriel/.asdf/installs/nodejs/12.7.0/.npm/lib/node_modules/typescript-language-server/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40
        return this._head?.value;
                          ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:720:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/gabriel/.asdf/installs/nodejs/12.7.0/.npm/lib/node_modules/typescript-language-server/node_modules/vscode-languageserver-protocol/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
```

My guess is that the node version used on the project is a bit old, because if I run the same command on node 16, it spits out some usage info, as I would expect:

```sh
$ typescript-language-server
error: required option '--stdio' not specified
```

The failing env:
```
Node 12.7.0
npm 6.10.0
typescript-language-server@0.10.0
typescript@4.6.4
```

I can't easily change the node version atm, so I was just wondering if I can just downgrade to a combination of versions which would run on that env, and what would those versions be, as I can't find much about node compatibility versions of this package... Is that possible?

**Comment by kazk** [comment]
I had v0.6.2 installed in a Node 12 container image (`npm i -g typescript-language-server@0.6.2`), and this started after rebuilding the image.

This is caused by a transitive dependency `vscode-jsonrpc` updated to `8.0.0` which now requires Node 14 and above.  
To prevent this from happening, `typescript-language-server` should include [`npm-shrinkwrap.json`](https://docs.npmjs.com/cli/v8/configuring-npm/npm-shrinkwrap-json) which locks down dependency versions for consumers.

**Comment by rchl** [comment]
The version could be pinned at the package.json level. And that would probably be OK in this case as we likely don't need anything from the new version of the libraries right now but in general we want to follow latest versions as those might expose things that new version of typescript uses. So just locking into specific versions is not very future-proof solution.

One could argue that at some point we should drop support for old Node versions anyway. The current stable version is version 16 and it wouldn't be that weird to require that.

When I have more time I will look into that and potentially revert to the old version of LSP libraries but it's not really viable long-term solution.

**Comment by rchl** [comment]
Released https://github.com/typescript-language-server/typescript-language-server/releases/tag/v0.10.1 with pinned LSP dependencies.
