### ISSUE TITLE
testing against latest TS

### ISSUE THREAD

**Issue by akosyakov** [typescript-language-server/typescript-language-server#47]
We run tests only against the typescript declared in packages.jon. It does not guarantee that it is going to work against other versions.

We should run tests against at least against the latest but for the backward compatibility probably against previous versions as well.

**Comment by rchl** [comment]
Ideally all functionality would be guarded by relevant typescript version checks but I think it's a bit too much to go back and fix it for all existing code. It's hard to know from which typescript versions a given code should work.

With #292 it will be pretty easy to add version guards to the new code at least.
