### ISSUE TITLE
Creates multiple instances

### ISSUE THREAD

**Issue by sarmong** [typescript-language-server/typescript-language-server#475]
typescript-language-server creates a new instance for each package in one neovim session

If I use `go_to_definition` to a function defined in some package in `node_modules`, a new tsserver instance is created. Same goes for library definitions, such as `Object.assign`. When buffer with such a file is deleted, tsserver process is still active.

Thus, just by navigating around the definition, I can get 5 tsserver instances, taking total of 8-10Gb of memory.

**Comment by rchl** [comment]
That would be a behavior that is defined by neovim, not this server itself. This server can only start one instance of tsserver so that means that this LSP server itself is started multiple times and that would be something that is controlled by neovim.

**Comment by sarmong** [comment]
I fix it by setting root_dir to detect `.git` folder first and foremost.
