### ISSUE TITLE
Report error when imports .vue files

### ISSUE THREAD

**Issue by ofseed** [typescript-language-server/typescript-language-server#477]
It diagnostics error when imports `.vue` files. How could I resolve this? the only way out is to disable it?
![image](https://user-images.githubusercontent.com/61115159/172035821-d0d37dab-37b6-4f9d-915d-03a09c23513d.png)

**Comment by predragnikolic** [comment]
See https://github.com/vuejs/vetur/blob/71aa326b93b152c02e886750d75eefdcb1db83bc/docs/guide/setup.md#typescript
