### ISSUE TITLE
Wrong tsconfig.json being used in monorepo

### ISSUE THREAD

**Issue by chiel** [typescript-language-server/typescript-language-server#495]
Hello! I'm setting up `typescript-language-server` for use with neovim's built in lsp client, using [neovim/nvim-lspconfig](https://github.com/neovim/nvim-lspconfig). While it is working perfectly in projects where only a single tsconfig is available, it struggles when there are multiple (which is common in a monorepo).

In a test repo (I didn't publish, let me know if that's needed) I have this `tsconfig.json` in my root:
```
{
  "compilerOptions": {
    "paths": {
      "@chiel/*": ["./packages/*/src"]
    }
  }
}
```
And then in the `packages/app` directory I have this tsconfig:
```
{
  "extends": "../../tsconfig.build.json",
  "compilerOptions": {
    "outDir": "./dist",
    "rootDir": "./src"
  }
}
```

When I remove the `tsconfig.json` in the `packages/app` directory, things continue to work fine since it's using the `paths` in the root `tsconfig.json` to resolve other packages. If I try to import another package from the `@chiel/*` scope, it manages to find the type definitions and everything is all good.

If I reinstate the `packages/app/tsconfig.json`, this import statement will throw errors such as:
```
Cannot find module '@chiel/whatever' or its corresponding type declarations.
```

So to me it feels like it's trying to use the wrong `tsconfig.json`. I did also check (through `:LspInfo`) that the root directory is being correctly resolved, but unfortunately this doesn't seem to make a different.

I've been banging my head against the wall for a bit now, but I'm not quite sure how to proceed/debug what's happening, so I'd appreciate some guidance. Cheers!

Edit: I've seen https://github.com/typescript-language-server/typescript-language-server/issues/431 as well, but it feels to me like this is a different issue - I don't actually have a globally-installed typescript as far as I'm aware - `which typescript` shows nothing.

**Comment by rchl** [comment]
The LSP server doesn't really have any logic to handle lookups or resolving of tsconfig. It's all done by typescript.

I suspect that if you just run `tsc .` in the root directory of the project then you will see the same issues.

Since I don't typically deal with configuration extending, I don't immediately see what's wrong here. If you'd create a simple project that reproduces this then I might have another look.

**Comment by rchl** [comment]
Unless maybe neovim starts separate instances of the the server for each `tsconfig.json` it sees. That would probably mess up the expected results.

**Comment by chiel** [comment]
Hmm okay, it is a bit of a known issue when running typescript in a monorepo that need multiple configs since behaviour between building and navigating around in your editor tend to be different, so I guess it's not too surprising that this is happening.

Out of curiosity, how does typescript get run? Does it look relative to the file that is being fed to it? Is there some kind of error/debug log kept anywhere?

**Comment by chiel** [comment]
I managed to "fix" it now by creating a `tsconfig.json` in the package directory which just extends the root `tsconfig.json`. It seems to do the trick, so I guess it's just some typescript weirdness like you said. Thanks for the help in any case! :)
