### ISSUE TITLE
CodeLens support

### ISSUE THREAD

**Issue by angelozerr** [typescript-language-server/typescript-language-server#5]
Like I had suggested at https://github.com/prabirshrestha/typescript-language-server/issues/9

tsserver doesn't supports CodeLens, but we could implement `textDocument/codeLens` and `codeLens/resolve` like VSCode does for [References CodeLens](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/referencesCodeLensProvider.ts) and [Implementations CodeLens](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/src/features/implementationsCodeLensProvider.ts)

**Comment by rchl** [comment]
I don't think it's feasible to implement that unless tsserver provides some fitting API. I think the only option now would be to iterate through all symbols in the file and trigger requests to get references/implementation which we obviously won't do for performance reasons.

**Comment by rchl** [comment]
Actually there is an API for that in tsserver and VSCode supports that functionality already.
