### ISSUE TITLE
Possibility of including Go to Source Definition?

### ISSUE THREAD

**Issue by ajitid** [typescript-language-server/typescript-language-server#507]
_Originally raised this issue in a [neovim plugin](https://github.com/jose-elias-alvarez/typescript.nvim/issues/13)._

Ref: [Go to source definiton](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/?q=1#go-to-source-definition)

When ctrl+clicking to invoke go to definition on an imported function, where being the function is coming from a dependency,, LSP would always link to its type definition and not to its actual defintion. This new Go to Source Definition could solve this. 

I'm unusre if tsserver actually exposes this (what I believe an) off-spec functionality.

**Comment by rchl** [comment]
Should be pretty easy to implement, based on the implementation in VSCode.

It could be a separate command that individual editors would then need to add some glue code for or the additional locations could just be bundled with the standard "go to definition" response but https://github.com/microsoft/TypeScript/pull/48264 gives a bunch of arguments why that might not be the best idea.

**Comment by sentriz** [comment]
do i understand correctly that #560 just adds a new "jump to source def" command? but still if i do a normal "jump to def" i still get a response that includes both the source def and the normal def?

**Comment by rchl** [comment]
No, it's a separate command and the new functionality is only available through that command.

See previous comment (and especially the link to Typescript repo) for reasoning.

**Comment by rchl** [comment]
Released in https://github.com/typescript-language-server/typescript-language-server/releases/tag/v1.1.0
