### ISSUE TITLE
workspace/didChangeConfiguration not working as expected

### ISSUE THREAD

**Issue by logesh14** [typescript-language-server/typescript-language-server#519]
I tried changing preferences by using  `workspace/didChangeConfiguration` and the server didn't  respect this change. I keep getting the results with default format options. `tsserver.log` has no trace of receiving this notification.

```
 TypescriptLanguageClient.sendCustomNotification('workspace/didChangeConfiguration', {
      settings: {
        typescript: {
          format: {
            insertSpaceAfterKeywordsInControlFlowStatements: false
          }
        }
      }
    })
```
Did i miss anything? any help is appreciated.

**Comment by rchl** [comment]
Can the client you are using log the LSP communication? I'd like to see it if so.

Also note that currently settings passed through that notification override all existing settings so ideally you would send all options every time. This should possibly be changed to do a merge.

**Comment by logesh14** [comment]
> Can your client log the LSP communication? I'd like to see it if so.

Double checked using debugger and logs, notification was sent.

code snippet:
```
this._rpc.sendNotification(method, params);
```

method : `workspace/didChangeConfiguration`
params :
```
{
  settings: {
    typescript: {
      format: {
        enable: true,
        insertSpaceAfterCommaDelimiter: true,
        insertSpaceAfterConstructor: false,
        insertSpaceAfterSemicolonInForStatements: true,
        insertSpaceBeforeAndAfterBinaryOperators: true,
        insertSpaceAfterKeywordsInControlFlowStatements: false,
        insertSpaceAfterFunctionKeywordForAnonymousFunctions: true,
        insertSpaceBeforeFunctionParenthesis: false,
        insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis: false,
        insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets: false,
        insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces: true,
        insertSpaceAfterOpeningAndBeforeClosingEmptyBraces: true,
        insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces: false,
        insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces: false,
        insertSpaceAfterTypeAssertion: false,
        placeOpenBraceOnNewLineForFunctions: false,
        placeOpenBraceOnNewLineForControlBlocks: false,
        semicolons: "ignore",
      },
    },
  },
}
```

modified option:
```
insertSpaceAfterKeywordsInControlFlowStatements: false
```
json-rpc version:
`vscode-jsonrpc: 5.0.1`

**Comment by rchl** [comment]
I'm interested in more detailed logs including the one that opens the file and one that sends the formatting request

**Comment by logesh14** [comment]
@rchl 
sample snippet (test.ts):
```
if(true){
    console.log("Hey!")
}
```

file open from client:
```
{
    textDocument: {
      uri: "file:///home/workspace/repo/test.ts",
      languageId: "typescript",
      version: 1,
      text: "if(true){\n    console.log(\"Hey!\")\n}",
    },
  }
```

formatting request from client:
```
{
    textDocument: {
      uri: "file:///home/workspace/repo/test.ts",
      version: 0,
    },
    options: {
      tabSize: 4,
      insertSpaces: true,
    },
  }
```
reposnse from server:
```
 [
    {
      range: {
        start: {
          line: 0,
          character: 2,
        },
        end: {
          line: 0,
          character: 2,
        },
      },
      newText: " ",
    },
    {
      range: {
        start: {
          line: 0,
          character: 8,
        },
        end: {
          line: 0,
          character: 8,
        },
      },
      newText: " ",
    },
  ]
```

I made sure the preferences were changed before formatting request.

**Comment by rchl** [comment]
I've tested it by slightly modifying this test:

https://github.com/typescript-language-server/typescript-language-server/blob/468e663f11b187203de022491df673c0a5846c2c/src/lsp-server.spec.ts#L775-L802

and it worked just fine for me.

Maybe make sure that no other configuration requests modify settings after you did it.

Also, you are sending `version: 0` in the formatting request while it was `version: 1` initially. Don't think that would be the cause of the issue but still this doesn't sound right.

**Comment by rchl** [comment]
You can also pass:

```
"initializationOptions": {
    "logVerbosity": "verbose",
}
```

to the initialize request to enable tsserver logs. Those would then be created in the project's root in `.log` directory and you can look there for a `configure` request that should match what you set.

**Comment by logesh14** [comment]
@rchl the issue is with client while opening the document, there is a case in which _languageId_ is passed as "javascript". So, the formatting options of typescript were ignored. :upside_down_face: 

Thanks for your time :smile:
