### ISSUE TITLE
code action doesn't suggest @ts-ignore

### ISSUE THREAD

**Issue by kamo93** [typescript-language-server/typescript-language-server#520]
Hi this is more question rather that a problem. I was wondering if it possible to the @ts-ignore as code action whenever a I have a typescript error. I don't know if that is possible or if I don't have well configure my tsserver on my nvim config.

**Comment by rchl** [comment]
This server just exposes what Typescript provides so such feature request would have to be requested at https://github.com/microsoft/TypeScript

**Comment by rchl** [comment]
And I should note that Typescript already has this feature enabled in JS files but not in TS files. I'm not sure what's the exact reasoning for that as I think there are still cases in TS where this can be useful.

**Comment by kamo93** [comment]
Yeah for sure. In my case I'm not pretty good at typescript so I use @ts-ignore just to continue with the develop and in IDEs like webstorm or vscode they suggest that option I thought it will be nice to have it in my neovim setup. Thanks for your help

**Comment by rchl** [comment]
VSCode behaves the same as this server, as far as I can tell -- supports this in JS files but not TS files.
