### ISSUE TITLE
project references support

### ISSUE THREAD

**Issue by akosyakov** [typescript-language-server/typescript-language-server#54]
I am trying to migrate Theia to them and cross-project navigation, completions are not working. I've checked that VS Code has some issues, but navigation and renaming works nicely there: https://github.com/Microsoft/TypeScript/issues/26467

**Comment by rchl** [comment]
This report seems a bit hard to figure out, I guess because you filed it as a member, implying some details you knew well.

So this might be either not relevant anymore or might need more details.

**Comment by rchl** [comment]
Closing due to lack of information.
