### ISSUE TITLE
Misleading tsserver not found error message

### ISSUE THREAD

**Issue by tzx** [typescript-language-server/typescript-language-server#554]
I think this is related: #411.

I am using `nix` to install `typescript` which gives me the binary `tsserver`, which is in my path. However, when starting my lsp server, it gives the error message: 
```
Request initialize failed with message: Could not find a valid tsserver executable in the workspace or in the $PATH. Please ensure that the "typescript" dependency is installed in either location. Exiting.
```

The solution is to use what one discussed in the issue linked by providing a explicit tsserver path. However this still means that the error message is misleading. Seems like the error is from finding a bundle version here: https://github.com/typescript-language-server/typescript-language-server/blob/master/src/lsp-server.ts#L180 which doesn't seem to look into `$PATH`.

**Comment by rchl** [comment]
An argument like `--tsserver-path tsserver` will lookup the binary in the PATH. Though if the argument is not provided then I agree that the message is confusing.

**Comment by rchl** [comment]
Made the error more generic in 585a05e43a0b530f10e488aed634fac0436109ae which should be more accurate.
