### ISSUE TITLE
Null bytes appearing in sortText

### ISSUE THREAD

**Issue by ktfleming** [typescript-language-server/typescript-language-server#559]
After upgrading to v1.0.0, I found a situation where completions no longer worked for my particular setup. I'm using Emacs and eglot as a client. Given the following contents:
```typescript
type Test = {
  first: string;
  second: string;
}

const a: Test = {
  // problem appears when getting completions here
}
```

with my cursor inside the `const a: Test = { }` block, I press TAB to bring up the list of completion items. In v0.11.2 of this library, this would correctly result in `first` and `second` appearing as completion items. With v1.0.0, nothing appears, and this seems to be caused by the returned `sortText` being different.

In v0.11.2. the sortText for these completion items looked like `"sortText": "11"`, while in v1.0.0, it looks like `"sortText": "11\u0000first\u0000"`. This causes an error where Emacs' built-in JSON parser does not allow null bytes in strings.

Other kinds of completion, like completion for methods on strings and numbers, still work fine.

I ran `git bisect` on this repo and found that this started happening with https://github.com/typescript-language-server/typescript-language-server/commit/49d6bb805321c5c7e9b21afa3e7c082c2f7b1ed4, which just upgrades the version of Typescript. So I'm not sure that this is really an issue with this project, although I see a few other LSP servers where similar issues have been reported:

https://github.com/MaskRay/ccls/issues/768
https://github.com/johnsoncodehk/volar/issues/1118#issuecomment-1094216983

I'm not familiar with the LSP spec enough to know whether null bytes appearing like this is expected, but at least in the case of `ccls` above, it seems like it was a bug in the server. But I thought I'd bring it up here to see if you had any ideas -- I appreciate that there might not be anything that can be done in this project.

**Comment by rchl** [comment]
Nice investigation!

From the sounds of it, it looks like a change in Typescript itself so, as you've guessed, not something that this server should handle.

You could raise or ask about it at https://github.com/microsoft/TypeScript/issues but I'm fairly sure that it's still a valid JSON so it might be difficult to argue for changing this.

**Comment by ktfleming** [comment]
I agree, I imagine that this actually would have to be addressed on the Emacs side, to allow it to accept this kind of string. And after doing a bit more looking around, to my pleasant surprise I found that this very change was made in Emacs 29 -- not released yet, but I was able to build the pre-release and the problem was fixed. Maybe if someone else runs into this, they'll find this issue and know what to do.

Thanks for the great work on this project!

**Comment by adimit** [comment]
For anyone having similar issues, in Emacs, at least, you can also patch older versions to allow null bytes in JSON:

```elisp
(advice-add 'json-parse-string :around
            (lambda (orig string &rest rest)
              (apply orig (s-replace "\\u0000" "" string)
                     rest)))
```

This just replaces all occurrences of the null byte with the empty string in all JSON inputs. See also [here](https://github.com/emacs-lsp/lsp-mode/issues/2681#issuecomment-792563858).

**Comment by fstuijt** [comment]
I tried the workaround above (advice-add 'json-parse-buffer), for my Emacs version (28.1) it did not work properly. Some small tweaks and now it works. So the complete work around would be:

```
(advice-add 'json-parse-string :around
            (lambda (orig string &rest rest)
              (apply orig (s-replace "\\u0000" "" string)
                     rest)))

;; saves excursion and uses search-forward instead
(advice-add 'json-parse-buffer :around
            (lambda (oldfn &rest args)
	      (save-excursion 
                (while (search-forward "\\u0000" nil t)
                  (replace-match "" nil t)))
		(apply oldfn args)))

**Comment by peter-wd-1** [comment]
I've tried the solution but now I'm getting next error 
```
with message (json-parse-error '[' or '{' expected near '","' <callback> 1 3 3)
Warning (lsp-mode): Failed to parse the following chunk:
```
