### ISSUE TITLE
Cannot use typescript-language-server on node v12

### ISSUE THREAD

**Issue by mbalazy** [typescript-language-server/typescript-language-server#565]
I want to use this package in project that still using node in version 12, but I can't make it.
In node v16 everything is ok. 
I'm using neovim with nvim-lspconfig and tsserver.

 
```
[mart@machine] ➜ exampleDir node -v
v16.15.1
[mart@machine] ➜ exampleDir typescript-language-server 
error: required option '--stdio' not specified
[mart@machine] ➜ exampleDir fnm use 12.21.0
Using Node v12.21.0
[mart@machine] ➜ exampleDir typescript-language-server 
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:fs/promises
    at Loader.builtinStrategy (internal/modules/esm/translators.js:281:11)
    at new ModuleJob (internal/modules/esm/module_job.js:37:41)
    at Loader.getModuleJob (internal/modules/esm/loader.js:277:11)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:49:17)
    at async Promise.all (index 1)
    at async link (internal/modules/esm/module_job.js:53:9) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}
[mart@machine] ➜ exampleDir 

```

Log from `lsp.log`:
```
[ERROR][2022-08-20 10:04:03] .../vim/lsp/rpc.lua:420	"rpc"	"typescript-language-server"	"stderr"	"internal/process/esm_loader.js:74\n    internalBinding('errors').triggerUncaughtException(\n                              ^\n\nError [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:fs/promises\n    at Loader.builtinStrategy (internal/modules/esm/translators.js:281:11)\n    at new ModuleJob (internal/modules/esm/module_job.js:37:41)\n    at Loader.getModuleJob (internal/modules/esm/loader.js:277:11)\n    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:49:17)\n    at async Promise.all (index 1)\n    at async link (internal/modules/esm/module_job.js:53:9) {\n  code: 'ERR_UNKNOWN_BUILTIN_MODULE'\n}\n"
```

How can I solve that?

**Comment by rchl** [comment]
As per the release notes of [version 1.0.0](https://github.com/typescript-language-server/typescript-language-server/releases/tag/v1.0.0), it now requires Node 14 at least.

You can stay on older version if you want it to work in Node <14.

But also, I'm not sure how nvim-lspconfig works, but does the node version used by the project have to be tied to the node version used by the language server? I would think that the language server could be running on newer node version still.

**Comment by mbalazy** [comment]
> As per the release notes of [version 1.0.0](https://github.com/typescript-language-server/typescript-language-server/releases/tag/v1.0.0), it now requires Node 14 at least.
> 
> 
> 
> You can stay on older version if you want it to work in Node <14.
> 
> 
> 
> But also, I'm not sure how nvim-lspconfig works, but does the node version used by the project have to be tied to the node version used by the language server? I would think that the language server could be running on newer node version still.

Thanks, I'm going to check the possibility of running nvim-lsp on  different version of node than the project one.
