### ISSUE TITLE
[question] Completions entry.replacementSpan is always undefined 

### ISSUE THREAD

**Issue by predragnikolic** [typescript-language-server/typescript-language-server#580]
[entry.replacementSpan](https://github.com/typescript-language-server/typescript-language-server/blob/f872078fa3b40d8b9b90f737fec7a4c808f1ccc7/src/completion.ts#L66) is always undefined for me.
and thus I never seem to get in this if statement?

https://github.com/typescript-language-server/typescript-language-server/blob/f872078fa3b40d8b9b90f737fec7a4c808f1ccc7/src/completion.ts#L112

What should I do to make the typescript API return CompletionEntry with replacementSpan?

I am using the latest master,
and the following typescript version "typescript": "^4.8.2".

----

Other things I tried/read:
I tried to dig in the code and found that if `CompletionEntry.replacementSpan` is missing, than the editor should use `CompletionInfo.optionalReplacementSpan`
```
interface CompletionInfo {
        readonly flags?: number;
        readonly isGlobalCompletion: boolean;
        readonly isMemberCompletion: boolean;
        readonly isNewIdentifierLocation: boolean;
        /**
         * In the absence of `CompletionEntry["replacementSpan"]`, the editor may choose whether to use
         * this span or its default one. If `CompletionEntry["replacementSpan"]` is defined, that span
         * must be used to commit that completion entry.
         */
        readonly optionalReplacementSpan?: TextSpan; // << This is the relavant part. 
        readonly isIncomplete?: boolean;
        readonly entries: readonly CompletionEntry[]; 
    }
```
But the typescript service is not returning  `CompletionEntry.replacementSpan`, nor it is returning  `CompletionInfo.optionalReplacementSpan`.

**Comment by predragnikolic** [comment]
FWIW I was experimenting with creating a PR for `InsertReplaceEdit` support for `CompletionItem.textEdit`
and stumbled upon this issue.

**Comment by rchl** [comment]
Some tests trigger this code path. For example a `test.ts` file with:

```ts
interface Foo {
    'invalid-identifier-name': string
}

const foo: Foo
foo.i
```

and triggering completions after `.i`.

**Comment by rchl** [comment]
I don't see even typescript-language-features in VSCode using `optionalReplacementSpan`. I feel like maybe editors really can just rely on its own logic in this case. Although that makes me think about some but in ST with `$` that maybe would be fixed when using `optionalReplacementSpan`... hmm

**Comment by predragnikolic** [comment]
I enabled volar in typescript files and volar is somehow getting `replacementSpan`.  (volar is also using `optionalReplacementSpan`).

I am diffing volar ts.UserPreferences to see if I need to enable a setting that will maybe cause `replacementSpan` to appear... still can't spot anything. :)

WIll continue looking at
https://github.com/johnsoncodehk/volar/blob/master/packages/typescript-language-service/src/services/completions/basic.ts

**Comment by rchl** [comment]
But you are getting replacementSpan in the test file that I've posted? So you are not getting it in which file?

**Comment by predragnikolic** [comment]
Yes, I am getting in the test file, but not in the following case :) 

```
document.g|etElementBy // cursor is after g
```

I expect to get replacementSpan text if I tirgger the autocomplete popup there....

I am on to something, :) will push a commit as soonish

**Comment by rchl** [comment]
It's the `optionalReplacementSpan` that makes it work in Volar, as far as I can see.

**Comment by predragnikolic** [comment]
Yes, https://github.com/predragnikolic/typescript-language-server/commit/795019654a698fb23008935fdabc88deea746d72

**Comment by predragnikolic** [comment]
The reason why I didn't got `CompletionInfo.optionalReplacementSpan` is because I was not triggering the autocomplete popup in a word, but rathar on an empty line, so the server didn't return anything. I have to be in a word in order to get `CompletionInfo.optionalReplacementSpan`. 

It makes sense now.

**Comment by rchl** [comment]
I'm a bit concerned about doing that as it will add a ton of extra bytes to the response which can already be in megabytes...

On the other hand, if it's just the correct thing to do, we might have to...

**Comment by predragnikolic** [comment]
original issue resolved :)
we can continue the discussion in #583
