### ISSUE TITLE
Add support for textDocument/prepareCallHierarchy

### ISSUE THREAD

**Issue by antogilbert** [typescript-language-server/typescript-language-server#591]
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareCallHierarchy

Would be great to have call hierarchy capabilities. I would be happy to work on this if given some guidance.

**Comment by predragnikolic** [comment]
Feel free to try. 
When you get stuck , reach out with a concrete problem that blocks you.
Someone will probably reply.

The first tip,
I would clone this repo.
Depending on the editor, setup the LSP client to open my local typescript server that I cloned.
Then I would see how other requests are implemented 🙂

**Comment by predragnikolic** [comment]
Coc-tsserver has call hierarchy implemented, so you could take a peek there https://github.com/neoclide/coc-tsserver

**Comment by nfrid** [comment]
there is already a PR for that feature, btw: https://github.com/typescript-language-server/typescript-language-server/pull/98

**Comment by rchl** [comment]
That PR is couple years old and already outdated relative to the specification.

Someone would need to make an effort to implement it properly.

A lot can be borrowed from VSCode implementation probably but I'm not sure how close VSCode implementation is to the LSP spec. Most likely would need to be adapted a bit.
