### ISSUE TITLE
Multiple Instances of `tsserver.js` and `typingsInstaller.js` will be created every time `:PackerCompile` is run. 

### ISSUE THREAD

**Issue by anthony-S93** [typescript-language-server/typescript-language-server#599]
As the title suggests, I am running `typescript-language-server` inside `Neovim` with `packer.nvim` as my package manager. I noticed that every time I run `:PackerCompile`, the `tsserver.js` and `typingsInstaller.js` duplicate themselves. Worst, these processes remained in memory even after I quit Neovim; I had to kill them directly either by using Htop or by sending a SIGTERM to it. 

**These are the exact steps I used to reproduce this behavior:** 
1) Open up htop, and then set filter (pressing F4) to see only processes starting with 'node'
2) Launch neovim and open up any .js file
3) Run `:PackerCompile` from inside Neovim. 
(At this point, we can easily observe via htop `typingInstaller.js` and `tsserver.js` duplicating itself)
4) Quit Neovim with `:q`
(Observe that the `typingInstaller.js` and `tsserver.js` processes are still running in the background)

**Additional Info:**
I first noticed this strange behavior when I was editing my plugin config file while a .js buffer is opened. And because I set up an autocommand to run `:PackerCompile` every time my config file is saved, I noticed (when I was done tweaking my config) that my RAM usage suddenly spiked to about 8GB, which rarely occurs even during heavy web-browsing. When I fired up htop, I was shocked to find up to nearly twenty instances of tsserver.js running in the background. And after some experimentation, I was able to figure out that `:PackerCompile` is the culprit. 

I put the config for all my Neovim plugins inside one file: `~/.config/nvim/lua/plugins.lua`:
```lua
--Plugin management
local packer = require('packer')
vim.cmd([[
    augroup packer_user_config
	autocmd!
	autocmd BufWritePost plugins.lua source <afile> | PackerCompile
    augroup end
]])

local plugins = packer.startup({function() 
    --irrelevant lines omitted
    use
    {
        "neovim/nvim-lspconfig",
        config = function()
              local lspconfig = require("lspconfig")
              -- more lines omitted
              lspconfig.pyright.setup {
                  --omitted lines
              }
              lspconfig.tsserver.setup {
               
              }
              --setup for other language servers
        end
    }
end,
config = {...}
})

return plugins
```
**Please note that only `typescript-language-server` has this issue. I ran `:PackerCompile` while other language servers are running (pyright, sumnekolua, etc), and none of them exhibit this behavior.**

**Comment by rchl** [comment]
I've noticed that too in ST and been looking for a way to fix it but haven't found one yet.

The issue is with using `Node IPC` rather than `stdio` to communicate with the `tsserrver` sub-processes. With stdio the subprocesses close on itself when the pipe is broken which doesn't happen with IPC (IPC is used if the tsserver version is `>=4.6.0`).

I'm guessing that neovim explicitly kills the language server process when done. This is partially the reason for this problem as if the editor wouldn't hard `kill` it, the process would shut down itself more cleanly after few seconds. But to be fair I can't blame editors for this as this "self killing" behavior might be specific to language servers based on vscode node libraries.

**Comment by rchl** [comment]
After investigating it more I found out that Node provides a way to detect that situation and the issue is in tsserver (typescript) itself. So I will disable IPC communication for now and wait until https://github.com/microsoft/TypeScript/issues/51100 is fixed.
