### ISSUE TITLE
Unable to resolve complex type if unincluded, and unable to parse Jest's moduleNameMapper

### ISSUE THREAD

**Issue by thedaviddelta** [typescript-language-server/typescript-language-server#602]
Hello!
I'm using `tsserver` inside Neovim's builtin LSP and I'm finding a couple of bugs inside some of my projects, that aren't happening neither in WebStorm nor VSCode.

The first of them is the inability to resolve a complex type that is being imported into a test file while this file is not included into compilation.
Basically, I have [this test](https://github.com/thedaviddelta/lingva-scraper/blob/main/tests/text.test.ts) that imports a type from [here](https://github.com/thedaviddelta/lingva-scraper/blob/main/src/utils/language.ts) and a function that also uses that type from [here](https://github.com/thedaviddelta/lingva-scraper/blob/main/src/text.ts). It's a complex type that reads an object from a `json` file and gets (and filters if needed) its keys. It always works correctly when used inside the `src` folder, but resolves to `never` when used inside `tests`.
The whole `tests` folder [isn't included in tsconfig](https://github.com/thedaviddelta/lingva-scraper/blob/main/tsconfig.json), as only `src` is. If I add `tests` to the includes, the type starts working, but that's not a viable solution as the `include` key is used to decide which files have to be compiled.
![imagen](https://user-images.githubusercontent.com/6679900/194772042-c3d0efde-94a8-4c0a-b3d9-5f649ea6b82a.png)

The second bug is happening in a different project and relates to Jest.
In this project, I have a `paths` key configured [inside tsconfig](https://github.com/thedaviddelta/lingva-translate/blob/main/tsconfig.json) to automatically parse every import starting with a `@` to the root of the project. In addition, I have this process repeated inside [Jest's config](https://github.com/thedaviddelta/lingva-translate/blob/main/jest.config.js), as this is needed for the parsing to work inside test files.
The first feature works correctly, as every `@` import in standard code files resolves. But `@` imports don't work inside test files (e.g. [this one](https://github.com/thedaviddelta/lingva-translate/blob/main/tests/Page.test.tsx)).
![imagen](https://user-images.githubusercontent.com/6679900/194772115-4d51150e-701b-4f62-ad38-a911ebe7fd6c.png)

Thank you so much for this server.
Regards, David.

**Comment by rchl** [comment]
It's about the implicit defaults that are assumed when the `compilerOptions` are not explicitly provided.

This server runs with a bit outdated defaults compared to VSCode and I'll update those to match.

VSCode assumes those defaults:

```json
{
        "module": "ESNext",
        "moduleResolution": "Node",
        "target": "ES2020",
        "jsx": "react",
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "sourceMap": true,
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "allowNonTsExtensions": true,
        "resolveJsonModule": true
    }
```

which this server currently defaults to:

```json
{
    "module": "CommonJS",
    "target": "ES2016",
    "jsx": "Preserve",
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "allowNonTsExtensions": true
}
```

I would anyway suggest creating a tests-specific `tsconfig.json` which can have its own default or even include the base one and override certain settings like `emit`.

**Comment by thedaviddelta** [comment]
Thank you for the suggestion.
I do have it on some projects but not in this one, as it worked correctly without it.
As for the defaults, I just added the missing properties from VSCode you mentioned to the existing `tsconfig`s of those projects and the problems were still there :cry: What do you think about it?

**Comment by rchl** [comment]
The existing tsconfig.json doesn't have any effect on those files as those are not included in the project (using either `include` or `files` options in `tsconfig.json`).

You can create `tests/tsconfig.json` with:

```js
{
    "extends": "../tsconfig.json",
    "compilerOptions": {
        "module": "ESNext",
        "moduleResolution": "Node",
        "target": "es2020",
        "noEmit": true,
    },
    "include": [
        "."
    ]
}
```

**Comment by thedaviddelta** [comment]
Ohh, I see, thank you so much!
In addition, you say you'll change those defaults in the next version, right?
I'll look forward for it!

Regards, David.
