### ISSUE TITLE
`logVerbosity` setting ignored

### ISSUE THREAD

**Issue by mskelton** [typescript-language-server/typescript-language-server#608]
From the readme, it would indicate you can specify the `tsserver` log verbosity via a `logVerbosity` key in the options:

https://github.com/typescript-language-server/typescript-language-server#initializationoptions

```md
logVerbosity | string | The verbosity level of the information printed in the log by tsserver. Accepts values: "off", "terse", "normal", "requesttime", "verbose". Default: undefined ("off").
```

However, it does not appear that flag is being respected, requiring instead passing the `--tsserver-log-verbosity` flag to change the log verbosity.

I'm happy to open a PR to fix or remove the `logVerbosity` key from the docs, whichever is the correct course of action.

**Comment by rchl** [comment]
It does look like it's unused indeed and should be removed.

(I'm in the process of refactoring those and moving all those tsserver options to `initializationOptions` but it didn't happen yet for this one.)
