### ISSUE TITLE
Pretty-printing with Typescript LS?

### ISSUE THREAD

**Issue by the42** [typescript-language-server/typescript-language-server#620]
I am sending this upon typescript LS invocation:

```lisp
(:jsonrpc "2.0" :method "workspace/didChangeConfiguration" :params
		  (:settings
		   (:typescript-language-server
			(:javascript
			 (:format
			  (:placeOpenBraceOnNewLineForControlBlocks t))))))
```
expecting that `[ "data" : "foo"}` would be formatted as
```json
{
  "data" : "foo"
}
```
yet editors content remains unchanged. Do I missinterpret what `placeOpenBraceOnNewLineForControlBlocks` is supposed to do I pass parameters wrong? Btw. using Emacs eglot ls-client btw.

**Comment by rchl** [comment]
This is not a control block but a literal object. I don't see any options for controlling formatting of this case.

For more control over formatting I would suggest using eslint (also available in LSP form).

**Comment by rchl** [comment]
And if you feel like this should be supported then you can raise it in TypeScript repo since it's TypeScript that provides this functionality.
