### ISSUE TITLE
.ts module autocompletion

### ISSUE THREAD

**Issue by theoparis** [typescript-language-server/typescript-language-server#621]
As seen in https://github.com/facebookresearch/shumai/issues/119, when importing a package that has no types field and only a `module` field set to a .ts file it does not pick up autocompletion at all. I'm wondering if there's a way this could be supported in the future.

This is mainly needed because [bun](https://bun.sh) supports running .ts files directly, as the code runs fine but does not get picked up by the neovim correctly.

example package.json:

```
{
  "name": "@shumai/shumai",
  "version": "0.0.9",
  "module": "shumai/index.ts",
  "type": "module"
}
```

**Comment by rchl** [comment]
This would need to be requested in the TypeScript repo itself - https://github.com/microsoft/TypeScript/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
