### ISSUE TITLE
missing import code action tries to import React unnecessarily

### ISSUE THREAD

**Issue by davidhu2000** [typescript-language-server/typescript-language-server#623]
In the case below where we are missing `import { Image } from 'react-native';`

```tsx
import { render } from '@testing-library/react-native';

describe('test lsp', () => {
  render(<Image />);
});
```

the available code action from the `tsserver` are 
<img width="634" alt="Screen Shot 2022-11-14 at 12 08 24 PM" src="https://user-images.githubusercontent.com/15827041/201755599-559cc6ec-7ea5-4cc0-928b-6d1f22bbb75f.png">

because we are using react-18, importing react is unnecessary. 

After adding 

```tsx
import React from' react';
```
then the code actions work 

<img width="627" alt="Screen Shot 2022-11-14 at 12 09 05 PM" src="https://user-images.githubusercontent.com/15827041/201755768-c0a482ac-4ae9-489c-9ab9-9e8518a82cb1.png">

the `Add import from "react-native"` should show up on the first try. 

```
typescript-language-server --version
2.1.0
```

**Comment by rchl** [comment]
Are you able to provide a minimal project that reproduces this issue?

**Comment by davidhu2000** [comment]
@rchl, I created a quick repo to reproduce.  https://github.com/davidhu2000/ts-lsp-import-bug 

I did someadditional tests, and it appears that the following option works

```json
{
  "compilerOptions": {
    "jsx": "react-jsx",
```

however, `jsx: 'react-native'`  or `jsx: react` does not work. does this mean this is a typescript issue?

**Comment by rchl** [comment]
> Possibly related? [microsoft/TypeScript#41762](https://github.com/microsoft/TypeScript/issues/41762)

I suppose so.
If this also works the same in VSCode then most definitively something that Typescript might need to handle.

**Comment by davidhu2000** [comment]
Yeah. Also happening in VS Code, l I'll open an issue with typescript
