### ISSUE TITLE
Inconsistent symbols in javascript project

### ISSUE THREAD

**Issue by yuval-piiano** [typescript-language-server/typescript-language-server#645]
I am using tthe lsp to get symbols in the files of this project https://github.com/shopizer-ecommerce/shopizer-shop-reactjs , 
The documentSymbols request for the file returns different results based on what requests I am doing before: 
If I open the https://github.com/shopizer-ecommerce/shopizer-shop-reactjs/blob/main/src/App.js as the first file,  I am getting  19 children for the symbol App (attached response as file App_as_first.txt)

If I am doing the same request after opening (and documentSymbol) for the index.js file (https://github.com/shopizer-ecommerce/shopizer-shop-reactjs/blob/main/src/index.js)  , I am getting 1 child for the symbol named 'App' (attached response in file App_after_index_response.txt ) 

Any explanation for this inconsistency? How to solve it? 

[App_as_first.txt](https://github.com/typescript-language-server/typescript-language-server/files/10307580/App_as_first.txt)
[App_after_index_response.txt](https://github.com/typescript-language-server/typescript-language-server/files/10307581/App_after_index_response.txt)

**Comment by rchl** [comment]
Haven't looked into it (yet) but I would suggest creating explicit `tsconfig.json` file with configuration instead of relying on implicit one. Then you can specify which files belong to a project and possibly that would fix the random behavior. Let  me know results after trying that.

**Comment by rchl** [comment]
I consistently see 19 symbols both before and after opening `index.js` here.

This is with Node 16, with server using workspace-local Typescript 4.6.4.

**Comment by rchl** [comment]
timeout
