### ISSUE TITLE
Code actions not working

### ISSUE THREAD

**Issue by yusuphgammut** [typescript-language-server/typescript-language-server#655]
Hi folks.

I've been using this LS for a while now with very good results. The only thing I can't manage to make work is code actions.

I opened a [discussion](https://neovim.discourse.group/t/code-actions-not-working-for-typescript-language-server/3525) on the Neovim discourse group and someone suggested me to use an [extension](https://github.com/jose-elias-alvarez/typescript.nvim) to this LS. However, the documentation in this LS [says](https://github.com/typescript-language-server/typescript-language-server#apply-code-action) it supports code actions out of the box, or at least that's what I understand.

Am I missing something in my configuration to make code actions work with no additional extensions?

Many thanks.

**Comment by rchl** [comment]
Are you getting diagnostic about variable being unused? You should get it in the first place and then code action should also be available. Hard to say what's the issue in your specific project. Could be related to `tsconfig.json` configuration.

You can try in this very project. Check it out, install dependencies and for example add

```ts
const x = 1;
```

line at the end of `src/cli.ts`. You should get code action to remove the variable.

**Comment by rchl** [comment]
No response so assuming it's a project-specific issue. Feel free to provide more information if you still think it's a server issue.

**Comment by yusuphgammut** [comment]
Hi @rchl . Thanks for the answer. Excuse my late reply, I was on vacations trying to disconnect a bit from stuff.

I've cloned this project's repo, added the suggested line, and as expected, I can see the diagnostic about the variable being unused. Then I put the cursor on the `x` and I get the code action and it works 🥳 .

If I move to my project and try the same, I don't get any actions. Do you have any idea on what configuration might mess with the server? This is my `tsconfig.json` file.

``` json
{
  "compilerOptions": {
    "target": "es2016",
    "lib": ["dom", "esnext"],
    "jsx": "react",
    "types": [
      "node",
      "jest",
      "@testing-library/jest-dom"
    ],
    "baseUrl": "./src",
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "allowJs": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noFallthroughCasesInSwitch": true,
    "noEmit": true
  },
  "include": ["jest-setup.ts", "src"]
}
```

Additionally, while working in this project's repo I tried messing the order of the imports, even moving one to the end of the file, but no diagnostics appeared, and I wasn't able to get any `organizeImports` code action on any part of the document. Am I understanding wrong how this action should work?

**Comment by rchl** [comment]
To many variables. Maybe type checking is failing completely somewhere else (does `tsc` on the command line give clean output?), maybe there is something else about the project. Can't say without playing with an actual project that reproduces.

**Comment by yusuphgammut** [comment]
I compared the tsconfig file from this project with mine and I was able to detect the missing options there. 

``` json
{
  "compilerOptions": {
    "noUnusedLocals": true,
    "noUnusedParameters": true
  }
}
```

Once I added those options, the `removeUnused` action was available. I was also able to use the `addMissingImports` action as well.

However, I can't manage to create an instance when the `fixAll` and `organizeImports` is available. I've tried in this project's repo and in mine unsuccesfully.

**Comment by rchl** [comment]
Those two are special and are intended to be used with "code actions on save" feature of the editor or requested explicitly with a custom command. You'd have to consult with documentation of your editor and you can also check readme of this server

**Comment by yusuphgammut** [comment]
Ok. I understand. Thanks for your time and patience.
