### ISSUE TITLE
Are arrow functions supposed to not have snippets attached?

### ISSUE THREAD

**Issue by Avishayy** [typescript-language-server/typescript-language-server#656]
I couldn't find helpful information by searching, so I figured out I might ask if it's even supported at all.

I've configured nvim (with nvim-cmp and nvim-lspconfig) to provide completions for functions
<details>

  <summary>Config (if relevant)</summary>

```lua
    "neovim/nvim-lspconfig",
    dependencies = {
      "hrsh7th/nvim-cmp",
    },
    config = function()
      local capabilities = require('cmp_nvim_lsp').default_capabilities()
      capabilities.textDocument.completion.completionItem.snippetSupport = true

      local on_attach = function(client, bufnr)
        -- If the LSP supports formatting, allow for format-on-save through LSP
        if client.server_capabilities.document_formatting then
          vim.cmd("autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()")
        end
      end

      require'lspconfig'.tsserver.setup {
        capabilities = capabilities,
        on_attach = on_attach,
        settings = {
          completions = {
            completeFunctionCalls = true
          }
        },
        init_options = {
          hostInfo = "neovim",
          preferences = {
            includeCompletionsWithSnippetText = true,
            includeCompletionsForImportStatements = true,
          },
        },
      }
   end
```

</details>

I tested it and it works great for functions, example:
<img width="677" alt="image" src="https://user-images.githubusercontent.com/5567310/211161235-f5b1e056-7108-4896-bf9f-3736669ac0d4.png">

However, if I use an arrow function, the token is regarded as a const and I do not have any completions offered
<img width="688" alt="image" src="https://user-images.githubusercontent.com/5567310/211161250-0a20d340-dc98-4de9-b800-906761bcc157.png">

Is this a missing feature / wrong configuration on my part?

Thank you

**Comment by rchl** [comment]
It appears to be working like that in VSCode also so I guess that's how it works right now. You could report this at https://github.com/microsoft/TypeScript and see what they have to say since the functionality comes from there.

**Comment by Avishayy** [comment]
I will, thank you!
