### ISSUE TITLE
Hard dependency on typescript

### ISSUE THREAD

**Issue by thatsmydoing** [typescript-language-server/typescript-language-server#658]
With https://github.com/typescript-language-server/typescript-language-server/pull/618 there is now a hard dependency on typescript since it's actually imported instead of just importing types. This means that `typescript` should be added to the `dependencies` in package.json or the import be switched back to `import type` (which would also require copying the enums into the source again).

In practice, this doesn't affect most users since the instructions also say to install `typescript` globally, but for users who run it via `npx` or use a different package manager like [nix](https://github.com/NixOS/nixpkgs/issues/210051), the dependency isn't installed and breaks with

```
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'typescript' imported from /home/thomas/.npm/_npx/94207acffe67148d/node_modules/typescript-language-server/lib/ts-protocol.js
    at new NodeError (node:internal/errors:393:5)
    at packageResolve (node:internal/modules/esm/resolve:860:9)
    at moduleResolve (node:internal/modules/esm/resolve:909:20)
    at defaultResolve (node:internal/modules/esm/resolve:1124:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by rchl** [comment]
Right, I will probably have to duplicate those enums again then.

To make things as clean as possible though, I would ideally want to re-export a namespace (but only types) from typescript but I don't quite see a way to do that in typescript. Maybe someone else knows if it's possible: https://stackoverflow.com/questions/75082546/re-export-namespace-using-type-specifier :)

**Comment by thecodrr** [comment]
I am also having this error even after installing `typescript` globally on Windows 11. Any way to fix this temporarily?

**Comment by rchl** [comment]
Revert to version [v2.1.0](https://github.com/typescript-language-server/typescript-language-server/releases/tag/v2.1.0)

**Comment by thatsmydoing** [comment]
> Right, I will probably have to duplicate those enums again then.
> 
> To make things as clean as possible though, I would ideally want to re-export a namespace (but only types) from typescript but I don't quite see a way to do that in typescript. Maybe someone else knows if it's possible: https://stackoverflow.com/questions/75082546/re-export-namespace-using-type-specifier :)

It seems like this is coming in typescript 5.0 https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#support-for-export-type

**Comment by rchl** [comment]
I don't think it will cover this specific need where I want to export a nested namespace rather than everything from a module.
