### ISSUE TITLE
Typescript server repetitively "initializing language features" causing high CPU usage at idle

### ISSUE THREAD

**Issue by mpearce-bain** [typescript-language-server/typescript-language-server#666]
#### Description
When working in a Svelte repository with a TS and Svelte file open, VSCode begins rapidly flashing the "initializing JS/TS language features" notification in the bottom LH bar. I also notice the notification bell in the bottom RH bar flickering on and off with a new notification.  This drives high CPU usage and noticeably slows down intellisense in my repo.

This behavior doesn't appear to be linked to any user input other than opening both `*.svelte` and `*.ts` files concurrently, and it will continue indefinitely until the VSCode instance is restarted. Running the "Typescript: Restart Language Server" command will temporarily halt the behavior, but it resumes within 30s afterward. If TS logging is turned on, the logs will grow indefinitely in size (in one instance I had a 2GB log file in <5 minutes).

Would anyone be able to suggest a potential next troubleshooting step?

#### Troubleshooting Attempts
* Restart TS Language Server
* Restart VSCode
* Clean Install of VSCode
* Update to latest nightly version of TS

#### Versioning
* VSCode: 1.74.3
* TypeScript: 4.9.4 and 5.0.0-dev (observed behavior in both versions)
* Svelte VSCode Plugin: 107.0.1

#### Logs
[tsserver.log](https://github.com/typescript-language-server/typescript-language-server/files/10428374/tsserver.log)

**Comment by rchl** [comment]
You'd have to report that against VSCode (https://github.com/microsoft/vscode). It doesn't use this server.

**Comment by mpearce-bain** [comment]
@rchl Ahh, thank you for the clarification and apologies for the false flag 👍
