### ISSUE TITLE
Add a shrinkwrap.json to prevent code injection when installing from npm

### ISSUE THREAD

**Issue by keyboardDrummer** [typescript-language-server/typescript-language-server#67]
For npm packages that are intended to be used as command line tools, a `shrinkwrap.json` should be added to the package to prevent malicious code entering the package installation through dependencies. Using strict version numbers in specifying the dependencies in `package.json` is not enough, because that does not specify the entire dependency tree. A malicious or hacked NPM author of a dependency's dependency can update a new version of that package, and through that inject malicious code.

See [the documentation](https://docs.npmjs.com/files/shrinkwrap.json): `The recommended use-case for npm-shrinkwrap.json is applications deployed through the publishing process on the registry: for example, daemons and command-line tools intended as global installs or devDependencies.`

**Comment by akosyakov** [comment]
Do you mean to publish it to npm?

**Comment by keyboardDrummer** [comment]
Yes, I mean that without a `shrinkwrap.json`, if you install from NPM, the versions in the dependency tree will not be fixed.

**Comment by pyrho** [comment]
If I'm not mistaken, the versioned "yarn.lock" file serves the same purpose as npm's "shrinkwrap.json" (which has been replaced by the "package-lock.json" file nowadays).

So I guess this issue can be closed?

**Comment by rchl** [comment]
`package-lock.json` doesn't replace `shrinkwrap.json`. package-lock is not published while shrinkwarp is included in published package - https://docs.npmjs.com/cli/v6/configuring-npm/shrinkwrap-json
