### ISSUE TITLE
If an import statement appears BEFORE certain Javascript statements, the import statements will be duplicated.

### ISSUE THREAD

**Issue by anthony-S93** [typescript-language-server/typescript-language-server#699]
Environment: 
```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3

typescript-language-server Version 3.3.0-1
```
I think this behavior can be best explained via the gif images attached below. 

1) If we add an import statement (using autocompletion) before a `console.log()` statement, for example, the import statement duplicates itself.
![duplicated_import_before_console](https://user-images.githubusercontent.com/69449791/222956414-34e5810a-715d-4942-b525-645015a4a550.gif)

2) However, this doesn't happen if the import statement appears AFTER the `console.log()` call.
![no_duplicate_after_console](https://user-images.githubusercontent.com/69449791/222956453-ad770c37-3c70-4605-9474-e454a31c672c.gif)

3) Other types of statements aren't affected.
![no-duplicates-with-var](https://user-images.githubusercontent.com/69449791/223019173-1165dc53-bf3f-4b1d-8f3e-38926595e7f8.gif)

4) It gets weirder if I have a mix of `console.log()` calls and other statements. 
![duplicates_after_console_and_var_declare](https://user-images.githubusercontent.com/69449791/222956784-dda618ce-29b9-47fa-bf0a-1f9d9aa99ab1.gif)

5) The conditions in this example is similar to the one in (4), just that the import statement is placed after the `console.log()` calls. Again, no duplicates.
![no_duplicates](https://user-images.githubusercontent.com/69449791/222956852-231b9eee-b239-4777-adf0-42618f288e7e.gif)

6) Another example where it duplicates.
![duplicates_again](https://user-images.githubusercontent.com/69449791/222956971-9774f303-5518-4c74-8dae-bcb61fa95230.gif)

The only explanation I can think of is that when I try to type the identifier name in the import statement (`foobar` in this case), the completion engine thinks I'm trying to _**use**_ the variable `foobar` in an expression rather than trying to _import_ it. So the language server automatically adds another import statement while the completion engine completes my original import statement, which results in a duplicate. 

Note, however, that the duplicate doesn't appear if I add a `{` before the identifier name. As in: 
![with_curly_braces](https://user-images.githubusercontent.com/69449791/222957237-4562c847-1fec-4852-9b0d-be2ee8a0ed9d.gif)

This behavior is reproducible even on the following minimal neovim config: 
```lua
--minimal_init.lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
    require('packer').startup({
        function(use)
            use 'wbthomason/packer.nvim'
            use 'hrsh7th/nvim-cmp'
            use 'hrsh7th/cmp-nvim-lsp'
            use 'saadparwaiz1/cmp_luasnip'
            use 'L3MON4D3/LuaSnip'
            use "neovim/nvim-lspconfig"
        end,
        config = {
            package_root = package_root,
            compile_path = install_path .. '/plugin/packer_compiled.lua',
            display = { non_interactive = true },
        }
    })
end

_G.load_config = function()


    --Configure lsp
    local lspconfig = require("lspconfig")
    local opts = { noremap = true, silent = true }
    local cmp_nvim_lsp = require("cmp_nvim_lsp")
    local capabilities = cmp_nvim_lsp.default_capabilities()

    --Configure affected language servers
    lspconfig.tsserver.setup({
        capabilities = capabilities,
    })

    --Configure nvim-cmp
    local luasnip = require('luasnip')
    local cmp = require('cmp')
    cmp.setup({
        sources = cmp.config.sources(
            {
                { name = 'nvim_lsp' },
                { name = 'luasnip' },
            },
            {
                { name = 'buffer' }
            }
        ),
        snippet = {
            expand = function(args)
                luasnip.lsp_expand(args.body)
            end,
        },
        mapping = cmp.mapping.preset.insert({
            ['<C-d>'] = cmp.mapping.scroll_docs( -4),
            ['<C-f>'] = cmp.mapping.scroll_docs(4),
            ['<C-Space>'] = cmp.mapping.complete(),
            ['<CR>'] = cmp.mapping.confirm {
                behavior = cmp.ConfirmBehavior.Replace,
                select = true,
            },
            ['<Tab>'] = cmp.mapping(function(fallback)
                if cmp.visible() then
                    cmp.select_next_item()
                elseif luasnip.expand_or_jumpable() then
                    luasnip.expand_or_jump()
                else
                    fallback()
                end
            end, { 'i', 's' }),
            ['<S-Tab>'] = cmp.mapping(function(fallback)
                if cmp.visible() then
                    cmp.select_prev_item()
                elseif luasnip.jumpable( -1) then
                    luasnip.jump( -1)
                else
                    fallback()
                end
            end, { 'i', 's' })
        }),
    })
    
end

if vim.fn.isdirectory(install_path) == 0 then
    print("Installing nvim-autopairs and dependencies.")
    vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end

load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]


```

**Comment by rchl** [comment]
Are you able to check whether it reproduces in VSCode?

Are you able to reproduce in vmim in this project itself?

Are you able to provide specific project that reproduces?

I'm not able to reproduce so it could be an editor, configuration, server or typescript issue. Can't tell without being able to reproduce.

**Comment by rchl** [comment]
Closing due to no response but I'm assuming this is a client problem anyway.

If you can provide LSP logs then that would make it clear.
