### ISSUE TITLE
workspace/symbol results in error: "No project"

### ISSUE THREAD

**Issue by bartoszkrawczyk2** [typescript-language-server/typescript-language-server#705]
Hi,

I'm trying to implement `typescript-language-server` in my project.

Initialization call is successfull, however when I call `workspace/symbol` I get an error:

```
ResponseError: Request workspace/symbol failed with message: <syntax> TypeScript Server Error (4.9.5)
No Project.
Error: No Project.
```

When I use `workspaceFolders` instead of `rootUri` in my `initialize` I don't get any error, but the response is just `[]`.

I am new to implementing LSP so I would appreciate any help.

**Comment by bartoszkrawczyk2** [comment]
Thanks @rchl . Does it need to be a specific file (tsconfig?), or any `.ts` file? `workspace/symbol` will resolve all symbols, or just for opened files?

**Comment by bartoszkrawczyk2** [comment]
Thanks @rchl , using `didOpenTextDocument` and waiting a bit did solve my issue!

**Comment by mikemonteith** [comment]
Isn't the point of `workspace/symbol` that it finds all symbols in the entire workspace?

> The workspace symbol request is sent from the client to the server to list project-wide symbols matching the query string.
> -- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_symbol

E.g. a user knows that somewhere there is a symbol called `MyClass` but they don't know which file it's in, and they want to find it.
If we only search for symbols in files that are open, this feature is redundant.
Am I misunderstanding something here?

**Comment by rchl** [comment]
It does work across the project.

I suspect that it's only necessary for the project to load (there is an according event for that) and not to open any file but I haven't tried the programmatic case. Normally in an editor you first open a file before you can interact with the server.

**Comment by mikemonteith** [comment]
I'll try to create a reproducible example because this isn't working for me - but it could be that I'm doing something wrong.
My code will only find symbols for files which are open.

**Comment by rchl** [comment]
You could always try if it works in a editor (neovim, sublime text) with relevant plugin/extension. If it works in a editor (which I'm confident that it does) then it could be an issue with how you use it.

**Comment by rchl** [comment]
BTW. Whether the project has loaded you can only know through the progress event that has status text `Initializing JS/TS language features…`. Once this progress event is ended, the project should be loaded.
