### ISSUE TITLE
Support .eslintrc config

### ISSUE THREAD

**Issue by msdrigg** [typescript-language-server/typescript-language-server#708]
I have a .eslintrc.cjs config file for eslint to support the next.js plugin. Eslint works as expected when I run `npm run lint`, but when I use zed.dev integrated with typescript-language-server, I don't see these diagnostics. 

I am specifically interested in the react-hooks diagnostics. 

If you suspect that this is a zed.dev problem rather than a typescript-language-server problem, please let me know how I can validate that this problem is caused by typescript-language-server

**Comment by rchl** [comment]
This server has nothing to do with eslint. It doesn't integrate with it

There might exist typescript plugins that run eslint but it's out of scope of this server if Zed is using those. I would anyway recommend running a separate LSP server for eslint.

**Comment by msdrigg** [comment]
Oof—I am sorry for the confusion here.

I got the idea that eslint was integrated from this issue. https://github.com/typescript-language-server/typescript-language-server/issues/159

Seeing your response, I see the confusion around internal use of eslint vs integration of eslint. Sorry for the confusion. Thanks for the quick response :)

**Comment by msdrigg** [comment]
Oof—I am sorry for the confusion here.

I got the idea that eslint was integrated from this issue. https://github.com/typescript-language-server/typescript-language-server/issues/159

Seeing your response, I see the confusion around internal use of eslint vs integration of eslint. Sorry for the confusion. Thanks for the quick response :)
