### ISSUE TITLE
An extra period is inserted with any completion item when using Neovim's omni completion

### ISSUE THREAD

**Issue by heygarrett** [typescript-language-server/typescript-language-server#711]
I'm not able to reproduce this issue with any other language server.

Triggering omni completion after a `.` and then selecting a completion item from the pop-up menu inserts an extra `.`:
![CleanShot 2023-03-27 at 23 34 31](https://user-images.githubusercontent.com/1154912/228121313-c362acc3-5a3a-4c10-a010-5d5e83c4567b.gif)

```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info

```

Minimal config:

```lua
vim.opt.completeopt = { "menuone", "noselect" }
vim.keymap.set("i", "<c-space>", "<c-x><c-o>")

local pattern = "typescript"
local cmd = { "typescript-language-server", "--stdio" }
local root_markers = { ".git", ".editorconfig", "package.json" }
local settings = vim.empty_dict()

vim.api.nvim_create_autocmd("FileType", {
	pattern = pattern,
	callback = function(args)
		local match = vim.fs.find(root_markers, { path = args.file, upward = true })[1]
		local root_dir = match and vim.fn.fnamemodify(match, ":p:h") or nil
		vim.lsp.start({
			name = "bugged-ls",
			cmd = cmd,
			root_dir = root_dir,
			settings = settings,
		})
	end,
})
```

**Comment by rchl** [comment]
It works in here.
You'd probably have to ask in neovim community as I don't know how to use and debug it. Make sure that you are using recent version of this server and typescript also.

**Comment by Vizualni** [comment]
Same thing is happening to me

**Comment by Vizualni** [comment]
Hey @rchl . I can confirm that this started happening on version 3.3.0 (`npm i -g typescript-language-server@3.3.0 typescript`). I did a binary search starting from version 2.0.0 until I found the first version this started to occur and that's 3.3.0.  @heygarrett  fix for this is to install 3.2.0 which is the last version where it works as expected: `npm i -g typescript-language-server@3.2.0 typescript`

**Comment by Vizualni** [comment]
@rchl you are right. It works just fine on version 3.3.1 if I enable `completionDisableFilterText` option. Thanks!

**Comment by heygarrett** [comment]
@rchl Yup, that works. Thank you!
