### ISSUE TITLE
"typescript.inlayHints.includeInlayParameterNameHints": "all" breaks inference with dangling commas

### ISSUE THREAD

**Issue by Klaster1** [typescript-language-server/typescript-language-server#724]
How to reproduce:
1. Install TypeScript 4.8.4 as a project dependency.
2. Enable set "typescript.inlayHints.includeInlayParameterNameHints" to "all".
3. Checks the inferred type for `nums`:
```typescript
class Bad {
	nums = combineLatest([of(1), of(2), of(3)]).pipe(
		map(([a, b, c]) => a + b + c), // <- trailing comma
	)
}
```

Reproducer: [tslangserver-report.zip](https://github.com/typescript-language-server/typescript-language-server/files/11474427/tslangserver-report.zip).

Expected:
The type is inferred as `Observable<number>`.

Observed:
`nums` infers to `Observable<unknown>`.

Notes:
I'm using the service via the https://github.com/sublimelsp/LSP-typescript in Sublime Text 4. Disabling the setting or removing the comma fixes the inference. VSCode with language server version set to 4.8.4 infers everything correctly. This is mildly annoying as Prettier adds dangling commas by default and I can't change the project TS version yet. I can point the server to use TS 5, but I figured the bug's worth reporting anyway,

**Comment by rchl** [comment]
I see the same for both cases.

![Screenshot 2023-05-15 at 09 21 32](https://github.com/typescript-language-server/typescript-language-server/assets/153197/a4d41d6e-d870-48fc-8bc3-2148fa1cd93e)

Also same in VSCode.
Is there something to your setup that makes it reproducible?

**Comment by Klaster1** [comment]
Perhaps I should have structered the example better, my bad. Try this:
```
const bad = new Bad()
const nums: Observable<number> = bad.nums
```
My results:
![image](https://github.com/typescript-language-server/typescript-language-server/assets/2667662/e41eeb6a-caee-4b27-bd9b-2a7f0d890f5f)
![image](https://github.com/typescript-language-server/typescript-language-server/assets/2667662/9c1d61ca-b265-4cf3-8a7b-1fdc11ac62d8)

**Comment by rchl** [comment]
Please provide here the output of `LSP: Troubleshoot server` command. You are setting a bunch of extra settings that you haven't mentioned and I don't want to figure out what to set from the screenshot.

Also you are using TS plugins which is another variable. Have you tried if this reproduces with a minimal user overrides?

**Comment by Klaster1** [comment]
The same happens when only setting the `"includeInlayParameterNameHints": "all"`:
```json
{
	"settings": {
		"typescript.inlayHints.includeInlayParameterNameHints": "all", // none | literals | all
	}
}
```
<details><summary>Troubleshoot output</summary
```
# Troubleshooting: LSP-typescript
## Version
 - LSP: 1.23.0
 - Sublime Text: 4143
## Server Test Run
 - exit code: 0
 - output
```

```
## Server Configuration
 - command
```json
[
  "${node_bin}", 
  "${server_path}", 
  "--stdio"
]
```
 - shell command
```sh
"C:\Program Files\nodejs\node.EXE" "C:\Users\Klaster_1\AppData\Local\Sublime Text 3\Package Storage\LSP-typescript\18.15.0\typescript-language-server\node_modules\typescript-language-server\lib\cli.mjs" --stdio
```
 - selector
```
source.js, source.jsx, source.ts, source.tsx
```
 - priority_selector
```
source.js, source.jsx, source.ts, source.tsx
```
 - init_options
```json
{
  "completionDisableFilterText": true, 
  "disableAutomaticTypingAcquisition": false, 
  "locale": "en", 
  "maxTsServerMemory": 0, 
  "npmLocation": "", 
  "plugins": [], 
  "preferences": {
    "allowIncompleteCompletions": true, 
    "allowRenameOfImportPath": true, 
    "allowTextChangesInNewFiles": true, 
    "autoImportFileExcludePatterns": [], 
    "disableSuggestions": false, 
    "displayPartsForJSDoc": true, 
    "generateReturnInDocTemplate": true, 
    "importModuleSpecifierEnding": "auto", 
    "importModuleSpecifierPreference": "shortest", 
    "includeAutomaticOptionalChainCompletions": true, 
    "includeCompletionsForImportStatements": true, 
    "includeCompletionsForModuleExports": true, 
    "includeCompletionsWithClassMemberSnippets": true, 
    "includeCompletionsWithInsertText": true, 
    "includeCompletionsWithObjectLiteralMethodSnippets": true, 
    "includeCompletionsWithSnippetText": true, 
    "includePackageJsonAutoImports": "auto", 
    "jsxAttributeCompletionStyle": "auto", 
    "lazyConfiguredProjectsFromExternalProject": false, 
    "organizeImportsAccentCollation": true, 
    "organizeImportsCaseFirst": false, 
    "organizeImportsCollation": "ordinal", 
    "organizeImportsCollationLocale": "en", 
    "organizeImportsIgnoreCase": "auto", 
    "organizeImportsNumericCollation": false, 
    "providePrefixAndSuffixTextForRename": true, 
    "provideRefactorNotApplicableReason": true, 
    "quotePreference": "auto", 
    "useLabelDetailsInCompletionEntries": true
  }, 
  "tsserver": {
    "logDirectory": "", 
    "logVerbosity": "off", 
    "path": "", 
    "trace": "off", 
    "useSyntaxServer": "auto"
  }
}
```
 - settings
```json
{
  "diagnostics": {
    "ignoredCodes": []
  }, 
  "implicitProjectConfiguration": {
    "checkJs": false, 
    "experimentalDecorators": false, 
    "module": "ESNext", 
    "strictFunctionTypes": true, 
    "strictNullChecks": true, 
    "target": "ES2020"
  }, 
  "javascript": {
    "format": {
      "insertSpaceAfterCommaDelimiter": true, 
      "insertSpaceAfterConstructor": false, 
      "insertSpaceAfterFunctionKeywordForAnonymousFunctions": true, 
      "insertSpaceAfterKeywordsInControlFlowStatements": true, 
      "insertSpaceAfterOpeningAndBeforeClosingEmptyBraces": false, 
      "insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false, 
      "insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": true, 
      "insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false, 
      "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false, 
      "insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false, 
      "insertSpaceAfterSemicolonInForStatements": true, 
      "insertSpaceAfterTypeAssertion": false, 
      "insertSpaceBeforeAndAfterBinaryOperators": true, 
      "insertSpaceBeforeFunctionParenthesis": false, 
      "insertSpaceBeforeTypeAnnotation": false, 
      "placeOpenBraceOnNewLineForControlBlocks": false, 
      "placeOpenBraceOnNewLineForFunctions": false, 
      "semicolons": "ignore", 
      "trimTrailingWhitespace": true
    }, 
    "inlayHints": {
      "includeInlayEnumMemberValueHints": false, 
      "includeInlayFunctionLikeReturnTypeHints": false, 
      "includeInlayFunctionParameterTypeHints": false, 
      "includeInlayParameterNameHints": "none", 
      "includeInlayParameterNameHintsWhenArgumentMatchesName": false, 
      "includeInlayPropertyDeclarationTypeHints": false, 
      "includeInlayVariableTypeHints": false, 
      "includeInlayVariableTypeHintsWhenTypeMatchesName": false
    }
  }, 
  "statusText": "$version, $source", 
  "typescript": {
    "format": {
      "insertSpaceAfterCommaDelimiter": true, 
      "insertSpaceAfterConstructor": false, 
      "insertSpaceAfterFunctionKeywordForAnonymousFunctions": true, 
      "insertSpaceAfterKeywordsInControlFlowStatements": true, 
      "insertSpaceAfterOpeningAndBeforeClosingEmptyBraces": false, 
      "insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false, 
      "insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": true, 
      "insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false, 
      "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false, 
      "insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false, 
      "insertSpaceAfterSemicolonInForStatements": true, 
      "insertSpaceAfterTypeAssertion": false, 
      "insertSpaceBeforeAndAfterBinaryOperators": true, 
      "insertSpaceBeforeFunctionParenthesis": false, 
      "insertSpaceBeforeTypeAnnotation": false, 
      "placeOpenBraceOnNewLineForControlBlocks": false, 
      "placeOpenBraceOnNewLineForFunctions": false, 
      "semicolons": "ignore", 
      "trimTrailingWhitespace": true
    }, 
    "inlayHints": {
      "includeInlayEnumMemberValueHints": false, 
      "includeInlayFunctionLikeReturnTypeHints": false, 
      "includeInlayFunctionParameterTypeHints": false, 
      "includeInlayParameterNameHints": "all", 
      "includeInlayParameterNameHintsWhenArgumentMatchesName": false, 
      "includeInlayPropertyDeclarationTypeHints": false, 
      "includeInlayVariableTypeHints": false, 
      "includeInlayVariableTypeHintsWhenTypeMatchesName": false
    }
  }
}
```
 - env
```json
{
  "PATH": "C:\\Program Files\\nodejs;C:\\Program Files\\nodejs;"
}
```

## Active view
 - File name
```
C:\dev\ggstuff\typescript-language-server-754\index.ts
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": true, 
  "syntax": "Packages/JavaScript/TypeScript.sublime-syntax"
}
```
 - base scope
```
source.ts
```

## Project / Workspace
 - folders
```json
[
  "C:\\dev\\ggstuff\\typescript-language-server-754"
]
```
 - is project: True
 - project data:
```json
{
  "folders": [
    {
      "path": "."
    }
  ]
}
```

## LSP configuration

```json
{
  "completion_insert_mode": "insert", 
  "document_highlight_style": "background", 
  "hover_highlight_style": "background", 
  "inhibit_snippet_completions": true, 
  "inhibit_word_completions": true, 
  "log_debug": true, 
  "lsp_code_actions_on_save": {
    "source.organizeImports": false
  }, 
  "lsp_format_on_save": false, 
  "semantic_highlighting": false, 
  "show_code_lens": "phantom", 
  "show_inlay_hints": true, 
  "show_references_in_quick_panel": true
}
```
## System PATH
 - C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin
 - C:\Program Files (x86)\Common Files\Oracle\Java\javapath
 - C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot\bin
 - C:\Python38\Scripts\
 - C:\Python38\
 - C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live
 - C:\Program Files (x86)\Intel\iCLS Client\
 - C:\Program Files\Intel\iCLS Client\
 - C:\Program Files (x86)\AMD APP\bin\x86_64
 - C:\Program Files (x86)\AMD APP\bin\x86
 - C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static
 - c:\Program Files\7-Zip\
 - c:\Program Files\OpenSSL-Win64\bin\
 - C:\Program Files (x86)\PuTTY\
 - c:\Program Files (x86)\Java\jre7\bin\
 - C:\Program Files\cURL\bin
 - c:\Program Files (x86)\GnuWin32\bin\
 - c:\Program Files\GraphicsMagick-1.3.19-Q8\
 - c:\mongo\bin\
 - C:\Program Files (x86)\Heroku\bin
 - C:\Program Files (x86)\git\cmd
 - C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
 - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
 - C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
 - C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
 - C:\Program Files (x86)\AMD\ATI.ACE\Core-Static
 - c:\Program Files\Sublime Text 3\
 - c:\Program Files\ConEmu\
 - C:\WINDOWS\system32
 - C:\WINDOWS
 - C:\WINDOWS\System32\Wbem
 - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
 - C:\WINDOWS\system32
 - C:\WINDOWS
 - C:\WINDOWS\System32\Wbem
 - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
 - C:\WINDOWS\System32\OpenSSH\
 - C:\ProgramData\chocolatey\bin
 - C:\Program Files\dotnet\
 - C:\Program Files\Git\cmd
 - C:\Program Files\Git\mingw64\bin
 - C:\Program Files\Git\usr\bin
 - C:\Program Files\WireGuard\
 - C:\Program Files\Docker\Docker\resources\bin
 - C:\Program Files\nodejs\
 - C:\Program Files\PowerShell\7\
 - C:\Users\Klaster_1\AppData\Local\Programs\Python\Python310\Scripts\
 - C:\Users\Klaster_1\AppData\Local\Programs\Python\Python310\
 - C:\Users\Klaster_1\scoop\shims
 - C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live
 - C:\Windows\System32
 - c:\Program Files\FFmpeg\bin\
 - c:\Program Files\cURL\bin\
 - C:\Program Files\Git\bin\
 - c:\Users\Klaster_1\AppData\Local\Android\android-sdk\platform-tools\
 - C:\Users\Klaster_1\AppData\Local\Microsoft\WindowsApps
 - C:\Users\Klaster_1\AppData\Local\Programs\oh-my-posh\bin
 - c:\Program Files\mvn\bin\
 - C:\Users\Klaster_1\AppData\Local\Microsoft\WinGet\Links
 - c:\Program Files (x86)\ClockworkMod\Universal Adb Driver\
 - c:\Users\Klaster_1\Downloads\gradle-8.0-bin\gradle-8.0\bin\
 - C:\Users\Klaster_1\AppData\Roaming\npm
 - C:\Users\Klaster_1\AppData\Local\Programs\Microsoft VS Code\bin
 - C:\Users\Klaster_1\AppData\Local\Microsoft\WindowsApps
 - 
```
</details>

**Comment by Klaster1** [comment]
Wait, but your screenshot reproduces the issue precisely. Was it made on Windows?

**Comment by rchl** [comment]
Oh. :)

That was mac but I see now why it wasn't reproducing before. It doesn't reproduce when `semantic_highlighting` is enabled.

If you set:

```
"editor.semanticHighlighting.enabled": false
```

in VSCode then it will also reproduce there.

It also doesn't reproduce in any case with TS 5.0.4 (for example) so I think this needs to be treated as a TypeScript bug that is already fixed and not an issue specific to this server.
