### ISSUE TITLE
Suggesti using pre-push instead of pre-commit

### ISSUE THREAD

**Issue by predragnikolic** [typescript-language-server/typescript-language-server#734]
I would suggest this change:

```diff
-      "pre-commit": "yarn lint && yarn test && yarn 
+      "pre-push": "yarn lint && yarn test && yarn build",
```

For someone who commits frequently, 
doing these steps on each commit, really takes a long time.

Do you think that it would be better if those steps took place only on pre-push?

That way, committing will be fast, but pushing will be slower.
IMO, that is better than committing to be slow.

**Comment by rchl** [comment]
The ideal situation in any project is when every commit works. If there are 3 commits for example, and an error is only shown on pushing, then the first 2 commits might be completely broken and that would not be caught.

Of course, if those commits would go through a PR then they would likely be squashed anyway (at least in this project) so it wouldn't really matter if some were originally broken.

But in general it's not that obvious which option is better. There are pros and cons to everything.

**Comment by predragnikolic** [comment]
> There are pros and cons to everything.

True,
thanks for sharing your opinion, didn't really think about this case:

> If there are 3 commits for example, and an error is only shown on pushing, then the first 2 commits might be completely broken and that would not be caught.

Well, it is not really a big of a deal. 
Maybe I would combine the two:
```
      "pre-push": "yarn test" 
      "pre-commit": "yarn lint && yarn build",
```

or
```
      "pre-push": "yarn test && yarn build" 
      "pre-commit": "yarn lint",
```

Just to make the commit part a bit faster.

Or keep it as is. :) 

I will close this, as it is not really an issue
