### ISSUE TITLE
[Question] Is semantic highlighting for import statements supported?

### ISSUE THREAD

**Issue by anthony-S93** [typescript-language-server/typescript-language-server#736]
Semantic tokens are not applied in import statements by default in Neovim, so I was wondering if there's a way enable it. In VSCode, this can probably be done via the `editor.tokenColorCustomizations` option, though I can't seem to find an equivalent in Neovim.

**Comment by rchl** [comment]
Typescript doesn't provide semantic tokens for import statements so nothing we can do.

(`ditor.tokenColorCustomizations` in VSCode will likely not help as it will be based on static syntax highlighting and not semantic tokens).
