### ISSUE TITLE
Do not send paddingLeft = true for type parameters' hints

### ISSUE THREAD

**Issue by SomeoneToIgnore** [typescript-language-server/typescript-language-server#738]
With the variable type hints enabled in the server settings

```json
"includeInlayVariableTypeHints": true,
```

and an expression

```typescript
let foo = false;
```

I get the following inlay hints from the latest server:

```json
[{"position":{"line":0,"character":8},"label":": boolean","kind":1,"paddingLeft":true}]
```

and with the specification (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlayHint) defined as 

```
/**
 * Render padding before the hint.
 *
 * Note: Padding should use the editor's background color, not the
 * background color of the hint itself. That means padding can be used
 * to visually align/separate an inlay hint.
 */
paddingLeft?: boolean;
```

in the editor, we'll have to render the hint as 

```typescript
let foo : boolean = false;
```

with the padding between `foo` and `: boolean` hint's label.

This is not a conventional TypeScript formatting: https://www.typescriptlang.org/docs/handbook/basic-types.html
shows examples of a regular type ascription

```typescript
let foo: boolean = false;
```

and the formatter would also format the unconventional form to the conventional one.

Should the language server require no padding for such cases instead? 
If not, how editors should render such hints?

**Comment by rchl** [comment]
This data comes from TypeScript itself and the server doesn't augment it in any way. You should report this issue in the TypeScript repo.

And it should also reproduce in VSCode. It might be good to mention that in their issue, if so.

**Comment by SomeoneToIgnore** [comment]
Can you elaborate what `typescript` means in this context? The language itself cannot really send anything to the server?
Do you mean that you use another library to parse the text and get the result with the padding? I would love to get a code pointer to there, if you have one.

**Comment by SomeoneToIgnore** [comment]
VSCode renders it according to the specification, also awkwardly:

![image](https://github.com/typescript-language-server/typescript-language-server/assets/2690773/6ff81c1c-adf8-4674-ba36-5b7ab0558ef2)

but it's an editor that conforms LSP protocol, so I don't see issues with their rendering.
So it's an LSP server that has to be sending the wrong data.

**Comment by rchl** [comment]
The TypeScript package (https://github.com/microsoft/TypeScript) itself is the one that provides bulk of the functionality provided by this server. What this server does is  it exposes a LSP-compatible API.

**Comment by rchl** [comment]
> but it's an editor that conforms LSP protocol, so I don't see issues with their rendering.

Typescript functionality in VSCode actually doesn't have much to do with LSP. They communicate directly through the TypeScript API in that case.

As for handling the padding, it might be just ignoring that parameter and always rendering without extra padding...

**Comment by SomeoneToIgnore** [comment]
Thank you a lot for the pointers.

**Comment by rchl** [comment]
For reference, the response VSCode receives in this case:
```
{"seq":0,"type":"response","command":"provideInlayHints","request_seq":11,"success":true,"body":[{"text":": boolean","position":{"line":1,"offset":8},"kind":"Type","whitespaceBefore":true}]}
```
So yes, `whitespaceBefore` is also set in their case. How their UI renders it is another matter.
