### ISSUE TITLE
Support custom typescript path?

### ISSUE THREAD

**Issue by ShiChenCong** [typescript-language-server/typescript-language-server#743]
Can support custom TypeScript paths? For example, sometimes I want to use a global TypeScript instead of the one inside the node_modules folder.

**Comment by ShiChenCong** [comment]
Works, Thank you

**Comment by dmeij** [comment]
Hi, the link isn't working anymore. Could you please provide an example?

**Comment by rchl** [comment]
https://github.com/typescript-language-server/typescript-language-server/blob/master/docs/configuration.md#initializationoptions

**Comment by Lilja-at-funnel** [comment]
I'm trying to debug `tsserver` with a custom path. Can I also run `--enable-source-maps` somehow?
