### ISSUE TITLE
EPERM: operation not permitted Cannot Move/Rename Files & Directories when Language Server is Running. 

### ISSUE THREAD

**Issue by realdevelogic** [typescript-language-server/typescript-language-server#744]
## Error: EPERM: operation not permitted, rename 'path a' -> 'path b'
I am uncertain whether this is the right place to post the issue, but When I kill the ts-js language server process on VS Code, the moving/rename operation succeeds instantly, however when the ts-js language server is enabled, the loading indicator is shown for ~30 seconds and then the operation fails.
I kill the language server process using the Windows Power Toys locksmith, in the locked files section, I see all the directories of the workspace, hopefully it means the language server is using and, in this case, also locking all the files/folders in my project.

## Context:
Project Language: Typescript/Javascript
Node.JS Version: v16.13.0 (using nvm)
Code Editor: VS Code
OS: Windows 10 22H2 Build 19045
Terminal: CMD

**Comment by rchl** [comment]
This server is not used by VSCode. You should report your issue in VSCode repo.
