### ISSUE TITLE
Syntax highlighting issue when generic input spans multiple lines

### ISSUE THREAD

**Issue by sachaw** [typescript-language-server/typescript-language-server#746]
Take the two following snippets:
```ts
getUsers: UnaryImpl<GetUsersRequest, GetUsersResponse> = async (req, ctx) => {
```
and 
```ts
getAuthenticator: UnaryImpl<
    GetAuthenticatorRequest,
    GetAuthenticatorResponse
  > = async (req, ctx) => {
```

The first snippet formatted to occupy one line correctly colours the property name.
The second however does not.

![image](https://github.com/typescript-language-server/typescript-language-server/assets/11172820/c8d713f7-0e1a-4a0b-aab2-d0a17acdfc10)

This issue only occurs when a generic input spans multiple lines

**Comment by rchl** [comment]
How does the more complete code look like. Those methods need to be inside and object literal or something, to be valid.

In any case, it's likely an issue with syntax highlighting provided by the editor you are using and not with this server.

If your editor supports LSP semantic highlighting then server might even improve editor's highlighting in this case but I'm not sure your editor supports it.

**Comment by sachaw** [comment]
Thanks for the reply,
this code is sitting inside a class:
```ts
export class Model
  extends BaseService<string>
  implements ServiceImpl<typeof ModelService>
```
My editor is VSCode 1.81.1. If this is not the correct place please let me know and I'll re-file it elsewhere, thanks.

**Comment by rchl** [comment]
You should report this in the VSCode repo.
