### ISSUE TITLE
Add support for `jsx` and `tsx` for setting preferences via `workspace/didChangeConfiguration`

### ISSUE THREAD

**Issue by rosingrind** [typescript-language-server/typescript-language-server#749]
I'm trying to set up formatting options for `typescript-language-server` via [`kak-lsp`](https://github.com/kak-lsp/kak-lsp), and I'm stuck with a problem:

- setting up my lsp client requires languageId to be `tsx` for .tsx files
- this leads to diffs when matching `typescript` in the config key (such as `typescript.format.semicolons = "insert"`)

If options mentioned in the following part of docs could support `typescript` along with `tsx` (same for `javascript`), it will be easier for lsp clients to support these without hacky workarounds:

https://github.com/typescript-language-server/typescript-language-server/blob/9f3e578792161095aab0eccb4c3e394dd9a4e697/README.md?plain=1#L318-L320

See https://github.com/kak-lsp/kak-lsp/issues/693#issuecomment-1701776617 for more info about the languageId and config key matching problem

**Comment by rchl** [comment]
I'll post a comment in the linked kak issue because this seems like a client issue.
