### ISSUE TITLE
Rename Symbol F2 with "pure keyof" is not possible - but it is possible if "wrapped as calculated property"

### ISSUE THREAD

**Issue by qwertysk** [typescript-language-server/typescript-language-server#767]
**I think this could be related to typescript-language-server, even I reported it also here** https://github.com/microsoft/TypeScript/issues/56052

### 🔎 Search Terms

Rename symbol, keyof

### 🕗 Version & Regression Information

- This is the behavior in every version I tried

### ⏯ Playground Link

https://tsplay.dev/N7QgPW

### 💻 Code

```ts
////////////////////////// CASE 1 - keyof to computed property /////////////////////////

declare const Att_1: "Att 1"

interface Case_1 {
  [Att_1]: string
}

declare const fnc_1: <K extends keyof Case_1>(p: K) => void

fnc_1("Att 1")
//     ^_ Rename Symbol F2 => SUCCESS



////////////////////////// CASE 2 - pure keyof //////////////////////////

interface Case_2 {
  "Att 2": string // here is the difference, pls compare to Case_1
}

declare const fnc_2: <K extends keyof Case_2>(p: K) => void

fnc_2("Att 2")
//     ^_ Rename Symbol F2 => FAIL
```

### 🙁 Actual behavior

![image](https://github.com/microsoft/TypeScript/assets/45438489/9cc37b11-52fb-41e8-8fc2-f445108ac29a)

It is wrong because `Att 2`  in `interface Case_2` is not renamed 

### 🙂 Expected behavior

I expect `Att 2` in `interface Case_2` to be successfully renamed to `Attribute 2`

### Additional information about the issue

Even it is not "a bug but the feature", is there best practice - if reliable renaming is really frequent and important in my project ?

**PLS HELP ME ❤️❤️❤️ ... because manually create tons of constants for all project interfaces and all attributes - this is not maintanable way - any other ideas/patterns please ?**

**Comment by rchl** [comment]
I think an issue in Typescript is enough since the logic for renaming is all there.
