### ISSUE TITLE
SyntaxError when running typescript-language-server --stdio

### ISSUE THREAD

**Issue by dneial** [typescript-language-server/typescript-language-server#770]
i get a SyntaxError: Unexpected token '.' when running the server manually

**Comment by rchl** [comment]
What exactly are you doing. How have you installed it and what command are you using to start it. Provide more details.

**Comment by dneial** [comment]
Sorry, I did a little bit of research and this was a node version problem. Node version should be at least 14 and I had v12

**Comment by rchl** [comment]
Not that for the latest version that was released free days ago you'll need node 18.
