### ISSUE TITLE
[Question] Why aren't certain standard built-in objects recognized by the language server?

### ISSUE THREAD

**Issue by anthony-S93** [typescript-language-server/typescript-language-server#812]
I noticed that the language server doesn't recognize certain [build-in objects ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects). By "recognize" I mean provide autocompletions, semantic tokens, etc. 

Take `Function` vs `Symbol`, for instance.  The language server recognizes the former but not the latter. 

https://github.com/typescript-language-server/typescript-language-server/assets/69449791/3f4dba6f-52fa-4955-87d3-72f1d9f2d60a

Is this by design?

**Comment by rchl** [comment]
It's decided in your `tsconfig.json` which features of the environment are enabled. Stuff like `compilerOptions.target` and `compilerOptions.lib`. Refer to https://www.typescriptlang.org/tsconfig
