### ISSUE TITLE
Error while importing `type`  and without types  

### ISSUE THREAD

**Issue by anoopd** [typescript-language-server/typescript-language-server#821]
https://asciinema.org/a/5v5oDhCemiy85MEqSXWqgbP1z

expected result 

`import {json} from  "@remix-run/node";
 import type {LoaderFunctionArgs} from "@remix-run/node"`

actual result 
`import {json, type LoaderFunctionArgs} from  "@remix-run/node";`

**Comment by rchl** [comment]
You can report it in typescript repo since the logic for that is implement in Typescript. Try to verify that it also reproduces in VSCode first and make sure that you've tested with latest typescript version.
