### ISSUE TITLE
No semantic token assigned to import names, but available for export

### ISSUE THREAD

**Issue by OzelotVanilla** [typescript-language-server/typescript-language-server#842]
When export a name, there is semantic token assigned. Such as the `Compiler` is assigned with `class`.

![image](https://github.com/typescript-language-server/typescript-language-server/assets/59910575/4a3c69c2-02e9-4dfb-8664-94fb69e8535b)

For import, there seems to be no semantic token available.

![image](https://github.com/typescript-language-server/typescript-language-server/assets/59910575/f3c8211d-52cf-4b0e-9849-a1ff0d532873)

Note: Sorry that this issue might not be the issue of language server, but I believe this is not for textmate or the language itself, so I submit it here.

**Comment by rchl** [comment]
You are using VSCode so you should report this issue either in VSCode repo. Or potentially even directly in the Typescript repo.

Might have been already reported and there might be good reason why it works like that so maybe try to search for existing issues first.
