### ISSUE TITLE
Language server giving out large array of items when requesting completion 

### ISSUE THREAD

**Issue by SFX123456** [typescript-language-server/typescript-language-server#871]
Hello
i am trying to write a lsp client and i cant understand why the lsp server would send me suggestions with a content length of 177278 starting with {"jsonrpc":"2.0","id":1,"result":{"items":[{"label":"AbortController","kind":6,"sortText":"15","data":{"cacheId":1},"commitCharacters":[".",",","("]},{"
label":"AbortSignal","kind":6,"sortText":"15","data":{"cacheId":2},"commitCharacters":[".",",","("]},{"label":"abstract","kind":14,"sortText":"15","data
":{"cacheId":3}},{"label":"AbstractRange","kind":6,"sortText":"15","data":{"cacheId":4},"commitCharacters":[".",",","("]},{"label":"ActiveXObject","kind
":6,"sortText":"15","data":{"cacheId":5},"commitCharacters":[".",",","("]},{"label":"addEventListener","kind":3,"sortText":"15","data":{"cacheId":6},"co
mmitCharacters":[".",",","("]},{"label":"alert","kind":3,"sortText":"15","data":{"cacheId":7},"commitCharacters":[".",",","("]},{"label":"AnalyserNode",
"kind":6,"sortText":"15","data":{"cacheId":8},"commitCharacters":[".",",","("]},{"label":"Animation","kind":6,"sortText":"15","data":{"cacheId":9},"comm
itCharacters":[".",",","("]},{"label":"AnimationEffect","kind":6,"sortText":"15","data":{"cacheId":10},"commitCharacters":[".",",","("]},{"label":"Anima
tionEvent","kind":6,"sortText":"15","data":{"cacheId":11},"commitCharacters":[".",",","("]},{"label":"AnimationPlaybackEvent","kind":6,"sortText":"15","
data":{"cacheId":12},"commitCharacters":[".",",","("]},{"label":"AnimationTimeline","kind":6,"sortText":"15","data":{"cacheId":13},"commitCharacters":["
.",",","("]},{"label":"any","kind":14,"sortText":"15","data":{"cacheId":14}},{"label":"Array","kind":6,"sortText":"15","data":{"cacheId":15},"commitChar
acters":[".",",","("]},{"label":"ArrayBuffer","kind":6,"sortText":"15","data":{"cacheId":16},"commitCharacters":[".",",","("]},{"label":"as","kind":14,"
sortText":"15","data":{"cacheId":17}},{"label":"asserts","kind":14,"sortText":"15","data":{"cacheId":18}},{"label":"async","kind":14,"sortText":"15","da
ta":{"cacheId":19}},{"label":"atob","kind":3,"sortText":"15","data":{"cacheId":20},"commitCharacters":[".",",","("]},{"label":"Atomics","kind":6,"sortTe
xt":"15","data":{"cacheId":21},"commitCharacters":[".",",","("]},{"label":"Attr","kind":6,"sortText":"15","data":{"cacheId":22},"commitCharacters":[".",
",","("]},{"label":"Audio","kind":6,"sortText":"15","data":{"cacheId":23},"commitCharacters":[".",",","("]},{"label":"AudioBuffer","kind":6,"sortText":" i am sending the typescript lsp the following  textDocument: {uri :"file:///e%3A/fsd/test2/index.ts","languageId":"typescript","version":1,"text":"console."} . I think it should give me something like log or error but it gives me random suggestions and the ones i would expect are not there. I send a completion request textDocument : {
            uri:"file:///e%3A/fsd/test2/index.ts"
        },
        position : {
            line: 0,
            char: 8
        },
        context : {
            triggerKind: 2,
            triggerCharacter: "."
        } i tried every char number between 0 and 20 and also line 1. it prints an error with line 1 as theres no line 1 so i guess it gets the text. Mvg Nico

**Comment by rchl** [comment]
Can you format your question (logs) properly? Place the logs between blocks surrounded by triple backtick:

````
```
foo
```
````

Also you can enable `initializationOptions` -> `"tsserver.logVerbosity": "verbose"` and provide logs generated inside the `.logs` directory in the current working directory.

**Comment by SFX123456** [comment]
I am so sorry. I was so sure that i copied it exactly from another lsp client and i just had a typo. I spelled char instead of character in code completion request. The server used 0 then i guess and gave me all sorts of auto completion as normally with typescript lsp server. Thanks for the log suggestion although there isnt anything to be seen in the logs that would have pointed to it. I didnt understand how to activate logs before. Thanks
