### ISSUE TITLE
(bug) Closed document ownership not transferred back to the filesystem

### ISSUE THREAD

**Issue by bradymadden97** [typescript-language-server/typescript-language-server#879]
I am fairly certain this is a bug, but I would like to confirm my understanding. The expectation I have is not explicitly confirmed or denied in the LSP spec, which is why I'm not 100% sure it's a bug. Here's my expectation that this bug report relies upon:

**If a server sends `WorkspaceEdit`s for a file that is not currently open, the client can apply those changes to the file without notifying the server - i.e. not send `didChange` - and rely on the server to watch the filesystem for the changes.**

^^ If you disagree with this statement, or I have a misunderstanding of the spec, definitely let me know. If you agree with this, read on for the bug report:

## Scenario:

- We have three files:

**export.ts**
```typescript
export const a = 10;
```

**import1.ts**
```typescript
import { a } from './export';
```

**import2.ts**
```typescript
import { a } from './export';
```

- We open both `import1.ts` and `import2.ts` on the client, and send their initial contents to the langauge server.
- We then close `import1.ts` on the client, and send a `didClose` notification to the language server
- We prepare to rename `export.ts` and send a `workspace/willRename` request to the language server. The language server responds with the following `WorkspaceEdit`s:
```json
{
  "jsonrpc":"2.0",
  "id":"411457457",
  "result":{
    "changes":{
      "file:///home/runner/lsp-runner/src/import1.ts":[
        {"range":{"start":{"line":0,"character":19},"end":{"line":0,"character":27}},"newText":"./export2"}
      ],
      "file:///home/runner/lsp-runner/src/import2.ts":[
        {"range":{"start":{"line":0,"character":19},"end":{"line":0,"character":27}},"newText":"./export2"}
      ]
    }
  }
}
```

- We apply the changes to **both** files, so the new file contents look like this:
**import1.ts**
```typescript
import { a } from './export2';
```

**import2.ts**
```typescript
import { a } from './export2';
```

- Since only **import2.ts** is open on the client, we only send `didChange` and `didSave` notifications from the client to the server for **import2.ts** with the above change.
- We perform the rename of **export.ts** --> **export2.ts**

**export2.ts**
```typescript
export const a = 10;
```

- Now, we prepare to rename **export2.ts** _back_ to **export.ts**. We make a second `workspace/willRenameFiles` request to the language server. The langauge server responds with the following `WorkspaceEdit`s:

```json
{
  "jsonrpc":"2.0",
  "id":"1057243199",
  "result":{
    "changes":{
      "file:///home/runner/lsp-runner/src/import2.ts":[
        {"range":{"start":{"line":0,"character":19},"end":{"line":0,"character":28}},"newText":"./export"}
      ]
    }
  }
}
```

- **Notice**, it only gave us edits for **import2.ts** (the file that is open on the client), not **import1.ts** (the file that was opened and subsequently closed).
- You can find a runnable reproduction of the above scenario here https://replit.com/@bradyatreplit/lsp-runner#index.js

At this point it seems good enough to make a bug report, as the above `WorkspaceEdit` is not correct. However, I wanted to add a few more details that led me to believe the root cause specifically is surrounding closed document ownership.

## Further investigation

1. If you repeat the above scenario, but **do not** send `didOpen` and `didClose` events for **import1.ts** - i.e. the file was never opened on the client at all - you will get the correct `WorkspaceEdit` results for the second `willRenameFiles` request.
2. If you continue the original scenario, including sending a **third** `willRenameFiles` from **export.ts** to **export2.ts** (for a second time), you will see, once again, **import1.ts** is included in the list of `WorkspaceEdit`s. This, I assume, I because `typescript-language-server` still thinks it's open on the client and it's seen no changes since its original version.

## Attempts to reproduce elsewhere:

1. I downloaded my reproduction repl (above) and also ran it locally, and was able to reproduce the same results
2. I set up a similar directory structure on VSCode, which uses tsserver directly, and was unable to reproduce the results - VSCode correctly updated the imports for the closed file on every rename. (One caveat, a `tsconfig.json` in the workspace root was required for things to work - but we also have one here)

Thanks for bearing with me through the long bug report, please let me know if you have any questions!

**Comment by rchl** [comment]
Spec talks about ownership and that the editor has to send didOpen to take ownership of the document before it can change it:

- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didChange
- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didOpen

**Comment by bradymadden97** [comment]
I'm a bit confused. I've read those parts of the spec, but I don't know if it explains the inconsistent behavior that occurs when **import1.ts** has been open - and then closed - on the client vs. when it never has been opened on the client at all.

When it's never been opened at all, the imports get updated correctly. However when it's been opened and then closed, suddenly things do not work.

Are you saying that prior to running any `ApplyWorkspaceEdit`, the client must send `didOpen` (and then send a `didChange` explicitly as well). I'm struggling to understand how that would work for situations where a file on the filesystem has been edited programmatically, through any other means.

**Comment by predragnikolic** [comment]
> Are you saying that prior to running any ApplyWorkspaceEdit, the client must send didOpen (and then send a didChange explicitly as well).

That is the way I understood the spec.

If a file is closed
and a WorkspaceEdit exist comes in for the file,
the client would first need to open that file (that should send a didOpen notification)
and then apply the edits (that should send a didChange notification).

**Comment by rchl** [comment]
> Here's an example:

I've tried it here and it worked fine for me.

If you want me to have a look into it then please:
 - provide a repo that reproduces this simplified case
 - set `initializationOptions.tsserver.logVerbosity` to `verbose` and provide the tsserver log that is created in `.log` directory after reproducing the issue

**Comment by bradymadden97** [comment]
Interestingly I retried a minimal repro and was unable to repro the error - even when I _didn't_ reopen the closed file before editing it directly on the file system.

Here's the example test I wrote:
```typescript
import { spawn } from "child_process";
import { readFileSync } from "fs";
import { mkdir, rm, writeFile, rename } from "fs/promises";
import {
  DidChangeTextDocumentNotification,
  DidCloseTextDocumentNotification,
  DidOpenTextDocumentNotification,
  ExitNotification,
  InitializeRequest,
  InitializedNotification,
  ShutdownRequest,
  WillRenameFilesRequest,
  createMessageConnection,
  type MessageConnection,
} from "vscode-languageserver/node";

import { test, expect, beforeEach, assert } from "vitest";

let connection: MessageConnection;

beforeEach(async () => {
  await mkdir("example");

  return async () => {
    // Shutdown the server and exit
    await connection.sendRequest(ShutdownRequest.method, {});
    await connection.sendNotification(ExitNotification.method, {});
    await rm("example", { force: true, recursive: true });
  };
});

test("passes", async () => {
  // Start langauge server process
  const proc = spawn(
    "./node_modules/.bin/typescript-language-server",
    ["--stdio", "--log-level=4"],
    {
      stdio: ["pipe", "pipe", "pipe"],
    },
  );

  const defaultRootUri = `file://${process.cwd()}`;
  const defaultParams = {
    capabilities: {
      textDocument: {
        synchronization: { dynamicRegistration: true, didSave: true },
      },
      workspace: {
        applyEdit: true,
        fileOperations: { willRename: true },
        workspaceEdit: {
          documentChanges: true,
          resourceOperations: ["create", "delete", "rename"],
        },
      },
    },
    processId: process.pid,
    rootUri: defaultRootUri,
    workspaceFolders: [{ name: defaultRootUri, uri: defaultRootUri }],
  };

  // Set up message connection and begin listening
  connection = createMessageConnection(proc.stdout, proc.stdin);
  connection.listen();

  // Initialize language server
  await connection.sendRequest(InitializeRequest.method, defaultParams);
  await connection.sendNotification(InitializedNotification.method, {});

  // Create 3 files
  await writeFile("example/export.ts", `export const a = 10;`);
  await writeFile("example/import1.ts", `import { a } from './export';`);
  await writeFile("example/import2.ts", `import { a } from './export';`);

  // Open example/import2.ts
  await connection.sendNotification(DidOpenTextDocumentNotification.method, {
    textDocument: {
      uri: `file://${process.env.PWD}/example/import2.ts`,
      languageId: "typescript",
      text: `${readFileSync("example/import2.ts").toString()}`,
      version: 0,
    },
  });

  // Open example/import1.ts
  await connection.sendNotification(DidOpenTextDocumentNotification.method, {
    textDocument: {
      uri: `file://${process.env.PWD}/example/import1.ts`,
      languageId: "typescript",
      text: `${readFileSync("example/import1.ts").toString()}`,
      version: 0,
    },
  });

  // Close example/import1.ts
  await connection.sendNotification(DidCloseTextDocumentNotification.method, {
    textDocument: {
      uri: `file://${process.env.PWD}/example/import1.ts`,
    },
  });

  // Send will rename request number 1 (export.ts --> export2.ts);
  const willRenameResponse1 = await connection.sendRequest(
    WillRenameFilesRequest.type,
    {
      files: [
        {
          oldUri: `file://${process.env.PWD}/example/export.ts`,
          newUri: `file://${process.env.PWD}/example/export2.ts`,
        },
      ],
    },
  );

  // Assert that `will rename` sends back changes for both files
  assert(willRenameResponse1 !== null);
  expect(
    willRenameResponse1.changes?.[
      "file:///home/runner/workspace/example/import1.ts"
    ],
  ).toEqual([
    {
      range: {
        start: { line: 0, character: 19 },
        end: { line: 0, character: 27 },
      },
      newText: "./export2",
    },
  ]);
  expect(
    willRenameResponse1.changes?.[
      "file:///home/runner/workspace/example/import2.ts"
    ],
  ).toEqual([
    {
      range: {
        start: { line: 0, character: 19 },
        end: { line: 0, character: 27 },
      },
      newText: "./export2",
    },
  ]);

  // Write both files to match what the language server wants
  // Try an atomic write for import1.ts
  await writeFile("example/import1.ts~", `import { a } from './export2';`);
  await rename("example/import1.ts~", "example/import1.ts");
  await writeFile("example/import2.ts", `import { a } from './export2';`);

  // Send changes about the open file to the language server
  await connection.sendNotification(DidChangeTextDocumentNotification.method, {
    textDocument: {
      uri: `file://${process.env.PWD}/example/import2.ts`,
      version: 1,
    },
    contentChanges: [
      {
        range: {
          start: { line: 0, character: 19 },
          end: { line: 0, character: 27 },
        },
        text: "./export2",
      },
    ],
  });

  // Send will rename request number 1 (export2.ts --> export.ts);
  const willRenameResponse2 = await connection.sendRequest(
    WillRenameFilesRequest.type,
    {
      files: [
        {
          oldUri: `file://${process.env.PWD}/example/export2.ts`,
          newUri: `file://${process.env.PWD}/example/export.ts`,
        },
      ],
    },
  );

  // Assert that `will rename` sends back changes for both files
  // import1.ts should be watched by tsserver as it's "closed"
  // import2.ts was updated in memory by the change event as it's "open"
  assert(willRenameResponse2 !== null);
  expect(
    willRenameResponse2.changes?.[
      "file:///home/runner/workspace/example/import1.ts"
    ],
  ).toEqual([
    {
      range: {
        start: { line: 0, character: 19 },
        end: { line: 0, character: 28 },
      },
      newText: "./export",
    },
  ]);
  expect(
    willRenameResponse2.changes?.[
      "file:///home/runner/workspace/example/import2.ts"
    ],
  ).toEqual([
    {
      range: {
        start: { line: 0, character: 19 },
        end: { line: 0, character: 28 },
      },
      newText: "./export",
    },
  ]);
});
```

With the following `package.json`:
```json
{
  "name": "nodejs-typescript",
  "version": "1.0.0",
  "description": "",
  "type": "module",
  "scripts": {
    "test": "vitest run test.test.ts"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "node-fetch": "^3.3.1",
    "typescript": "^5.2.2",
    "typescript-language-server": "^4.3.3",
    "vitest": "^2.1.2",
    "vscode-languageserver": "^9.0.1"
  },
  "devDependencies": {
    "@types/node": "^20.10.0",
    "tsx": "^4.7.1"
  }
}
```
