### ISSUE TITLE
Deprecated property not marked as such

### ISSUE THREAD

**Issue by greg0ire** [typescript-language-server/typescript-language-server#891]
Consider the following piece of code:

```typescript
interface Hi {
    /** @deprecated */
    stopUsingMe?: string
}
export function foo(): Hi {
    return {
        stopUsingMe: "toto"
    }
}
```

I would expect a diagnosis letting me know that I shouldn't use `stopUsingMe` inside `foo()`, but that does not happen.
I'm using v4.3.3

Note that it works for other elements, for example if I deprecate a function, it's stricken through at every call site.

**Comment by rchl** [comment]
Diagnostics are provided by typescript/tsserver. You should ask about it in the [typescript](https://github.com/microsoft/TypeScript) repo instead.

**Comment by rchl** [comment]
This issue looks related: https://github.com/microsoft/TypeScript/issues/45657

**Comment by greg0ire** [comment]
It does look related! Thanks :pray:
