### ISSUE TITLE
typescript server error when using 'inlay hints' (Unexpected node.^M)

### ISSUE THREAD

**Issue by Antony-AXS** [typescript-language-server/typescript-language-server#895]
![image](https://github.com/typescript-language-server/typescript-language-server/assets/99483158/066b6a48-f3e9-4012-8906-2598a1098cb6)
line number 522 seems to be the reason for the error how can i resolve this issue ?
![image](https://github.com/typescript-language-server/typescript-language-server/assets/99483158/e3b11f8a-a3e2-4bc7-b435-f52e8fa2b731)

**Comment by rchl** [comment]
Probably report in typescript repo if it reproduces in VSCode (it should).

Also, provide a code instead of a screenshot in your report.
