### ISSUE TITLE
neovide GUI "env: node: No such file or directory

### ISSUE THREAD

**Issue by stark-jarvis** [typescript-language-server/typescript-language-server#908]
- MacOS 14.5
- neovim version：v0.10.0
- Plugins： lazy.nvim、mason.nvim、mason-lspconfig.nvim、nvim-lspconfig
- mason installed：lua-language-server、typescript-language-server

lspconfig setting
```
lspconfig.tsserver.setup({
    capabilities = capabilities,
    on_attach = on_attach
})
```
The same configuration works fine when running Neovim in iTerm2, but errors occur in the Neovide GUI.

Use Neovide GUI，When I open a JS or TS file, the following prompt appears in the status:
`Client tsserver quit with exit code 127 and signal 0. Check log for errors: ~/.local/state/nvim/lsp.log`

here is lsplog: 
```
[START][2024-07-24 16:30:24] LSP logging initiated

[ERROR][2024-07-24 16:30:24] .../vim/lsp/rpc.lua:770	"rpc"	"~/.local/share/nvim/mason/bin/typescript-language-server"	"stderr"	"env: node: No such file or directory\n"
```

**Comment by rchl** [comment]
I think it would be more appropriate to ask that question towards the `lspconfig` plugin?
I don't know specifics of nvim/neovim configuration and its ecosystem.
That said, I think (based on the error alone) that `node` is not in the PATH when the plugin tries to execute `~/.local/share/nvim/mason/bin/typescript-language-server`.
