### ISSUE TITLE
Does not format .tsx files

### ISSUE THREAD

**Issue by majidmadadi** [typescript-language-server/typescript-language-server#912]
LSP does not format .tsx file correctly. 
Os: fedora
Editor: Kate
LSP client config:
` "javascript": {
            "command": ["typescript-language-server", "--stdio"],
            "rootIndicationFileNames": ["package.json", "package-lock.json"],
            "url": "https://github.com/theia-ide/typescript-language-server",
            "highlightingModeRegex": "^JavaScript.*$"
        },`

To reproduce this behavior just format a sample .tsx file.

**Comment by rchl** [comment]
I don't know anything about Kate but it would likely be an issue with wrong languageId being sent (should be `javascriptreact` for `tsx` files.

I found some possibly related config change that might help: https://invent.kde.org/utilities/kate/-/merge_requests/1349/diffs
Try adding `"documentLanguageId": true` to your config.

**Comment by majidmadadi** [comment]
I added that but still not working. Kate is a multi-language editor for linux by the way.

**Comment by majidmadadi** [comment]
I could not send verbose command to LSP server. 
I use this editor: https://kate-editor.org/
To check this just create a simple .tsx file and try to format it with the editor. You should first enable LSP client plugin through the menu Settings/Configure Kate/Plugins.

**Comment by rchl** [comment]
Please provide a simple project and state what exactly do you expect to be formatted and in what way.

I don't want to create my own and potentially waste time reproducing it when for example the contents of `tsconfig.json` can matter a lot.

Failing that, just check if it works in VSCode. If not then your project configuration could be wrong or it's just not supported.

**Comment by Waqar144** [comment]
This is fixed in Kate now. https://bugs.kde.org/show_bug.cgi?id=495805
