### ISSUE TITLE
Server initialization failed with "command '_typescript.applyWorkspaceEdit' already exists"

### ISSUE THREAD

**Issue by adj5672** [typescript-language-server/typescript-language-server#914]
I use this language server with webSocket proxy, since my editor is monaco editor and it is using websocket.

Running webSocket proxy server code is below.

```
import {WebSocketServer} from "ws";
import {createServerProcess, createWebSocketConnection, forward} from "vscode-ws-jsonrpc/server";
import {toSocket} from "vscode-ws-jsonrpc";

const serverPort = 30000;

const webSocketServer = new WebSocketServer({
    port: serverPort,
    perMessageDeflate: false,
}, () => {
    console.log(`Listening to http and ws requests on ${serverPort}`)
});

webSocketServer.on('connection', (client, request) => {
    const serverName = 'typescript-language-server';
    const runCommand = 'typescript-language-server';
    const runArgs = ['--stdio'];
    const spawnOptions = {
        shell: true
    };

    const serverProcess = createServerProcess(serverName, runCommand, runArgs, spawnOptions);
    const socket = toSocket(client);
    const websocketConnection = createWebSocketConnection(socket);

    forward(serverProcess, websocketConnection);
    console.log('Forwarding new client');

    socket.onClose((code, reason) => {
        console.log('Client closed', reason);
        serverProcess.dispose();
    })
})
```

On connect, create process with child_process.spawn and create webSocket connection.

The problem is.. when I use multiple editor, every connection closed except first connection.

Error log said that server initialization is failed since "command '_typescript.applyWorkspaceEdit' already exists".

Is there any solution that can solve this problem? Or this error is occured from client settings?

<img width="501" alt="image" src="https://github.com/user-attachments/assets/c3dd4b76-ecc6-498e-bed9-022f158558f4">

**Comment by rchl** [comment]
Looks like monaco specific issue or design decison. See https://github.com/microsoft/monaco-editor/issues/1957 for example.

**Comment by adj5672** [comment]
thanks, I will check this from monaco editor.

**Comment by adj5672** [comment]
@rchl 
Is there a way to prevent registering workspace/executeCommand when initialize connection?

Since I will not use that commands
