### ISSUE TITLE
How to configure a max line width?

### ISSUE THREAD

**Issue by gjbianco** [typescript-language-server/typescript-language-server#919]
I am trying to set a max line length for formatting my code. Currently, I have to manually break up lines that are too long. I can have ridiculously long lines (>250) that still don't get broken up.

I know the formatting works, as it will fix other issues. e.g. if I break a line up manually, but misalign the indentation, formatting corrects the indentation.

In particular, I expected to find something like `[language].format.maxLineLength: number;` for `workspace/didChangeConfiguration` within the configuration doc (`/docs/configuration.md`: https://github.com/typescript-language-server/typescript-language-server/blob/master/docs/configuration.md).

I do apologize for opening an issue if this is not an appropriate place for the question. I have been completely unable to find any leads on configuring this in my editor, my LSP plugin, or with this language server. I am not intimately familiar with LSP configuration, so I might be misguided in how this option should work. I'm open and appreciative of any and all guidance :slightly_smiling_face:

**Comment by rchl** [comment]
TypeScript doesn't support that.
You'd have to use a dedicated formatter (maybe `clang-format`) or try to request this feature in the TypeScript repo.
