### ISSUE TITLE
Fails to load with syntax error in Kate on KDE Neon

### ISSUE THREAD

**Issue by luciph0r** [typescript-language-server/typescript-language-server#921]
Trying to start it from within Kate results in this syntax error:

```
file:///home/user/.nvm/versions/node/v22.9.0/lib/node_modules/typescript-
language-server/lib/cli.mjs:790
    enableOrNameAndArgs = enableOrNameAndArgs ?? 'help [command]';
                                               ^
SyntaxError: Unexpected token '?'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
[17:41:25 ￼ LSP Client Warning] Server terminated unexpectedly ... NOT 
Restarting [/home/user/.nvm/versions/node/v22.9.0/bin/typescript-language-server --stdio]
```

**Comment by rchl** [comment]
This indicates that your node version is very old.

The node version and path referenced in the error (v22) is NOT being used to start the server. Kate must be using version older than 18.

**Comment by luciph0r** [comment]
If you paid attention to the stack trace before rushing to close it, you can clearly see node version is 22.9.0. I have no other version installed.

**Comment by rchl** [comment]
Check my comment again. I referred to it. Running server from that location doesn't mean that the same nice version is being used to run it.

**Comment by luciph0r** [comment]
But there is no other version of node installed, I downloaded node only for this and it is the latest. Node -v returns 22.9.0 both from user and root accounts.

*From: *Rafał Chłodnicki ***@***.***>
*To: *typescript-language-server/typescript-language-server ***@***.***>
*CC: *luciph0r ***@***.***>; Author ***@***.***>
*Date: *6 Oct 2024 00:45:49
*Subject: *Re: [typescript-language-server/typescript-language-server] Fails to load with syntax error in Kate on KDE Neon (Issue #921)

**Comment by luciph0r** [comment]
Where would it be used from when no other node installation exists on the system? As you can see the path to the node binary being used has the version in it.

*From: *Rafał Chłodnicki ***@***.***>
*To: *typescript-language-server/typescript-language-server ***@***.***>
*CC: *luciph0r ***@***.***>; Author ***@***.***>
*Date: *6 Oct 2024 00:01:33
*Subject: *Re: [typescript-language-server/typescript-language-server] Fails to load with syntax error in Kate on KDE Neon (Issue #921)

**Comment by rchl** [comment]
I guarantee you that there is another node version in your system. 

The path shown is not necessarily the path of the running node. It can be just the path of the script that node is running. 

Run Kate with some other node-based server that works and check the process manager like top to find out the path to the running node.

**Comment by luciph0r** [comment]
There is only one node installation from what I've searched:

```
user@host:/home/user$nvm list
->      v22.9.0
         system
default -> 22 (-> v22.9.0)
iojs -> N/A (default)
unstable -> N/A (default)
node -> stable (-> v22.9.0) (default)
stable -> 22.9 (-> v22.9.0) (default)
lts/* -> lts/iron (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.12 (-> N/A)
lts/fermium -> v14.21.3 (-> N/A)
lts/gallium -> v16.20.2 (-> N/A)
lts/hydrogen -> v18.20.4 (-> N/A)
lts/iron -> v20.17.0 (-> N/A)

user@host:/home/user$which node
/home/user/.nvm/versions/node/v22.9.0/bin/node
user@host:/home/user$node -v
22.9.0
```
There is exactly one directory under /home/user/.nvm/versions/node and that is 22.9.0. Since I am not a node.js developer, I have had zero need for node until installing this LSP and I went for the latest available one. 

I had also forced Kate to use the installed typescript-language-server, which is under this directory:
```

{
    "servers": {
        "javascript": {
            "command": ["/home/user/.nvm/versions/node/v22.9.0/bin/typescript-language-server", "--stdio"],
            "rootIndicationFileNames": ["package.json", "package-lock.json"],
            "url": "https://github.com/theia-ide/typescript-language-server",
            "highlightingModeRegex": "^JavaScript.*$"
        }
    }
}
```
If I just run typescript-language-server --stdio frm the console, it appears to start up with no errors.

**Comment by rchl** [comment]
Again I suggest to list the process which should answer your questions. 
Kate can come with bundled node, for example.

**Comment by rchl** [comment]
Create a JS file with just `throw new Error(process.argv[0])` and point your Kate server configuration to it. What does the error say?

**Comment by luciph0r** [comment]
Kate plugins have to be executable binaries, it can't be pointed to a javascript file. 
```
 LSP Client Warning] Failed to find server binary: /home/user/Documents/code/test.js
Please check your PATH for the binary
```

**Comment by rchl** [comment]
Then temporarily replace contents of `file:///home/user/.nvm/versions/node/v22.9.0/lib/node_modules/typescript-
language-server/lib/cli.mjs` with my code and rerun.

**Comment by luciph0r** [comment]
```
file:///home/user/.nvm/versions/node/v22.9.0/lib/node_modules/typescript-language-server/lib/cli.mjs:2
throw new Error(process.argv[0]);
      ^
Error: /usr/bin/node
    at file:///home/user/.nvm/versions/node/v22.9.0/lib/node_modules/typescript-language-server/lib/cli.mjs:2:7
    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
[17:51:09 ￼ LSP Client Warning] Server terminated unexpectedly ... NOT Restarting [/home/user/.nvm/versions/node/v22.9.0/bin/typescript-language-server --stdio]
```

**Comment by rchl** [comment]
There you have your answer - you have another node instance at `/usr/bin/node`.

**Comment by luciph0r** [comment]
that's the system executable - it points to the same version of node.

**Comment by rchl** [comment]
You are being a bit difficult here. 
Please take it as an answer that you have an old version of node in your system that is being used in this case. 

Just run `/usr/bin/node --version` and you'll see. You have to upgrade your system node version of convince Kate to use your nose version from the nvm.

**Comment by luciph0r** [comment]
I removed the system node. Now going to force it to use the one in .nvm.

**Comment by luciph0r** [comment]
I removed the system node. Finally works now! Thanks for your patience :)
