### ISSUE TITLE
LSP does not properly narrow types

### ISSUE THREAD

**Issue by aryanjassal** [typescript-language-server/typescript-language-server#924]
I have a type defined such that it is a union of two individual types. Each type has a `type` field with a constant, which can be used to select one-or-other file type.

```ts
type SuccessMessage = {
  type: 'success';
  success: boolean;
};

type ErrorMessage = {
  type: 'error';
  code: string;
  reason?: string;
};

type SuccessOrErrorMessage = SuccessMessage | ErrorMessage;
```

A response of type `SuccessOrErrorMessage` gets wrapped in a `JSONRPCResponseResult` of the following type.

```ts
type JSONRPCResponseMetadata = Partial<{
    timeout: number | null;
}>;
/**
 * `T` is the result you want to specify.
 *
 * `M` is the metadata you want to specify.
 *
 * Metadata can also be specified on `T.metadata`
 */
type JSONRPCResponseResult<T extends JSONObject = JSONObject, M extends JSONObject = JSONObject> = {
    metadata?: JSONObject & JSONRPCResponseMetadata & Omit<T['metadata'] & M, keyof JSONRPCResponseMetadata>;
} & Omit<T, 'metadata'>;
```

Then, in a condition like this, it would be expected that the type would be deduced to either `SuccessMessage` or `ErrorMessage`, but this does not happen.

```ts
if (data.type !== 'success') {
  expect(data.code).toEqual('ENOENT');  // Property 'code' does not exist on type 'JSONRPCResponseResult<SuccessOrErrorMessage>'.
  expect(data.reason).toEqual(dirPath3);  // Property 'code' does not exist on type 'JSONRPCResponseResult<SuccessOrErrorMessage>'.
  // Hoverdocs show that the type has not been successfully inferred.
}
```

I tried to make a minimal example of this, but in that minimal example, I can see that it works perfectly.

```ts
type Type1 = {
  type: 'a';
  field1: string;
};

type Type2 = {
  type: 'b';
  field2: string;
};

type Combo = Type1 | Type2;

type Alias<T> = T extends object ? { [K in keyof T]: T[K] } : never;

const inst1: Combo = { type: 'a', field1: 'value1' };
const inst2: Alias<Combo> = { type: 'a', field1: 'value1' };

if (inst1.type === 'a') {
  console.log(inst1)
}

if (inst2.type === 'a') {
  console.log(inst2)
}
```

This has no errors or warnings, and the hoverdocs also show the correct type hints. The code is not wrong, as these warnings are not present on JetBrains WebStorm on the exact same codebase.

**Comment by rchl** [comment]
The difference could come from differences in project configuration. If you don't have `tsconfig.json` at the project root then implicit defaults are used which could differ for this server vs. webstorm.

Otherwise the difference could be due to use of different typescript version. The typechecking is being done by typescript and not this server. This server uses project-local typescript by default, not sure what webstorm does.

**Comment by aryanjassal** [comment]
I do actually have a `tsconfig.json` and `tsconfig.build.json` in my project tree.

`tsconfig.json`
```json
{
  "compilerOptions": {
    "outDir": "./dist",
    "tsBuildInfoFile": "./dist/tsbuildinfo",
    "incremental": true,
    "sourceMap": true,
    "declaration": true,
    "allowJs": true,
    "strictNullChecks": true,
    "noImplicitAny": false,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "module": "CommonJS",
    "target": "ES2022",
    "baseUrl": "./src",
    "paths": {
      "@": ["index"],
      "@/*": ["*"]
    },
    "noEmit": true
  },
  "include": [
    "./src/**/*",
    "./src/**/*.json",
    "./tests/**/*",
    "./scripts/**/*",
    "./benches/**/*"
  ],
  "ts-node": {
    "require": ["tsconfig-paths/register"],
    "transpileOnly": true,
    "swc": true
  }
}
```

`tsconfig.build.json`
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "rootDir": "./src",
    "noEmit": false,
    "stripInternal": true
  },
  "exclude": [
    "./tests/**/*",
    "./scripts/**/*",
    "./benches/**/*"
  ]
}
```

Also, the type inferencing in the minimal example was working without any config file as it was a single temp file I had made to test it out.

NixOS is used for development, and the development shell enforces certain versions of typescript and other dependencies, so differing versions of typescript on the system could not have caused this.

I'm not sure if this is relevant or not, but I also tested this on VS code, and it also behaves similar to neovim. I am using the nightly TS and JS extension for that.

**Comment by aryanjassal** [comment]
I use a slightly different script for compilation, but the code compiles and runs without issues. I have run tests and also used the relevant code after building, and never has the project crashed despite the LSP's complaints.

**Comment by rchl** [comment]
Well, some builders can ignore type errors.
Does `tsc` report the same errors that you see with this server?

**Comment by aryanjassal** [comment]
Huh. Running `npx tsc` does give me the errors I was getting on the server. So, does this mean that the issue is with typescript? Or is to something to do with my project? I'm not sure how code with errors is being compiled and run without issues.

**Comment by rchl** [comment]
I think you are using `ts-node` which does not use typescript directly. I don't know exactly how it works.

But yes, this is not related to this server. You can ask at the TypeScript repo for why it behaves like that and whether it's expected or not.
